window.__MANIFEST__ = [
  {
    "day": 1,
    "folder": "Day-1",
    "title": "Day 1",
    "slides": [
      "https://lh3.googleusercontent.com/d/1An-LF_vB-mDz6PGsqtTc9ltNH4sh7S7o",
      "https://lh3.googleusercontent.com/d/19IzIHs5g378AoHPXVs_m-PKDfmKxKxkB",
      "https://lh3.googleusercontent.com/d/1XC9mObRLTfi30KsPHW3VoILHe4TQ3L8d",
      "https://lh3.googleusercontent.com/d/13DsFpc2MNyLj_HZNP5TtXUbvgn1p-8TL",
      "https://lh3.googleusercontent.com/d/18Xo_VnTa3DgpY787e_xiwpMaJVW9q8du",
      "https://lh3.googleusercontent.com/d/16seLHJzD7AZFt88rHqkKtQdO0pOp-5cO",
      "https://lh3.googleusercontent.com/d/1xc9RimUP6dk1oITStp0G7RW9ARcXHKWZ",
      "https://lh3.googleusercontent.com/d/1GVFAOp0O-SEYdnw7BA299y_X6cdY5U4R",
      "https://lh3.googleusercontent.com/d/1l_7do1m2cWupisPtVch3DEsUcRYb3c-E",
      "https://lh3.googleusercontent.com/d/1NgCV1nhNyQlHGfFjmB5X5-cURhUBWljN",
      "https://lh3.googleusercontent.com/d/1voJVP2acV5o60BhLMdZzKDCdCOEyhlde",
      "https://lh3.googleusercontent.com/d/1zFD4VlBRyj8OoefovvfzYeiT-SIo_mOX",
      "https://lh3.googleusercontent.com/d/19HHTGmfAMPuqnKIU_62Zc5_9qDRvDD9g",
      "https://lh3.googleusercontent.com/d/1mCLuFzs3jceKgi4DjbG60o4qLX6ZFnMr",
      "https://lh3.googleusercontent.com/d/10sWmYz5RT0btatmnrqxNQJkjEwS1GTkB",
      "https://lh3.googleusercontent.com/d/18waogAn2gaUqYAYHSRDfkuCvKRlUxvOo",
      "https://lh3.googleusercontent.com/d/1gBcEa-QhNU50MP8rd8-CHWNhKBNJs4el",
      "https://lh3.googleusercontent.com/d/17FwB5B-mlMPfLqo90rFvHrpghYSm4WKG",
      "https://lh3.googleusercontent.com/d/1hTLv6prhon_nReQJIri3fxfhV_TDxRIA",
      "https://lh3.googleusercontent.com/d/1qB9Inb8a4PEE7nqYVXTUDBBwfgt6bCfb",
      "https://lh3.googleusercontent.com/d/138kGs953iLyUPPeYbnnDbHsfVqF8FeaC",
      "https://lh3.googleusercontent.com/d/1C0gm_7P7wQFFWAUXOm8BUKy6AA8Cq5Jb"
    ]
  },
  {
    "day": 2,
    "folder": "Day-2",
    "title": "Day 2",
    "slides": [
      "https://lh3.googleusercontent.com/d/1xm57MUraw9YIKb95o-_8sx2bgvk8XFre",
      "https://lh3.googleusercontent.com/d/14_H5gbj8xNRsuwix3A4mqv7Px-n-XpZJ",
      "https://lh3.googleusercontent.com/d/1T7Flf7EjnZlkghroxufZ7adVdCGtbVrD",
      "https://lh3.googleusercontent.com/d/1IPuloH2h6N4GjlBDigRZ4FVjoxBv9cWL",
      "https://lh3.googleusercontent.com/d/1J1d5iOzJ8I3WDZ0DZSmkkgEBS9fIem08",
      "https://lh3.googleusercontent.com/d/1CoNe6lm89qsU4hDEOT8pOo3amlzTquY7",
      "https://lh3.googleusercontent.com/d/1GQ79Uts6mVMCHZHFjoXyJM6hJBIcYhko",
      "https://lh3.googleusercontent.com/d/1fOZRhwMe2g5tIGQKagOGg_E03k6ilCta",
      "https://lh3.googleusercontent.com/d/1bT2nFZyO6poNEUIk9sVqP6YQihDsZqDk",
      "https://lh3.googleusercontent.com/d/1dZk2m6pZdnuc2znadb4CrkcthMKaesLK",
      "https://lh3.googleusercontent.com/d/1-ARloapRhr9S4lOLbCEpv-irFX-EtqCn",
      "https://lh3.googleusercontent.com/d/1DQSVJ09Rva5w2NEvKt3TwDfj68I5B56c",
      "https://lh3.googleusercontent.com/d/1sS-JoIx1tsq_qwVXtbD8PTrswn_VvCY3",
      "https://lh3.googleusercontent.com/d/1JYiuJ1c_moFNoGVjBGKnUk8NftTYY0pL",
      "https://lh3.googleusercontent.com/d/13kTEaDrBlOArPUEZ_Nm9nh6PKWAzaxjJ",
      "https://lh3.googleusercontent.com/d/1SyYOT_2QJjWyq0nI93BDd-KzA7YkL4oE",
      "https://lh3.googleusercontent.com/d/1c0wwW1VbiRCFiB9GR6h3d9PVeMn_MmOs",
      "https://lh3.googleusercontent.com/d/11YABEqxqRMAkybtpwLT7kyj8ZFx6z0Nv",
      "https://lh3.googleusercontent.com/d/1uoSuZw6Wzf1hXJ9u9dG4CnkiuxsIRdJM"
    ]
  },
  {
    "day": 3,
    "folder": "Day-3",
    "title": "Day 3",
    "slides": [
      "https://lh3.googleusercontent.com/d/1hLg6m6cYTkE-NmyUtlSgEeT9S83365jN",
      "https://lh3.googleusercontent.com/d/1W07i6I2DpkUQfcX5IXIrrruevZEs-mx6",
      "https://lh3.googleusercontent.com/d/1poO_NXIvdv2n3gwiGjKKjwuh8W5QSDap",
      "https://lh3.googleusercontent.com/d/1nJMIRr8H9MEEXvTgS-SXbCo3SAGcWRfZ",
      "https://lh3.googleusercontent.com/d/1wUZ6Z6qYwl4L2awmrIPP9hDrHPUr3iWl",
      "https://lh3.googleusercontent.com/d/1nsEh9XvangKT3MOj01lFTkKapS1ws2jW",
      "https://lh3.googleusercontent.com/d/1n1ZWjYQjwAe5X3cQ0_FNZBmfLLmre4VP",
      "https://lh3.googleusercontent.com/d/18_vGnyKJjdJ8JwgK5jB8cgdhyzNaya7b",
      "https://lh3.googleusercontent.com/d/1XbIHnWRF2N9hvWEIYveQ0dwN36PgOCK4",
      "https://lh3.googleusercontent.com/d/1ELvhxiQN168PPwFN092D3gASUDx_ekhV",
      "https://lh3.googleusercontent.com/d/116vham6vy0dzm7VvT3DYeBEha2ce1Jew",
      "https://lh3.googleusercontent.com/d/1PReoPO3IpL_FxMvbmrXuEETwQmPlL8BF",
      "https://lh3.googleusercontent.com/d/1mjfEvAUA4dVTX38TTK6HzQDzW7fx2snq",
      "https://lh3.googleusercontent.com/d/16t1C9-AkwKHuIFHmAQrk9NO5H9egeFD2",
      "https://lh3.googleusercontent.com/d/1wQ5wDAjQAjCev8pyeUuVlYDdHLsA1ZYP",
      "https://lh3.googleusercontent.com/d/128KErpGY678GiYU7H-hAfcmiB6CMV-Uc",
      "https://lh3.googleusercontent.com/d/1TQlQDORyrJm0LQ08HqInrtqTowARwT0q",
      "https://lh3.googleusercontent.com/d/1mMPAAVqEdyn1mZ2WmcKlFaCp0Zpy0Lrp",
      "https://lh3.googleusercontent.com/d/1mTk1c94pCBjFY-_YnExL2Nbg1ucnKGgl",
      "https://lh3.googleusercontent.com/d/1TBvviPzv_HxopGe4IrCyxGkcujmANwD7",
      "https://lh3.googleusercontent.com/d/1fSIbx6ufuzWRfC7W1w2PFtKUoQNl7i-F",
      "https://lh3.googleusercontent.com/d/1O7mcVQO7unEJpkrtlETlmgvRKp0K0Ecu",
      "https://lh3.googleusercontent.com/d/1QxKAzE5QXOpW5Md4OaFwfuIy5J6_pPxD",
      "https://lh3.googleusercontent.com/d/1edTLPCUeAg3zzCQYQjPmvM-szC5WK6Ea",
      "https://lh3.googleusercontent.com/d/1ur6NgGqIf2HR6sPw3qSYmV3Xa0ZikkdX",
      "https://lh3.googleusercontent.com/d/18lSev8LpxiLHxTZuF5oG-hExXTq52ZAK",
      "https://lh3.googleusercontent.com/d/16-HgPNlJhso7qkScc8SvmSeh0p79wuyX",
      "https://lh3.googleusercontent.com/d/1dQsRp2O85as8LnBNePAIndMTrLmcmBZC",
      "https://lh3.googleusercontent.com/d/1qgfS3Ag8ne730jra9q83dblox3s5SQYU",
      "https://lh3.googleusercontent.com/d/1hQJ_Y-Fp90F3s5PgIUMmVNfy6i2e7fAU"
    ]
  }
];
