/* ============================================================
   DSA & ML/AI Visualizer — Topic Metadata
   224 entries used by the hub page (search/filter/sort) and
   topic pages (prev/next navigation).
   Loaded via <script> tag — no fetch().
   ============================================================ */

var DSA_DATA = [

  /* ──────────────────────────────────────────────────────────
     FOUNDATIONS  (2)
     ────────────────────────────────────────────────────────── */
  { id: "logic-building", title: "Logic Building", category: "Foundations", difficulty: "Easy", description: "Foundational problem-solving patterns and logical thinking for programming.", problemCount: 10, timeComplexity: "\u2014", href: "foundations/logic-building.html", tags: ["logic","basics","patterns"], section: "dsa" },
  { id: "complexity-analysis", title: "Complexity Analysis", category: "Foundations", difficulty: "Easy", description: "Big O notation, time and space complexity analysis for algorithms.", problemCount: 8, timeComplexity: "\u2014", href: "foundations/complexity-analysis.html", tags: ["big-o","time","space","analysis"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     DATA STRUCTURES  (8)
     ────────────────────────────────────────────────────────── */
  { id: "arrays", title: "Arrays", category: "Data Structures", difficulty: "Easy", description: "Contiguous memory storage with O(1) random access by index.", problemCount: 15, timeComplexity: "O(1) access", href: "data-structures/arrays.html", tags: ["array","sequential","index"], section: "dsa" },
  { id: "linked-lists", title: "Linked Lists", category: "Data Structures", difficulty: "Easy", description: "Sequential nodes connected via pointers, supporting O(1) insert/delete at known positions.", problemCount: 15, timeComplexity: "O(n) access", href: "data-structures/linked-lists.html", tags: ["linked-list","nodes","pointers"], section: "dsa" },
  { id: "stacks", title: "Stacks", category: "Data Structures", difficulty: "Easy", description: "LIFO data structure supporting push and pop in O(1).", problemCount: 12, timeComplexity: "O(1) push/pop", href: "data-structures/stacks.html", tags: ["stack","lifo","push","pop"], section: "dsa" },
  { id: "queues", title: "Queues", category: "Data Structures", difficulty: "Easy", description: "FIFO data structure supporting enqueue and dequeue in O(1).", problemCount: 10, timeComplexity: "O(1) enqueue", href: "data-structures/queues.html", tags: ["queue","fifo","enqueue"], section: "dsa" },
  { id: "hash-tables", title: "Hash Tables", category: "Data Structures", difficulty: "Medium", description: "Key-value storage with O(1) average lookup using hash functions.", problemCount: 15, timeComplexity: "O(1) avg", href: "data-structures/hash-tables.html", tags: ["hash","map","dictionary"], section: "dsa" },
  { id: "heaps", title: "Heaps / Priority Queues", category: "Data Structures", difficulty: "Medium", description: "Complete binary tree maintaining heap property for O(log n) insert and extract.", problemCount: 12, timeComplexity: "O(log n)", href: "data-structures/heaps.html", tags: ["heap","priority-queue","binary"], section: "dsa" },
  { id: "tries", title: "Tries", category: "Data Structures", difficulty: "Medium", description: "Tree-like structure for efficient string prefix operations.", problemCount: 10, timeComplexity: "O(m) lookup", href: "data-structures/tries.html", tags: ["trie","prefix","string"], section: "dsa" },
  { id: "matrix-grid", title: "Matrix / Grid", category: "Data Structures", difficulty: "Easy", description: "2D array operations including traversal, rotation, spiral order, and search.", problemCount: 12, timeComplexity: "O(m\u00d7n)", href: "data-structures/matrix-grid.html", tags: ["matrix","grid","2d-array"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     ADVANCED DATA STRUCTURES  (17)
     ────────────────────────────────────────────────────────── */
  { id: "segment-trees", title: "Segment Trees", category: "Advanced Data Structures", difficulty: "Hard", description: "Tree for efficient range queries and updates in O(log n).", problemCount: 10, timeComplexity: "O(log n)", href: "advanced-data-structures/segment-trees.html", tags: ["segment-tree","range-query"], section: "dsa" },
  { id: "union-find", title: "Union-Find (Disjoint Set)", category: "Advanced Data Structures", difficulty: "Medium", description: "Tracks disjoint sets with near O(1) union and find operations.", problemCount: 10, timeComplexity: "O(\u03b1(n))", href: "advanced-data-structures/union-find.html", tags: ["union-find","disjoint-set"], section: "dsa" },
  { id: "monotonic-stack-queue", title: "Monotonic Stack / Queue", category: "Advanced Data Structures", difficulty: "Medium", description: "Stack or queue maintaining monotonic order for range extrema queries.", problemCount: 8, timeComplexity: "O(n)", href: "advanced-data-structures/monotonic-stack-queue.html", tags: ["monotonic","stack","queue"], section: "dsa" },
  { id: "b-tree", title: "B-Tree / B+ Tree", category: "Advanced Data Structures", difficulty: "Hard", description: "Self-balancing tree with high branching factor optimized for disk access.", problemCount: 5, timeComplexity: "O(log n)", href: "advanced-data-structures/b-tree.html", tags: ["b-tree","database","index"], section: "dsa" },
  { id: "skip-list", title: "Skip List", category: "Advanced Data Structures", difficulty: "Medium", description: "Layered linked list providing O(log n) average search.", problemCount: 5, timeComplexity: "O(log n) avg", href: "advanced-data-structures/skip-list.html", tags: ["skip-list","probabilistic"], section: "dsa" },
  { id: "bloom-filter", title: "Bloom Filter", category: "Advanced Data Structures", difficulty: "Medium", description: "Probabilistic set membership test with no false negatives.", problemCount: 5, timeComplexity: "O(k)", href: "advanced-data-structures/bloom-filter.html", tags: ["bloom-filter","probabilistic","hash"], section: "dsa" },
  { id: "lru-cache", title: "LRU Cache", category: "Advanced Data Structures", difficulty: "Medium", description: "Least Recently Used cache with O(1) get/put using hash map + doubly linked list.", problemCount: 8, timeComplexity: "O(1)", href: "advanced-data-structures/lru-cache.html", tags: ["cache","lru","linked-list"], section: "dsa" },
  { id: "fenwick-tree", title: "Fenwick Tree (BIT)", category: "Advanced Data Structures", difficulty: "Medium", description: "Compact tree for O(log n) prefix sum queries and point updates.", problemCount: 8, timeComplexity: "O(log n)", href: "advanced-data-structures/fenwick-tree.html", tags: ["fenwick","bit","prefix-sum"], section: "dsa" },
  { id: "sparse-table", title: "Sparse Table", category: "Advanced Data Structures", difficulty: "Medium", description: "O(1) range min/max queries after O(n log n) preprocessing.", problemCount: 5, timeComplexity: "O(1) query", href: "advanced-data-structures/sparse-table.html", tags: ["sparse-table","range-query","static"], section: "dsa" },
  { id: "deque", title: "Deque", category: "Advanced Data Structures", difficulty: "Easy", description: "Double-ended queue allowing O(1) insertion/deletion at both ends.", problemCount: 6, timeComplexity: "O(1)", href: "advanced-data-structures/deque.html", tags: ["deque","double-ended"], section: "dsa" },
  { id: "circular-buffer", title: "Circular Buffer", category: "Advanced Data Structures", difficulty: "Easy", description: "Fixed-size buffer wrapping around, overwriting oldest data when full.", problemCount: 4, timeComplexity: "O(1)", href: "advanced-data-structures/circular-buffer.html", tags: ["ring-buffer","circular","stream"], section: "dsa" },
  { id: "doubly-linked-list", title: "Doubly Linked List", category: "Advanced Data Structures", difficulty: "Easy", description: "Each node points to both next and previous, enabling O(1) deletion.", problemCount: 8, timeComplexity: "O(1) delete", href: "advanced-data-structures/doubly-linked-list.html", tags: ["doubly-linked","bidirectional"], section: "dsa" },
  { id: "treap", title: "Treap", category: "Advanced Data Structures", difficulty: "Hard", description: "Randomized BST maintaining heap property on priorities.", problemCount: 5, timeComplexity: "O(log n) exp", href: "advanced-data-structures/treap.html", tags: ["treap","randomized","bst"], section: "dsa" },
  { id: "splay-tree", title: "Splay Tree", category: "Advanced Data Structures", difficulty: "Hard", description: "Self-adjusting BST moving accessed elements to root via rotations.", problemCount: 5, timeComplexity: "O(log n) amort", href: "advanced-data-structures/splay-tree.html", tags: ["splay","self-adjusting","bst"], section: "dsa" },
  { id: "hash-map-internals", title: "Hash Map Internals", category: "Advanced Data Structures", difficulty: "Medium", description: "Collision resolution: chaining, open addressing, Robin Hood hashing.", problemCount: 6, timeComplexity: "O(1) avg", href: "advanced-data-structures/hash-map-internals.html", tags: ["hash-map","collision","probing"], section: "dsa" },
  { id: "persistent-data-structures", title: "Persistent Data Structures", category: "Advanced Data Structures", difficulty: "Hard", description: "Immutable structures preserving previous versions on modification.", problemCount: 3, timeComplexity: "O(log n)", href: "advanced-data-structures/persistent-data-structures.html", tags: ["persistent","immutable","versioned"], section: "dsa" },
  { id: "bitwise-trie", title: "Bitwise Trie (XOR Trie)", category: "Advanced Data Structures", difficulty: "Medium", description: "Trie on binary representations for efficient max XOR queries.", problemCount: 5, timeComplexity: "O(32)", href: "advanced-data-structures/bitwise-trie.html", tags: ["xor-trie","bitwise","trie"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     SORTING  (11)
     ────────────────────────────────────────────────────────── */
  { id: "bubble-sort", title: "Bubble Sort", category: "Sorting", difficulty: "Easy", description: "Repeatedly swaps adjacent elements if in wrong order.", problemCount: 5, timeComplexity: "O(n\u00b2)", href: "sorting/bubble-sort.html", tags: ["sorting","comparison","stable"], section: "dsa" },
  { id: "selection-sort", title: "Selection Sort", category: "Sorting", difficulty: "Easy", description: "Finds minimum in unsorted portion and places it at the front.", problemCount: 5, timeComplexity: "O(n\u00b2)", href: "sorting/selection-sort.html", tags: ["sorting","comparison","in-place"], section: "dsa" },
  { id: "insertion-sort", title: "Insertion Sort", category: "Sorting", difficulty: "Easy", description: "Builds sorted array one element at a time by inserting into correct position.", problemCount: 5, timeComplexity: "O(n\u00b2)", href: "sorting/insertion-sort.html", tags: ["sorting","comparison","stable","adaptive"], section: "dsa" },
  { id: "merge-sort", title: "Merge Sort", category: "Sorting", difficulty: "Medium", description: "Divides array in half, recursively sorts, then merges sorted halves.", problemCount: 8, timeComplexity: "O(n log n)", href: "sorting/merge-sort.html", tags: ["sorting","divide-conquer","stable"], section: "dsa" },
  { id: "quick-sort", title: "Quick Sort", category: "Sorting", difficulty: "Medium", description: "Partitions around a pivot, recursively sorts sub-arrays.", problemCount: 8, timeComplexity: "O(n log n) avg", href: "sorting/quick-sort.html", tags: ["sorting","divide-conquer","in-place"], section: "dsa" },
  { id: "heap-sort", title: "Heap Sort", category: "Sorting", difficulty: "Medium", description: "Builds a max-heap then repeatedly extracts the maximum.", problemCount: 6, timeComplexity: "O(n log n)", href: "sorting/heap-sort.html", tags: ["sorting","heap","in-place"], section: "dsa" },
  { id: "counting-sort", title: "Counting Sort", category: "Sorting", difficulty: "Easy", description: "Counts occurrences for integer keys, non-comparison based.", problemCount: 5, timeComplexity: "O(n+k)", href: "sorting/counting-sort.html", tags: ["sorting","non-comparison","integer"], section: "dsa" },
  { id: "radix-sort", title: "Radix Sort", category: "Sorting", difficulty: "Medium", description: "Sorts digit by digit from least to most significant.", problemCount: 5, timeComplexity: "O(d\u00b7(n+k))", href: "sorting/radix-sort.html", tags: ["sorting","non-comparison","digit"], section: "dsa" },
  { id: "tim-sort", title: "Tim Sort", category: "Sorting", difficulty: "Hard", description: "Hybrid of merge sort and insertion sort exploiting existing runs.", problemCount: 5, timeComplexity: "O(n log n)", href: "sorting/tim-sort.html", tags: ["sorting","hybrid","adaptive"], section: "dsa" },
  { id: "bucket-sort", title: "Bucket Sort", category: "Sorting", difficulty: "Medium", description: "Distributes elements into buckets, sorts each, then concatenates.", problemCount: 5, timeComplexity: "O(n+k) avg", href: "sorting/bucket-sort.html", tags: ["sorting","distribution","non-comparison"], section: "dsa" },
  { id: "shell-sort", title: "Shell Sort", category: "Sorting", difficulty: "Medium", description: "Insertion sort with decreasing gap sequences for better performance.", problemCount: 5, timeComplexity: "O(n^1.5)", href: "sorting/shell-sort.html", tags: ["sorting","gap-sequence","in-place"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     SEARCHING  (6)
     ────────────────────────────────────────────────────────── */
  { id: "binary-search", title: "Binary Search", category: "Searching", difficulty: "Easy", description: "Halves search space each step in sorted array.", problemCount: 15, timeComplexity: "O(log n)", href: "searching/binary-search.html", tags: ["search","sorted","divide"], section: "dsa" },
  { id: "dfs", title: "Depth-First Search", category: "Searching", difficulty: "Medium", description: "Explores as deep as possible before backtracking.", problemCount: 12, timeComplexity: "O(V+E)", href: "searching/dfs.html", tags: ["graph","traversal","stack"], section: "dsa" },
  { id: "bfs", title: "Breadth-First Search", category: "Searching", difficulty: "Medium", description: "Explores all neighbors at current depth before going deeper.", problemCount: 12, timeComplexity: "O(V+E)", href: "searching/bfs.html", tags: ["graph","traversal","queue"], section: "dsa" },
  { id: "ternary-search", title: "Ternary Search", category: "Searching", difficulty: "Easy", description: "Finds min/max of unimodal function by dividing into thirds.", problemCount: 4, timeComplexity: "O(log n)", href: "searching/ternary-search.html", tags: ["search","unimodal","optimization"], section: "dsa" },
  { id: "interpolation-search", title: "Interpolation Search", category: "Searching", difficulty: "Medium", description: "Estimates position based on value distribution in sorted data.", problemCount: 4, timeComplexity: "O(log log n) avg", href: "searching/interpolation-search.html", tags: ["search","sorted","estimation"], section: "dsa" },
  { id: "exponential-search", title: "Exponential Search", category: "Searching", difficulty: "Easy", description: "Doubles bound to find range, then binary searches within.", problemCount: 4, timeComplexity: "O(log n)", href: "searching/exponential-search.html", tags: ["search","unbounded","binary"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     TREE ALGORITHMS  (3)
     ────────────────────────────────────────────────────────── */
  { id: "binary-tree", title: "Binary Tree", category: "Tree Algorithms", difficulty: "Medium", description: "Tree where each node has at most two children. Covers traversals.", problemCount: 15, timeComplexity: "O(n) traversal", href: "tree-algorithms/binary-tree.html", tags: ["tree","traversal","inorder","preorder"], section: "dsa" },
  { id: "binary-search-tree", title: "Binary Search Tree", category: "Tree Algorithms", difficulty: "Medium", description: "Binary tree with left < root < right property for O(log n) search.", problemCount: 12, timeComplexity: "O(log n) avg", href: "tree-algorithms/binary-search-tree.html", tags: ["bst","search","insert","delete"], section: "dsa" },
  { id: "avl-red-black-trees", title: "AVL & Red-Black Trees", category: "Tree Algorithms", difficulty: "Hard", description: "Self-balancing BSTs maintaining O(log n) height via rotations.", problemCount: 8, timeComplexity: "O(log n)", href: "tree-algorithms/avl-red-black-trees.html", tags: ["avl","red-black","balanced","rotation"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     GRAPH ALGORITHMS  (20)
     ────────────────────────────────────────────────────────── */
  { id: "graph-representation", title: "Graph Representation", category: "Graph Algorithms", difficulty: "Easy", description: "Adjacency matrix, adjacency list, and edge list representations.", problemCount: 6, timeComplexity: "\u2014", href: "graph-algorithms/graph-representation.html", tags: ["graph","adjacency","matrix","list"], section: "dsa" },
  { id: "dijkstras", title: "Dijkstra's Algorithm", category: "Graph Algorithms", difficulty: "Medium", description: "Finds shortest paths from source in weighted graph with non-negative edges.", problemCount: 10, timeComplexity: "O((V+E) log V)", href: "graph-algorithms/dijkstras.html", tags: ["shortest-path","weighted","greedy"], section: "dsa" },
  { id: "bellman-ford", title: "Bellman-Ford Algorithm", category: "Graph Algorithms", difficulty: "Medium", description: "Shortest paths handling negative weights, detects negative cycles.", problemCount: 8, timeComplexity: "O(V\u00b7E)", href: "graph-algorithms/bellman-ford.html", tags: ["shortest-path","negative-weight"], section: "dsa" },
  { id: "floyd-warshall", title: "Floyd-Warshall Algorithm", category: "Graph Algorithms", difficulty: "Medium", description: "All-pairs shortest paths via dynamic programming.", problemCount: 6, timeComplexity: "O(V\u00b3)", href: "graph-algorithms/floyd-warshall.html", tags: ["all-pairs","shortest-path","dp"], section: "dsa" },
  { id: "topological-sort", title: "Topological Sort", category: "Graph Algorithms", difficulty: "Medium", description: "Linear ordering of DAG vertices respecting edge direction.", problemCount: 8, timeComplexity: "O(V+E)", href: "graph-algorithms/topological-sort.html", tags: ["dag","ordering","dependencies"], section: "dsa" },
  { id: "minimum-spanning-tree", title: "Minimum Spanning Tree (Kruskal/Prim)", category: "Graph Algorithms", difficulty: "Medium", description: "Connects all vertices with minimum total edge weight.", problemCount: 8, timeComplexity: "O(E log V)", href: "graph-algorithms/minimum-spanning-tree.html", tags: ["mst","kruskal","prim","spanning"], section: "dsa" },
  { id: "a-star-search", title: "A* Search Algorithm", category: "Graph Algorithms", difficulty: "Hard", description: "Informed pathfinding using heuristics, combining Dijkstra's with greedy best-first.", problemCount: 8, timeComplexity: "O(E)", href: "graph-algorithms/a-star-search.html", tags: ["pathfinding","heuristic","a-star"], section: "dsa" },
  { id: "tarjans-scc", title: "Tarjan's SCC", category: "Graph Algorithms", difficulty: "Hard", description: "Finds strongly connected components in one DFS pass.", problemCount: 6, timeComplexity: "O(V+E)", href: "graph-algorithms/tarjans-scc.html", tags: ["scc","strongly-connected","dfs"], section: "dsa" },
  { id: "kosarajus-scc", title: "Kosaraju's SCC", category: "Graph Algorithms", difficulty: "Hard", description: "Two-pass DFS to find strongly connected components.", problemCount: 5, timeComplexity: "O(V+E)", href: "graph-algorithms/kosarajus-scc.html", tags: ["scc","transpose","two-pass"], section: "dsa" },
  { id: "euler-path-circuit", title: "Euler Path & Circuit", category: "Graph Algorithms", difficulty: "Medium", description: "Path/circuit visiting every edge exactly once (Hierholzer's).", problemCount: 5, timeComplexity: "O(E)", href: "graph-algorithms/euler-path-circuit.html", tags: ["euler","circuit","edge-traversal"], section: "dsa" },
  { id: "floyd-cycle-detection", title: "Floyd's Cycle Detection", category: "Graph Algorithms", difficulty: "Medium", description: "Tortoise and Hare algorithm to detect cycles with two pointers.", problemCount: 8, timeComplexity: "O(n)", href: "graph-algorithms/floyd-cycle-detection.html", tags: ["cycle","two-pointer","linked-list"], section: "dsa" },
  { id: "bipartite-check", title: "Bipartite Graph Check", category: "Graph Algorithms", difficulty: "Medium", description: "Determines if graph can be 2-colored using BFS/DFS.", problemCount: 6, timeComplexity: "O(V+E)", href: "graph-algorithms/bipartite-check.html", tags: ["bipartite","coloring","bfs"], section: "dsa" },
  { id: "network-flow", title: "Network Flow (Ford-Fulkerson)", category: "Graph Algorithms", difficulty: "Hard", description: "Computes max flow via augmenting paths.", problemCount: 6, timeComplexity: "O(V\u00b7E\u00b2)", href: "graph-algorithms/network-flow.html", tags: ["max-flow","augmenting-path","min-cut"], section: "dsa" },
  { id: "hungarian-algorithm", title: "Hungarian Algorithm", category: "Graph Algorithms", difficulty: "Hard", description: "Optimal assignment matching between two sets in O(n\u00b3).", problemCount: 4, timeComplexity: "O(n\u00b3)", href: "graph-algorithms/hungarian-algorithm.html", tags: ["assignment","matching","bipartite"], section: "dsa" },
  { id: "articulation-points-bridges", title: "Articulation Points & Bridges", category: "Graph Algorithms", difficulty: "Hard", description: "Finds cut vertices/edges whose removal disconnects graph.", problemCount: 5, timeComplexity: "O(V+E)", href: "graph-algorithms/articulation-points-bridges.html", tags: ["cut-vertex","bridge","connectivity"], section: "dsa" },
  { id: "hamiltonian-path", title: "Hamiltonian Path & Cycle", category: "Graph Algorithms", difficulty: "Hard", description: "Path/cycle visiting every vertex exactly once (NP-complete).", problemCount: 5, timeComplexity: "O(n!)", href: "graph-algorithms/hamiltonian-path.html", tags: ["hamiltonian","np-complete","backtracking"], section: "dsa" },
  { id: "graph-coloring", title: "Graph Coloring", category: "Graph Algorithms", difficulty: "Hard", description: "Assign minimum colors so no adjacent vertices share a color.", problemCount: 5, timeComplexity: "O(n!)", href: "graph-algorithms/graph-coloring.html", tags: ["coloring","chromatic","scheduling"], section: "dsa" },
  { id: "minimum-cut", title: "Minimum Cut (Karger's)", category: "Graph Algorithms", difficulty: "Hard", description: "Minimum edges to disconnect graph using randomized contraction.", problemCount: 4, timeComplexity: "O(V\u00b2 log V)", href: "graph-algorithms/minimum-cut.html", tags: ["min-cut","randomized","contraction"], section: "dsa" },
  { id: "travelling-salesman", title: "Travelling Salesman Problem", category: "Graph Algorithms", difficulty: "Hard", description: "Shortest route visiting all cities exactly once (NP-hard).", problemCount: 5, timeComplexity: "O(n\u00b2\u00b72\u207f)", href: "graph-algorithms/travelling-salesman.html", tags: ["tsp","np-hard","dp-bitmask"], section: "dsa" },
  { id: "shortest-path-dag", title: "Shortest Path in DAG", category: "Graph Algorithms", difficulty: "Medium", description: "O(V+E) shortest paths using topological sort + relaxation.", problemCount: 5, timeComplexity: "O(V+E)", href: "graph-algorithms/shortest-path-dag.html", tags: ["dag","shortest-path","topological"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     TECHNIQUES  (29)
     ────────────────────────────────────────────────────────── */
  { id: "two-pointers", title: "Two Pointers", category: "Techniques", difficulty: "Easy", description: "Uses two indices moving toward each other or in same direction to solve array problems.", problemCount: 15, timeComplexity: "O(n)", href: "techniques/two-pointers.html", tags: ["two-pointer","array","sorted"], section: "dsa" },
  { id: "sliding-window", title: "Sliding Window", category: "Techniques", difficulty: "Medium", description: "Maintains a window over a sequence, expanding/shrinking to find optimal subarrays.", problemCount: 12, timeComplexity: "O(n)", href: "techniques/sliding-window.html", tags: ["window","subarray","optimization"], section: "dsa" },
  { id: "divide-and-conquer", title: "Divide and Conquer", category: "Techniques", difficulty: "Medium", description: "Breaks problem into subproblems, solves recursively, combines results.", problemCount: 10, timeComplexity: "varies", href: "techniques/divide-and-conquer.html", tags: ["divide","conquer","recursive"], section: "dsa" },
  { id: "dynamic-programming", title: "Dynamic Programming", category: "Techniques", difficulty: "Hard", description: "Solves overlapping subproblems by storing intermediate results.", problemCount: 20, timeComplexity: "varies", href: "techniques/dynamic-programming.html", tags: ["dp","memoization","tabulation"], section: "dsa" },
  { id: "greedy", title: "Greedy Algorithms", category: "Techniques", difficulty: "Medium", description: "Makes locally optimal choice at each step hoping for global optimum.", problemCount: 12, timeComplexity: "varies", href: "techniques/greedy.html", tags: ["greedy","optimal","local"], section: "dsa" },
  { id: "backtracking", title: "Backtracking", category: "Techniques", difficulty: "Medium", description: "Builds solution incrementally, abandoning paths that can't lead to valid solution.", problemCount: 12, timeComplexity: "O(k^n)", href: "techniques/backtracking.html", tags: ["backtrack","constraint","pruning"], section: "dsa" },
  { id: "bit-manipulation", title: "Bit Manipulation", category: "Techniques", difficulty: "Medium", description: "Uses bitwise operations for efficient computation and state encoding.", problemCount: 12, timeComplexity: "O(1) per op", href: "techniques/bit-manipulation.html", tags: ["bits","xor","and","or","shift"], section: "dsa" },
  { id: "recursion", title: "Recursion", category: "Techniques", difficulty: "Easy", description: "Function calling itself with a smaller subproblem until base case.", problemCount: 12, timeComplexity: "varies", href: "techniques/recursion.html", tags: ["recursive","base-case","call-stack"], section: "dsa" },
  { id: "reservoir-sampling", title: "Reservoir Sampling", category: "Techniques", difficulty: "Medium", description: "Selects k random items from a stream of unknown length.", problemCount: 4, timeComplexity: "O(n)", href: "techniques/reservoir-sampling.html", tags: ["sampling","random","stream"], section: "dsa" },
  { id: "fisher-yates-shuffle", title: "Fisher-Yates Shuffle", category: "Techniques", difficulty: "Easy", description: "Generates unbiased random permutation in O(n) time.", problemCount: 4, timeComplexity: "O(n)", href: "techniques/fisher-yates-shuffle.html", tags: ["shuffle","random","permutation"], section: "dsa" },
  { id: "boyer-moore-voting", title: "Boyer-Moore Voting", category: "Techniques", difficulty: "Easy", description: "Finds majority element in O(n) time and O(1) space.", problemCount: 5, timeComplexity: "O(n)", href: "techniques/boyer-moore-voting.html", tags: ["majority","voting","linear"], section: "dsa" },
  { id: "dutch-national-flag", title: "Dutch National Flag", category: "Techniques", difficulty: "Easy", description: "Three-way partitioning sorting 0s, 1s, 2s in a single pass.", problemCount: 5, timeComplexity: "O(n)", href: "techniques/dutch-national-flag.html", tags: ["partition","three-way","quicksort"], section: "dsa" },
  { id: "kadanes-algorithm", title: "Kadane's Algorithm", category: "Techniques", difficulty: "Easy", description: "Finds maximum sum contiguous subarray in O(n).", problemCount: 8, timeComplexity: "O(n)", href: "techniques/kadanes-algorithm.html", tags: ["max-subarray","dp","contiguous"], section: "dsa" },
  { id: "prefix-sum", title: "Prefix Sum", category: "Techniques", difficulty: "Easy", description: "Precomputes cumulative sums for O(1) range sum queries.", problemCount: 10, timeComplexity: "O(1) query", href: "techniques/prefix-sum.html", tags: ["prefix","cumulative","range-query"], section: "dsa" },
  { id: "difference-array", title: "Difference Array", category: "Techniques", difficulty: "Easy", description: "O(1) range update operations, reconstruct via prefix sum.", problemCount: 5, timeComplexity: "O(1) update", href: "techniques/difference-array.html", tags: ["difference","range-update","prefix"], section: "dsa" },
  { id: "interval-scheduling", title: "Interval Scheduling", category: "Techniques", difficulty: "Medium", description: "Selects maximum non-overlapping intervals by earliest end time.", problemCount: 8, timeComplexity: "O(n log n)", href: "techniques/interval-scheduling.html", tags: ["intervals","merge","greedy"], section: "dsa" },
  { id: "line-sweep", title: "Line Sweep Algorithm", category: "Techniques", difficulty: "Hard", description: "Sweeps a line across events to solve geometric/interval problems.", problemCount: 6, timeComplexity: "O(n log n)", href: "techniques/line-sweep.html", tags: ["sweep","geometric","events"], section: "dsa" },
  { id: "meet-in-the-middle", title: "Meet in the Middle", category: "Techniques", difficulty: "Hard", description: "Splits input in half, solves both, combines. Reduces O(2^n) to O(2^(n/2)).", problemCount: 5, timeComplexity: "O(2^(n/2))", href: "techniques/meet-in-the-middle.html", tags: ["subset-sum","exponential","split"], section: "dsa" },
  { id: "topk-elements", title: "Top-K Elements (Quickselect)", category: "Techniques", difficulty: "Medium", description: "Finds k-th smallest/largest element in O(n) average.", problemCount: 8, timeComplexity: "O(n) avg", href: "techniques/topk-elements.html", tags: ["quickselect","k-th","partition"], section: "dsa" },
  { id: "sliding-window-max", title: "Sliding Window Maximum", category: "Techniques", difficulty: "Medium", description: "O(1) amortized range max using monotonic deque.", problemCount: 6, timeComplexity: "O(n)", href: "techniques/sliding-window-max.html", tags: ["sliding-window","deque","maximum"], section: "dsa" },
  { id: "cycle-detection-arrays", title: "Cycle Detection in Arrays", category: "Techniques", difficulty: "Medium", description: "Find duplicates/missing by placing elements at correct index.", problemCount: 5, timeComplexity: "O(n)", href: "techniques/cycle-detection-arrays.html", tags: ["cycle","duplicate","in-place"], section: "dsa" },
  { id: "coordinate-compression", title: "Coordinate Compression", category: "Techniques", difficulty: "Medium", description: "Maps large values to smaller consecutive integers preserving order.", problemCount: 4, timeComplexity: "O(n log n)", href: "techniques/coordinate-compression.html", tags: ["compression","mapping","segment-tree"], section: "dsa" },
  { id: "binary-lifting", title: "Binary Lifting (LCA)", category: "Techniques", difficulty: "Hard", description: "Preprocesses tree for O(log n) Lowest Common Ancestor queries.", problemCount: 6, timeComplexity: "O(log n)", href: "techniques/binary-lifting.html", tags: ["lca","ancestor","tree"], section: "dsa" },
  { id: "heavy-light-decomposition", title: "Heavy-Light Decomposition", category: "Techniques", difficulty: "Hard", description: "Decomposes tree into chains for O(log\u00b2 n) path queries.", problemCount: 4, timeComplexity: "O(log\u00b2 n)", href: "techniques/heavy-light-decomposition.html", tags: ["hld","tree","path-query"], section: "dsa" },
  { id: "mos-algorithm", title: "Mo's Algorithm", category: "Techniques", difficulty: "Hard", description: "Offline range queries in O((N+Q)\u221aN) by reordering queries.", problemCount: 4, timeComplexity: "O((N+Q)\u221aN)", href: "techniques/mos-algorithm.html", tags: ["offline","range-query","sqrt"], section: "dsa" },
  { id: "sqrt-decomposition", title: "Square Root Decomposition", category: "Techniques", difficulty: "Medium", description: "Divides array into \u221an blocks for O(\u221an) range queries.", problemCount: 5, timeComplexity: "O(\u221an)", href: "techniques/sqrt-decomposition.html", tags: ["sqrt","block","range-query"], section: "dsa" },
  { id: "branch-and-bound", title: "Branch and Bound", category: "Techniques", difficulty: "Hard", description: "Systematic enumeration with pruning using bounds for optimization.", problemCount: 5, timeComplexity: "varies", href: "techniques/branch-and-bound.html", tags: ["optimization","pruning","enumeration"], section: "dsa" },
  { id: "randomized-algorithms", title: "Randomized Algorithms", category: "Techniques", difficulty: "Medium", description: "Algorithms using random choices for expected efficiency.", problemCount: 5, timeComplexity: "varies", href: "techniques/randomized-algorithms.html", tags: ["random","expected","probabilistic"], section: "dsa" },
  { id: "string-hashing", title: "String Hashing (Rolling Hash)", category: "Techniques", difficulty: "Medium", description: "Maps strings to integers for O(1) comparison using polynomial hash.", problemCount: 5, timeComplexity: "O(n)", href: "techniques/string-hashing.html", tags: ["hash","rolling","polynomial"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     STRING ALGORITHMS  (11)
     ────────────────────────────────────────────────────────── */
  { id: "kmp", title: "KMP Algorithm", category: "String Algorithms", difficulty: "Medium", description: "Pattern matching using failure function to avoid redundant comparisons.", problemCount: 8, timeComplexity: "O(n+m)", href: "string-algorithms/kmp.html", tags: ["pattern","matching","failure-function"], section: "dsa" },
  { id: "rabin-karp", title: "Rabin-Karp Algorithm", category: "String Algorithms", difficulty: "Medium", description: "Pattern matching using rolling hash for fast string comparison.", problemCount: 6, timeComplexity: "O(n+m) avg", href: "string-algorithms/rabin-karp.html", tags: ["pattern","rolling-hash","matching"], section: "dsa" },
  { id: "string-matching", title: "String Matching & Manipulation", category: "String Algorithms", difficulty: "Easy", description: "Basic string operations, substring search, and common patterns.", problemCount: 10, timeComplexity: "O(n\u00b7m)", href: "string-algorithms/string-matching.html", tags: ["string","substring","manipulation"], section: "dsa" },
  { id: "z-algorithm", title: "Z-Algorithm", category: "String Algorithms", difficulty: "Medium", description: "Computes Z-array for linear time pattern matching.", problemCount: 5, timeComplexity: "O(n)", href: "string-algorithms/z-algorithm.html", tags: ["z-array","pattern","prefix"], section: "dsa" },
  { id: "manachers", title: "Manacher's Algorithm", category: "String Algorithms", difficulty: "Hard", description: "Finds longest palindromic substring in O(n).", problemCount: 5, timeComplexity: "O(n)", href: "string-algorithms/manachers.html", tags: ["palindrome","manacher","longest"], section: "dsa" },
  { id: "suffix-array", title: "Suffix Array", category: "String Algorithms", difficulty: "Hard", description: "Sorted array of all suffixes for efficient substring operations.", problemCount: 5, timeComplexity: "O(n log n)", href: "string-algorithms/suffix-array.html", tags: ["suffix","substring","search"], section: "dsa" },
  { id: "suffix-tree", title: "Suffix Tree (Ukkonen's)", category: "String Algorithms", difficulty: "Hard", description: "Compressed trie of all suffixes built in O(n).", problemCount: 4, timeComplexity: "O(n)", href: "string-algorithms/suffix-tree.html", tags: ["suffix","trie","ukkonen"], section: "dsa" },
  { id: "aho-corasick", title: "Aho-Corasick Algorithm", category: "String Algorithms", difficulty: "Hard", description: "Multi-pattern string matching automaton.", problemCount: 4, timeComplexity: "O(n+m+z)", href: "string-algorithms/aho-corasick.html", tags: ["multi-pattern","automaton","trie"], section: "dsa" },
  { id: "boyer-moore-search", title: "Boyer-Moore String Search", category: "String Algorithms", difficulty: "Medium", description: "Efficient search using bad character and good suffix heuristics.", problemCount: 4, timeComplexity: "O(n/m) best", href: "string-algorithms/boyer-moore-search.html", tags: ["pattern","heuristic","skip"], section: "dsa" },
  { id: "longest-common-subsequence", title: "Longest Common Subsequence", category: "String Algorithms", difficulty: "Medium", description: "Finds longest subsequence common to two sequences via DP.", problemCount: 8, timeComplexity: "O(n\u00b7m)", href: "string-algorithms/longest-common-subsequence.html", tags: ["lcs","dp","subsequence"], section: "dsa" },
  { id: "edit-distance", title: "Edit Distance (Levenshtein)", category: "String Algorithms", difficulty: "Medium", description: "Min insertions/deletions/substitutions to transform one string to another.", problemCount: 8, timeComplexity: "O(n\u00b7m)", href: "string-algorithms/edit-distance.html", tags: ["levenshtein","dp","transform"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     MATH  (11)
     ────────────────────────────────────────────────────────── */
  { id: "math-number-theory", title: "Math & Number Theory", category: "Math", difficulty: "Medium", description: "Foundations of number theory: primes, divisibility, modular arithmetic.", problemCount: 10, timeComplexity: "\u2014", href: "math/math-number-theory.html", tags: ["math","primes","modular"], section: "dsa" },
  { id: "sieve-of-eratosthenes", title: "Sieve of Eratosthenes", category: "Math", difficulty: "Easy", description: "Finds all primes up to n by marking composites.", problemCount: 6, timeComplexity: "O(n log log n)", href: "math/sieve-of-eratosthenes.html", tags: ["prime","sieve","composite"], section: "dsa" },
  { id: "euclidean-gcd", title: "Euclidean Algorithm (GCD)", category: "Math", difficulty: "Easy", description: "Computes greatest common divisor in O(log min(a,b)).", problemCount: 5, timeComplexity: "O(log n)", href: "math/euclidean-gcd.html", tags: ["gcd","euclidean","divisor"], section: "dsa" },
  { id: "fast-exponentiation", title: "Fast Exponentiation", category: "Math", difficulty: "Easy", description: "Computes a^n in O(log n) by squaring.", problemCount: 5, timeComplexity: "O(log n)", href: "math/fast-exponentiation.html", tags: ["exponent","binary","power"], section: "dsa" },
  { id: "modular-arithmetic", title: "Modular Arithmetic", category: "Math", difficulty: "Medium", description: "Operations under modulo including modular inverse.", problemCount: 6, timeComplexity: "O(log n)", href: "math/modular-arithmetic.html", tags: ["modular","inverse","fermat"], section: "dsa" },
  { id: "matrix-exponentiation", title: "Matrix Exponentiation", category: "Math", difficulty: "Hard", description: "Matrix powers in O(n\u00b3 log k) for linear recurrences.", problemCount: 4, timeComplexity: "O(n\u00b3 log k)", href: "math/matrix-exponentiation.html", tags: ["matrix","recurrence","fibonacci"], section: "dsa" },
  { id: "catalan-numbers", title: "Catalan Numbers", category: "Math", difficulty: "Medium", description: "Sequence counting balanced parentheses, BST shapes, triangulations.", problemCount: 5, timeComplexity: "O(n)", href: "math/catalan-numbers.html", tags: ["catalan","combinatorics","counting"], section: "dsa" },
  { id: "combinatorics", title: "Combinatorics (nCr, nPr)", category: "Math", difficulty: "Medium", description: "Permutations, combinations, and Pascal's triangle.", problemCount: 6, timeComplexity: "O(n)", href: "math/combinatorics.html", tags: ["combinations","permutations","pascal"], section: "dsa" },
  { id: "prime-factorization", title: "Prime Factorization", category: "Math", difficulty: "Easy", description: "Decomposing numbers into prime factors in O(\u221an).", problemCount: 5, timeComplexity: "O(\u221an)", href: "math/prime-factorization.html", tags: ["prime","factors","divisors"], section: "dsa" },
  { id: "chinese-remainder-theorem", title: "Chinese Remainder Theorem", category: "Math", difficulty: "Hard", description: "Solves simultaneous modular congruences.", problemCount: 3, timeComplexity: "O(n log n)", href: "math/chinese-remainder-theorem.html", tags: ["crt","modular","congruence"], section: "dsa" },
  { id: "inclusion-exclusion", title: "Inclusion-Exclusion Principle", category: "Math", difficulty: "Medium", description: "Counting technique for union of sets using alternating sums.", problemCount: 4, timeComplexity: "O(2^n)", href: "math/inclusion-exclusion.html", tags: ["counting","sets","venn"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     COMPUTATIONAL GEOMETRY  (4)
     ────────────────────────────────────────────────────────── */
  { id: "convex-hull", title: "Convex Hull", category: "Computational Geometry", difficulty: "Hard", description: "Smallest convex polygon enclosing all points (Graham Scan).", problemCount: 5, timeComplexity: "O(n log n)", href: "computational-geometry/convex-hull.html", tags: ["convex","hull","graham"], section: "dsa" },
  { id: "line-intersection", title: "Line Segment Intersection", category: "Computational Geometry", difficulty: "Medium", description: "Determines if/where two segments intersect using cross products.", problemCount: 4, timeComplexity: "O(1)", href: "computational-geometry/line-intersection.html", tags: ["intersection","cross-product","geometry"], section: "dsa" },
  { id: "closest-pair", title: "Closest Pair of Points", category: "Computational Geometry", difficulty: "Hard", description: "Finds two closest points in O(n log n) via divide and conquer.", problemCount: 4, timeComplexity: "O(n log n)", href: "computational-geometry/closest-pair.html", tags: ["closest","divide-conquer","distance"], section: "dsa" },
  { id: "point-in-polygon", title: "Point in Polygon", category: "Computational Geometry", difficulty: "Medium", description: "Determines if a point lies inside a polygon via ray casting.", problemCount: 3, timeComplexity: "O(n)", href: "computational-geometry/point-in-polygon.html", tags: ["ray-casting","polygon","containment"], section: "dsa" },

  /* ──────────────────────────────────────────────────────────
     GAME THEORY  (3)
     ────────────────────────────────────────────────────────── */
  { id: "minimax", title: "Minimax Algorithm", category: "Game Theory", difficulty: "Medium", description: "Optimal decision-making for two-player zero-sum games.", problemCount: 5, timeComplexity: "O(b^d)", href: "game-theory/minimax.html", tags: ["game","minimax","zero-sum"], section: "dsa" },
  { id: "alpha-beta-pruning", title: "Alpha-Beta Pruning", category: "Game Theory", difficulty: "Hard", description: "Minimax optimization pruning branches that can't affect the decision.", problemCount: 4, timeComplexity: "O(b^(d/2))", href: "game-theory/alpha-beta-pruning.html", tags: ["pruning","minimax","optimization"], section: "dsa" },
  { id: "nim-game", title: "Nim Game & Sprague-Grundy", category: "Game Theory", difficulty: "Medium", description: "Combinatorial game theory using Grundy numbers.", problemCount: 4, timeComplexity: "O(n)", href: "game-theory/nim-game.html", tags: ["nim","grundy","xor","game"], section: "dsa" },

  /* ══════════════════════════════════════════════════════════
     ML / AI  TOPICS
     ══════════════════════════════════════════════════════════ */

  /* ──────────────────────────────────────────────────────────
     SUPERVISED LEARNING  (19)
     ────────────────────────────────────────────────────────── */
  { id: "linear-regression", title: "Linear Regression", category: "Supervised Learning", difficulty: "Easy", description: "Fits a straight line by minimizing sum of squared residuals.", problemCount: 8, timeComplexity: "O(n)", href: "ml-supervised/linear-regression.html", tags: ["regression","line","least-squares"], section: "ml" },
  { id: "polynomial-regression", title: "Polynomial Regression", category: "Supervised Learning", difficulty: "Easy", description: "Fits a polynomial curve to capture nonlinear relationships.", problemCount: 5, timeComplexity: "O(n)", href: "ml-supervised/polynomial-regression.html", tags: ["regression","polynomial","nonlinear"], section: "ml" },
  { id: "ridge-regression", title: "Ridge Regression (L2)", category: "Supervised Learning", difficulty: "Medium", description: "Linear regression with L2 regularization to reduce overfitting.", problemCount: 4, timeComplexity: "O(n)", href: "ml-supervised/ridge-regression.html", tags: ["regression","regularization","l2"], section: "ml" },
  { id: "lasso-regression", title: "Lasso Regression (L1)", category: "Supervised Learning", difficulty: "Medium", description: "Linear regression with L1 regularization for feature selection.", problemCount: 4, timeComplexity: "O(n)", href: "ml-supervised/lasso-regression.html", tags: ["regression","regularization","l1","feature-selection"], section: "ml" },
  { id: "elastic-net", title: "Elastic Net", category: "Supervised Learning", difficulty: "Medium", description: "Combines L1 and L2 regularization.", problemCount: 3, timeComplexity: "O(n)", href: "ml-supervised/elastic-net.html", tags: ["regression","regularization","combined"], section: "ml" },
  { id: "bayesian-linear-regression", title: "Bayesian Linear Regression", category: "Supervised Learning", difficulty: "Hard", description: "Treats coefficients as probability distributions for uncertainty estimates.", problemCount: 3, timeComplexity: "O(n\u00b3)", href: "ml-supervised/bayesian-linear-regression.html", tags: ["bayesian","uncertainty","posterior"], section: "ml" },
  { id: "quantile-regression", title: "Quantile Regression", category: "Supervised Learning", difficulty: "Medium", description: "Predicts specific quantiles of the response variable.", problemCount: 3, timeComplexity: "O(n)", href: "ml-supervised/quantile-regression.html", tags: ["quantile","median","distribution"], section: "ml" },
  { id: "svr", title: "Support Vector Regression", category: "Supervised Learning", difficulty: "Medium", description: "Applies SVM principles to regression with epsilon-insensitive tube.", problemCount: 4, timeComplexity: "O(n\u00b2)", href: "ml-supervised/svr.html", tags: ["svm","regression","epsilon"], section: "ml" },
  { id: "logistic-regression", title: "Logistic Regression", category: "Supervised Learning", difficulty: "Easy", description: "Sigmoid function for binary classification with linear decision boundary.", problemCount: 10, timeComplexity: "O(n)", href: "ml-supervised/logistic-regression.html", tags: ["classification","sigmoid","binary"], section: "ml" },
  { id: "decision-tree", title: "Decision Tree", category: "Supervised Learning", difficulty: "Easy", description: "Recursive feature splits forming a tree of if-then rules.", problemCount: 10, timeComplexity: "O(n log n)", href: "ml-supervised/decision-tree.html", tags: ["tree","splits","classification"], section: "ml" },
  { id: "random-forest", title: "Random Forest", category: "Supervised Learning", difficulty: "Medium", description: "Ensemble of decision trees on random subsets.", problemCount: 8, timeComplexity: "O(n log n\u00b7k)", href: "ml-supervised/random-forest.html", tags: ["ensemble","bagging","trees"], section: "ml" },
  { id: "svm", title: "Support Vector Machine", category: "Supervised Learning", difficulty: "Medium", description: "Optimal hyperplane maximizing margin between classes.", problemCount: 8, timeComplexity: "O(n\u00b2)", href: "ml-supervised/svm.html", tags: ["svm","margin","kernel"], section: "ml" },
  { id: "knn", title: "K-Nearest Neighbors", category: "Supervised Learning", difficulty: "Easy", description: "Classifies by majority vote of k closest neighbors.", problemCount: 8, timeComplexity: "O(n)", href: "ml-supervised/knn.html", tags: ["knn","distance","neighbors"], section: "ml" },
  { id: "naive-bayes", title: "Naive Bayes", category: "Supervised Learning", difficulty: "Easy", description: "Bayes' theorem with feature independence assumption.", problemCount: 6, timeComplexity: "O(n\u00b7d)", href: "ml-supervised/naive-bayes.html", tags: ["bayes","probabilistic","text"], section: "ml" },
  { id: "gradient-boosted-trees", title: "Gradient Boosted Trees", category: "Supervised Learning", difficulty: "Hard", description: "Sequential trees correcting previous errors via gradient descent.", problemCount: 6, timeComplexity: "O(n log n\u00b7k)", href: "ml-supervised/gradient-boosted-trees.html", tags: ["boosting","gradient","sequential"], section: "ml" },
  { id: "perceptron", title: "Perceptron", category: "Supervised Learning", difficulty: "Easy", description: "Simplest neural network \u2014 single-layer linear classifier.", problemCount: 5, timeComplexity: "O(n)", href: "ml-supervised/perceptron.html", tags: ["neural","linear","binary"], section: "ml" },
  { id: "lda-classifier", title: "Linear Discriminant Analysis", category: "Supervised Learning", difficulty: "Medium", description: "Projects data to maximize class separability.", problemCount: 4, timeComplexity: "O(n\u00b7d\u00b2)", href: "ml-supervised/lda-classifier.html", tags: ["lda","projection","separability"], section: "ml" },
  { id: "qda", title: "Quadratic Discriminant Analysis", category: "Supervised Learning", difficulty: "Medium", description: "Like LDA but with per-class covariance for curved boundaries.", problemCount: 3, timeComplexity: "O(n\u00b7d\u00b2)", href: "ml-supervised/qda.html", tags: ["qda","quadratic","covariance"], section: "ml" },
  { id: "softmax-regression", title: "Softmax Regression", category: "Supervised Learning", difficulty: "Medium", description: "Multiclass logistic regression using softmax function.", problemCount: 5, timeComplexity: "O(n\u00b7k)", href: "ml-supervised/softmax-regression.html", tags: ["softmax","multiclass","probability"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     UNSUPERVISED LEARNING  (16)
     ────────────────────────────────────────────────────────── */
  { id: "k-means", title: "K-Means Clustering", category: "Unsupervised Learning", difficulty: "Easy", description: "Iteratively assigns points to nearest centroid and recomputes.", problemCount: 8, timeComplexity: "O(n\u00b7k\u00b7i)", href: "ml-unsupervised/k-means.html", tags: ["clustering","centroid","iterative"], section: "ml" },
  { id: "dbscan", title: "DBSCAN", category: "Unsupervised Learning", difficulty: "Medium", description: "Density-based clustering finding arbitrary-shaped clusters.", problemCount: 6, timeComplexity: "O(n log n)", href: "ml-unsupervised/dbscan.html", tags: ["clustering","density","noise"], section: "ml" },
  { id: "hierarchical-clustering", title: "Hierarchical Clustering", category: "Unsupervised Learning", difficulty: "Medium", description: "Builds dendrogram by merging closest clusters iteratively.", problemCount: 5, timeComplexity: "O(n\u00b3)", href: "ml-unsupervised/hierarchical-clustering.html", tags: ["clustering","dendrogram","agglomerative"], section: "ml" },
  { id: "gaussian-mixture-models", title: "Gaussian Mixture Models", category: "Unsupervised Learning", difficulty: "Hard", description: "Models data as mixture of Gaussians with soft assignment.", problemCount: 5, timeComplexity: "O(n\u00b7k\u00b7d\u00b2)", href: "ml-unsupervised/gaussian-mixture-models.html", tags: ["gmm","gaussian","em"], section: "ml" },
  { id: "mean-shift", title: "Mean Shift", category: "Unsupervised Learning", difficulty: "Medium", description: "Points drift toward density peaks via kernel window.", problemCount: 4, timeComplexity: "O(n\u00b2)", href: "ml-unsupervised/mean-shift.html", tags: ["clustering","density","kernel"], section: "ml" },
  { id: "spectral-clustering", title: "Spectral Clustering", category: "Unsupervised Learning", difficulty: "Hard", description: "Uses graph Laplacian eigenvalues for complex cluster shapes.", problemCount: 4, timeComplexity: "O(n\u00b3)", href: "ml-unsupervised/spectral-clustering.html", tags: ["clustering","eigenvalue","graph"], section: "ml" },
  { id: "optics", title: "OPTICS", category: "Unsupervised Learning", difficulty: "Medium", description: "DBSCAN extension for varying density clusters.", problemCount: 3, timeComplexity: "O(n log n)", href: "ml-unsupervised/optics.html", tags: ["clustering","density","ordering"], section: "ml" },
  { id: "k-medoids", title: "K-Medoids (PAM)", category: "Unsupervised Learning", difficulty: "Medium", description: "Like K-Means but uses actual data points as centers.", problemCount: 4, timeComplexity: "O(n\u00b2\u00b7k)", href: "ml-unsupervised/k-medoids.html", tags: ["clustering","medoid","robust"], section: "ml" },
  { id: "pca", title: "Principal Component Analysis", category: "Unsupervised Learning", difficulty: "Medium", description: "Finds axes of maximum variance for dimensionality reduction.", problemCount: 8, timeComplexity: "O(d\u00b2\u00b7n)", href: "ml-unsupervised/pca.html", tags: ["pca","variance","eigenvalue"], section: "ml" },
  { id: "t-sne", title: "t-SNE", category: "Unsupervised Learning", difficulty: "Hard", description: "Nonlinear mapping preserving local structure for 2D visualization.", problemCount: 5, timeComplexity: "O(n\u00b2)", href: "ml-unsupervised/t-sne.html", tags: ["visualization","nonlinear","embedding"], section: "ml" },
  { id: "umap", title: "UMAP", category: "Unsupervised Learning", difficulty: "Hard", description: "Fast dimensionality reduction preserving local and global structure.", problemCount: 4, timeComplexity: "O(n^1.14)", href: "ml-unsupervised/umap.html", tags: ["embedding","topology","manifold"], section: "ml" },
  { id: "lda-topic", title: "Latent Dirichlet Allocation", category: "Unsupervised Learning", difficulty: "Hard", description: "Discovers hidden topics in document collections.", problemCount: 4, timeComplexity: "O(n\u00b7k\u00b7V)", href: "ml-unsupervised/lda-topic.html", tags: ["topics","documents","generative"], section: "ml" },
  { id: "svd", title: "Singular Value Decomposition", category: "Unsupervised Learning", difficulty: "Medium", description: "Decomposes matrix into U\u00b7\u03a3\u00b7V for dimensionality reduction.", problemCount: 5, timeComplexity: "O(min(mn\u00b2,m\u00b2n))", href: "ml-unsupervised/svd.html", tags: ["svd","matrix","decomposition"], section: "ml" },
  { id: "autoencoder", title: "Autoencoder", category: "Unsupervised Learning", difficulty: "Medium", description: "Neural net compressing data through a bottleneck and reconstructing.", problemCount: 5, timeComplexity: "O(n\u00b7d)", href: "ml-unsupervised/autoencoder.html", tags: ["autoencoder","bottleneck","reconstruction"], section: "ml" },
  { id: "isomap", title: "Isomap", category: "Unsupervised Learning", difficulty: "Hard", description: "Uses geodesic distances for nonlinear dimensionality reduction.", problemCount: 3, timeComplexity: "O(n\u00b2\u00b7log n)", href: "ml-unsupervised/isomap.html", tags: ["manifold","geodesic","embedding"], section: "ml" },
  { id: "kernel-pca", title: "Kernel PCA", category: "Unsupervised Learning", difficulty: "Hard", description: "Applies kernel trick to PCA for nonlinear reduction.", problemCount: 3, timeComplexity: "O(n\u00b3)", href: "ml-unsupervised/kernel-pca.html", tags: ["kernel","pca","nonlinear"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     ENSEMBLE METHODS  (8)
     ────────────────────────────────────────────────────────── */
  { id: "bagging", title: "Bagging", category: "Ensemble Methods", difficulty: "Medium", description: "Bootstrap samples + aggregation to reduce variance.", problemCount: 4, timeComplexity: "O(n\u00b7k)", href: "ml-ensemble/bagging.html", tags: ["bootstrap","aggregation","variance"], section: "ml" },
  { id: "boosting", title: "Boosting (Concept)", category: "Ensemble Methods", difficulty: "Medium", description: "Sequential weak learners focusing on previous errors.", problemCount: 5, timeComplexity: "O(n\u00b7k)", href: "ml-ensemble/boosting.html", tags: ["sequential","weak-learner","bias"], section: "ml" },
  { id: "adaboost", title: "AdaBoost", category: "Ensemble Methods", difficulty: "Medium", description: "Adjusts sample weights so misclassified examples get more attention.", problemCount: 5, timeComplexity: "O(n\u00b7k)", href: "ml-ensemble/adaboost.html", tags: ["adaptive","weights","boosting"], section: "ml" },
  { id: "xgboost", title: "XGBoost", category: "Ensemble Methods", difficulty: "Hard", description: "Optimized gradient boosting with regularization and parallelism.", problemCount: 5, timeComplexity: "O(n log n\u00b7k)", href: "ml-ensemble/xgboost.html", tags: ["xgboost","gradient","regularization"], section: "ml" },
  { id: "lightgbm", title: "LightGBM", category: "Ensemble Methods", difficulty: "Hard", description: "Leaf-wise gradient boosting with histogram binning.", problemCount: 4, timeComplexity: "O(n\u00b7k)", href: "ml-ensemble/lightgbm.html", tags: ["lightgbm","leaf-wise","histogram"], section: "ml" },
  { id: "catboost", title: "CatBoost", category: "Ensemble Methods", difficulty: "Hard", description: "Gradient boosting with native categorical feature handling.", problemCount: 4, timeComplexity: "O(n\u00b7k)", href: "ml-ensemble/catboost.html", tags: ["catboost","categorical","ordered"], section: "ml" },
  { id: "stacking", title: "Stacking", category: "Ensemble Methods", difficulty: "Hard", description: "Meta-model combining predictions from diverse base models.", problemCount: 3, timeComplexity: "O(n\u00b7k)", href: "ml-ensemble/stacking.html", tags: ["stacking","meta-learner","blending"], section: "ml" },
  { id: "voting-ensemble", title: "Voting Ensemble", category: "Ensemble Methods", difficulty: "Easy", description: "Majority vote or averaging from multiple models.", problemCount: 3, timeComplexity: "O(n\u00b7k)", href: "ml-ensemble/voting-ensemble.html", tags: ["voting","majority","averaging"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     DEEP LEARNING  (13)
     ────────────────────────────────────────────────────────── */
  { id: "mlp", title: "Multilayer Perceptron", category: "Deep Learning", difficulty: "Medium", description: "Feedforward neural network with hidden layers and nonlinear activations.", problemCount: 6, timeComplexity: "O(n\u00b7d\u00b2)", href: "ml-deep-learning/mlp.html", tags: ["neural-network","feedforward","activation"], section: "ml" },
  { id: "cnn", title: "Convolutional Neural Network", category: "Deep Learning", difficulty: "Hard", description: "Learnable convolutional filters extracting spatial feature hierarchies.", problemCount: 8, timeComplexity: "O(n\u00b7k\u00b2\u00b7c)", href: "ml-deep-learning/cnn.html", tags: ["convolution","filters","image"], section: "ml" },
  { id: "rnn", title: "Recurrent Neural Network", category: "Deep Learning", difficulty: "Hard", description: "Processes sequences with hidden state carrying information across time steps.", problemCount: 6, timeComplexity: "O(T\u00b7d\u00b2)", href: "ml-deep-learning/rnn.html", tags: ["recurrent","sequence","hidden-state"], section: "ml" },
  { id: "lstm", title: "Long Short-Term Memory", category: "Deep Learning", difficulty: "Hard", description: "RNN with gates solving vanishing gradient for long sequences.", problemCount: 6, timeComplexity: "O(T\u00b7d\u00b2)", href: "ml-deep-learning/lstm.html", tags: ["lstm","gates","long-range"], section: "ml" },
  { id: "gru", title: "Gated Recurrent Unit", category: "Deep Learning", difficulty: "Hard", description: "Simplified LSTM with reset and update gates.", problemCount: 4, timeComplexity: "O(T\u00b7d\u00b2)", href: "ml-deep-learning/gru.html", tags: ["gru","gates","simplified"], section: "ml" },
  { id: "transformer", title: "Transformer", category: "Deep Learning", difficulty: "Hard", description: "Self-attention replacing recurrence for parallel sequence processing.", problemCount: 8, timeComplexity: "O(n\u00b2\u00b7d)", href: "ml-deep-learning/transformer.html", tags: ["attention","parallel","llm"], section: "ml" },
  { id: "gan", title: "Generative Adversarial Network", category: "Deep Learning", difficulty: "Hard", description: "Generator vs discriminator competing to create realistic data.", problemCount: 5, timeComplexity: "O(n\u00b7d)", href: "ml-deep-learning/gan.html", tags: ["generative","adversarial","generator"], section: "ml" },
  { id: "vae", title: "Variational Autoencoder", category: "Deep Learning", difficulty: "Hard", description: "Learns smooth latent space via probabilistic encoding.", problemCount: 4, timeComplexity: "O(n\u00b7d)", href: "ml-deep-learning/vae.html", tags: ["generative","latent","variational"], section: "ml" },
  { id: "resnet-skip-connections", title: "Residual Connections (ResNet)", category: "Deep Learning", difficulty: "Hard", description: "Skip connections enabling training of very deep networks.", problemCount: 5, timeComplexity: "O(n\u00b7d\u00b2\u00b7L)", href: "ml-deep-learning/resnet-skip-connections.html", tags: ["resnet","skip","deep"], section: "ml" },
  { id: "batch-normalization", title: "Batch Normalization", category: "Deep Learning", difficulty: "Medium", description: "Normalizes layer inputs for stable, faster training.", problemCount: 4, timeComplexity: "O(n\u00b7d)", href: "ml-deep-learning/batch-normalization.html", tags: ["normalization","training","stability"], section: "ml" },
  { id: "dropout", title: "Dropout Regularization", category: "Deep Learning", difficulty: "Easy", description: "Randomly deactivates neurons during training to prevent overfitting.", problemCount: 4, timeComplexity: "O(n\u00b7d)", href: "ml-deep-learning/dropout.html", tags: ["dropout","regularization","ensemble"], section: "ml" },
  { id: "attention-mechanism", title: "Attention Mechanism", category: "Deep Learning", difficulty: "Hard", description: "Dynamic focus on relevant input parts for each output element.", problemCount: 6, timeComplexity: "O(n\u00b2\u00b7d)", href: "ml-deep-learning/attention-mechanism.html", tags: ["attention","focus","weights"], section: "ml" },
  { id: "diffusion-models", title: "Diffusion Models", category: "Deep Learning", difficulty: "Hard", description: "Generates data by iteratively denoising from pure noise.", problemCount: 4, timeComplexity: "O(T\u00b7n\u00b7d)", href: "ml-deep-learning/diffusion-models.html", tags: ["diffusion","denoising","generative"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     REINFORCEMENT LEARNING  (8)
     ────────────────────────────────────────────────────────── */
  { id: "q-learning", title: "Q-Learning", category: "Reinforcement Learning", difficulty: "Medium", description: "Model-free RL learning action-value function via Bellman equation.", problemCount: 6, timeComplexity: "O(S\u00b7A)", href: "ml-reinforcement/q-learning.html", tags: ["q-table","bellman","model-free"], section: "ml" },
  { id: "sarsa", title: "SARSA", category: "Reinforcement Learning", difficulty: "Medium", description: "On-policy RL updating Q-values using action actually taken.", problemCount: 4, timeComplexity: "O(S\u00b7A)", href: "ml-reinforcement/sarsa.html", tags: ["on-policy","conservative","q-value"], section: "ml" },
  { id: "deep-q-network", title: "Deep Q-Network (DQN)", category: "Reinforcement Learning", difficulty: "Hard", description: "Q-Learning with neural networks for high-dimensional states.", problemCount: 4, timeComplexity: "O(n\u00b7d\u00b2)", href: "ml-reinforcement/deep-q-network.html", tags: ["dqn","replay","target-network"], section: "ml" },
  { id: "policy-gradient", title: "Policy Gradient (REINFORCE)", category: "Reinforcement Learning", difficulty: "Hard", description: "Directly optimizes policy by gradient of expected reward.", problemCount: 4, timeComplexity: "O(T\u00b7d)", href: "ml-reinforcement/policy-gradient.html", tags: ["policy","gradient","reinforce"], section: "ml" },
  { id: "actor-critic", title: "Actor-Critic", category: "Reinforcement Learning", difficulty: "Hard", description: "Combines policy gradient (actor) with value estimation (critic).", problemCount: 4, timeComplexity: "O(T\u00b7d\u00b2)", href: "ml-reinforcement/actor-critic.html", tags: ["actor","critic","advantage"], section: "ml" },
  { id: "monte-carlo-rl", title: "Monte Carlo Methods (RL)", category: "Reinforcement Learning", difficulty: "Medium", description: "Estimates values by averaging returns from complete episodes.", problemCount: 4, timeComplexity: "O(T)", href: "ml-reinforcement/monte-carlo-rl.html", tags: ["monte-carlo","episodes","returns"], section: "ml" },
  { id: "multi-armed-bandit", title: "Multi-Armed Bandit", category: "Reinforcement Learning", difficulty: "Easy", description: "Balances exploration and exploitation for unknown reward distributions.", problemCount: 5, timeComplexity: "O(k)", href: "ml-reinforcement/multi-armed-bandit.html", tags: ["bandit","exploration","exploitation"], section: "ml" },
  { id: "ppo", title: "Proximal Policy Optimization", category: "Reinforcement Learning", difficulty: "Hard", description: "Clips policy updates for stable improvement. Used in RLHF.", problemCount: 4, timeComplexity: "O(T\u00b7d\u00b2)", href: "ml-reinforcement/ppo.html", tags: ["ppo","clipping","rlhf"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     NLP ALGORITHMS  (7)
     ────────────────────────────────────────────────────────── */
  { id: "tf-idf", title: "TF-IDF", category: "NLP Algorithms", difficulty: "Easy", description: "Scores word importance by term frequency \u00d7 inverse document frequency.", problemCount: 4, timeComplexity: "O(n\u00b7V)", href: "ml-nlp/tf-idf.html", tags: ["tfidf","text","importance"], section: "ml" },
  { id: "word2vec", title: "Word2Vec", category: "NLP Algorithms", difficulty: "Medium", description: "Dense word vectors from context windows capturing semantic relationships.", problemCount: 5, timeComplexity: "O(n\u00b7d)", href: "ml-nlp/word2vec.html", tags: ["embedding","context","semantic"], section: "ml" },
  { id: "glove", title: "GloVe", category: "NLP Algorithms", difficulty: "Medium", description: "Word embeddings from global co-occurrence matrix factorization.", problemCount: 4, timeComplexity: "O(V\u00b2)", href: "ml-nlp/glove.html", tags: ["embedding","co-occurrence","matrix"], section: "ml" },
  { id: "beam-search", title: "Beam Search", category: "NLP Algorithms", difficulty: "Medium", description: "Explores top-k candidate sequences during decoding.", problemCount: 5, timeComplexity: "O(b\u00b7V\u00b7T)", href: "ml-nlp/beam-search.html", tags: ["decoding","candidates","pruning"], section: "ml" },
  { id: "bpe-tokenization", title: "Byte Pair Encoding (BPE)", category: "NLP Algorithms", difficulty: "Medium", description: "Iteratively merges frequent character pairs for subword vocabulary.", problemCount: 4, timeComplexity: "O(n\u00b7V)", href: "ml-nlp/bpe-tokenization.html", tags: ["tokenization","subword","merge"], section: "ml" },
  { id: "seq2seq", title: "Sequence-to-Sequence", category: "NLP Algorithms", difficulty: "Hard", description: "Encoder-decoder architecture for sequence transformation.", problemCount: 5, timeComplexity: "O(T\u00b7d\u00b2)", href: "ml-nlp/seq2seq.html", tags: ["encoder","decoder","translation"], section: "ml" },
  { id: "self-attention", title: "Self-Attention", category: "NLP Algorithms", difficulty: "Hard", description: "Each token attends to every other token in the sequence.", problemCount: 5, timeComplexity: "O(n\u00b2\u00b7d)", href: "ml-nlp/self-attention.html", tags: ["attention","scaled-dot","transformer"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     OPTIMIZATION  (9)
     ────────────────────────────────────────────────────────── */
  { id: "gradient-descent", title: "Gradient Descent", category: "Optimization", difficulty: "Easy", description: "Moves parameters toward steepest loss reduction.", problemCount: 6, timeComplexity: "O(n\u00b7d)", href: "ml-optimization/gradient-descent.html", tags: ["gradient","loss","convergence"], section: "ml" },
  { id: "sgd", title: "Stochastic Gradient Descent", category: "Optimization", difficulty: "Easy", description: "Updates per random sample, noisy path that escapes local minima.", problemCount: 5, timeComplexity: "O(d)", href: "ml-optimization/sgd.html", tags: ["stochastic","mini-batch","noise"], section: "ml" },
  { id: "adam", title: "Adam Optimizer", category: "Optimization", difficulty: "Medium", description: "Adaptive learning rates with momentum and RMSProp.", problemCount: 5, timeComplexity: "O(d)", href: "ml-optimization/adam.html", tags: ["adam","adaptive","momentum"], section: "ml" },
  { id: "rmsprop", title: "RMSProp", category: "Optimization", difficulty: "Medium", description: "Adapts learning rate by dividing by running average of gradient magnitudes.", problemCount: 3, timeComplexity: "O(d)", href: "ml-optimization/rmsprop.html", tags: ["rmsprop","adaptive","running-average"], section: "ml" },
  { id: "momentum", title: "Momentum", category: "Optimization", difficulty: "Easy", description: "Accumulates velocity from past gradients to push through flat regions.", problemCount: 4, timeComplexity: "O(d)", href: "ml-optimization/momentum.html", tags: ["momentum","velocity","acceleration"], section: "ml" },
  { id: "learning-rate-scheduling", title: "Learning Rate Scheduling", category: "Optimization", difficulty: "Easy", description: "Reduces learning rate over time for fine convergence.", problemCount: 4, timeComplexity: "O(1)", href: "ml-optimization/learning-rate-scheduling.html", tags: ["schedule","decay","cosine","warmup"], section: "ml" },
  { id: "simulated-annealing", title: "Simulated Annealing", category: "Optimization", difficulty: "Medium", description: "Global optimization accepting worse solutions with decreasing probability.", problemCount: 4, timeComplexity: "O(n\u00b7T)", href: "ml-optimization/simulated-annealing.html", tags: ["annealing","temperature","global"], section: "ml" },
  { id: "genetic-algorithm", title: "Genetic Algorithm", category: "Optimization", difficulty: "Medium", description: "Evolves solutions via selection, crossover, and mutation.", problemCount: 5, timeComplexity: "O(n\u00b7g)", href: "ml-optimization/genetic-algorithm.html", tags: ["evolution","crossover","mutation"], section: "ml" },
  { id: "backpropagation", title: "Backpropagation", category: "Optimization", difficulty: "Medium", description: "Computes gradients backward through network via chain rule.", problemCount: 6, timeComplexity: "O(n\u00b7d\u00b2)", href: "ml-optimization/backpropagation.html", tags: ["gradient","chain-rule","backward"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     COMPUTER VISION  (8)
     ────────────────────────────────────────────────────────── */
  { id: "edge-detection", title: "Edge Detection (Sobel/Canny)", category: "Computer Vision", difficulty: "Easy", description: "Detects boundaries using gradient operators.", problemCount: 4, timeComplexity: "O(n\u00b7m)", href: "ml-computer-vision/edge-detection.html", tags: ["edge","gradient","canny","sobel"], section: "ml" },
  { id: "hog", title: "Histogram of Oriented Gradients", category: "Computer Vision", difficulty: "Medium", description: "Gradient direction histograms in local patches for object detection.", problemCount: 3, timeComplexity: "O(n\u00b7m)", href: "ml-computer-vision/hog.html", tags: ["hog","gradient","pedestrian"], section: "ml" },
  { id: "sift", title: "SIFT", category: "Computer Vision", difficulty: "Hard", description: "Scale and rotation invariant local feature detection and description.", problemCount: 3, timeComplexity: "O(n\u00b7log n)", href: "ml-computer-vision/sift.html", tags: ["sift","keypoint","scale-invariant"], section: "ml" },
  { id: "image-convolution", title: "Image Convolution", category: "Computer Vision", difficulty: "Easy", description: "Kernel sliding over image computing weighted sums.", problemCount: 5, timeComplexity: "O(n\u00b7m\u00b7k\u00b2)", href: "ml-computer-vision/image-convolution.html", tags: ["convolution","kernel","filter"], section: "ml" },
  { id: "non-max-suppression", title: "Non-Maximum Suppression", category: "Computer Vision", difficulty: "Medium", description: "Eliminates redundant overlapping bounding boxes.", problemCount: 4, timeComplexity: "O(n log n)", href: "ml-computer-vision/non-max-suppression.html", tags: ["nms","bounding-box","detection"], section: "ml" },
  { id: "iou", title: "Intersection over Union (IoU)", category: "Computer Vision", difficulty: "Easy", description: "Measures overlap between predicted and ground-truth boxes.", problemCount: 4, timeComplexity: "O(1)", href: "ml-computer-vision/iou.html", tags: ["iou","overlap","evaluation"], section: "ml" },
  { id: "anchor-boxes", title: "Anchor Boxes", category: "Computer Vision", difficulty: "Medium", description: "Predefined reference boxes at various scales and ratios for detection.", problemCount: 3, timeComplexity: "O(n\u00b7k)", href: "ml-computer-vision/anchor-boxes.html", tags: ["anchor","yolo","faster-rcnn"], section: "ml" },
  { id: "image-augmentation", title: "Image Augmentation", category: "Computer Vision", difficulty: "Easy", description: "Random transformations to increase training data diversity.", problemCount: 4, timeComplexity: "O(n)", href: "ml-computer-vision/image-augmentation.html", tags: ["augmentation","transform","diversity"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     PROBABILISTIC  (6)
     ────────────────────────────────────────────────────────── */
  { id: "bayesian-networks", title: "Bayesian Networks", category: "Probabilistic", difficulty: "Hard", description: "DAGs representing probabilistic dependencies for causal reasoning.", problemCount: 3, timeComplexity: "O(2^k)", href: "ml-probabilistic/bayesian-networks.html", tags: ["bayesian","dag","inference"], section: "ml" },
  { id: "hidden-markov-models", title: "Hidden Markov Models", category: "Probabilistic", difficulty: "Hard", description: "Hidden states with transitions and observable emissions.", problemCount: 4, timeComplexity: "O(T\u00b7S\u00b2)", href: "ml-probabilistic/hidden-markov-models.html", tags: ["hmm","viterbi","emission"], section: "ml" },
  { id: "expectation-maximization", title: "Expectation-Maximization", category: "Probabilistic", difficulty: "Hard", description: "Alternating E-step and M-step for maximum likelihood with latent variables.", problemCount: 4, timeComplexity: "O(n\u00b7k\u00b7d)", href: "ml-probabilistic/expectation-maximization.html", tags: ["em","latent","likelihood"], section: "ml" },
  { id: "mcmc", title: "Markov Chain Monte Carlo", category: "Probabilistic", difficulty: "Hard", description: "Generates samples from complex distributions via Markov chains.", problemCount: 3, timeComplexity: "O(n\u00b7T)", href: "ml-probabilistic/mcmc.html", tags: ["mcmc","sampling","markov"], section: "ml" },
  { id: "bayes-theorem", title: "Bayes' Theorem", category: "Probabilistic", difficulty: "Easy", description: "Updates probability of hypothesis given new evidence.", problemCount: 5, timeComplexity: "O(1)", href: "ml-probabilistic/bayes-theorem.html", tags: ["bayes","prior","posterior","evidence"], section: "ml" },
  { id: "kalman-filter", title: "Kalman Filter", category: "Probabilistic", difficulty: "Hard", description: "Optimal state estimation from noisy observations.", problemCount: 3, timeComplexity: "O(d\u00b3)", href: "ml-probabilistic/kalman-filter.html", tags: ["kalman","prediction","measurement"], section: "ml" },

  /* ──────────────────────────────────────────────────────────
     RECOMMENDATION  (5)
     ────────────────────────────────────────────────────────── */
  { id: "collaborative-filtering", title: "Collaborative Filtering", category: "Recommendation", difficulty: "Medium", description: "Recommends based on similar users' preferences.", problemCount: 5, timeComplexity: "O(n\u00b7m)", href: "ml-recommendation/collaborative-filtering.html", tags: ["collaborative","user-based","similarity"], section: "ml" },
  { id: "content-based-filtering", title: "Content-Based Filtering", category: "Recommendation", difficulty: "Medium", description: "Recommends items similar to user's past preferences.", problemCount: 4, timeComplexity: "O(n\u00b7d)", href: "ml-recommendation/content-based-filtering.html", tags: ["content","features","similarity"], section: "ml" },
  { id: "matrix-factorization", title: "Matrix Factorization", category: "Recommendation", difficulty: "Hard", description: "Decomposes user-item matrix into latent factor matrices.", problemCount: 4, timeComplexity: "O(n\u00b7m\u00b7k)", href: "ml-recommendation/matrix-factorization.html", tags: ["factorization","latent","svd"], section: "ml" },
  { id: "apriori", title: "Apriori Algorithm", category: "Recommendation", difficulty: "Medium", description: "Discovers frequent itemsets by pruning infrequent candidates.", problemCount: 4, timeComplexity: "O(2^d)", href: "ml-recommendation/apriori.html", tags: ["association","itemset","support"], section: "ml" },
  { id: "fp-growth", title: "FP-Growth", category: "Recommendation", difficulty: "Medium", description: "Efficient frequent itemset mining via FP-tree without candidate generation.", problemCount: 4, timeComplexity: "O(n\u00b7m)", href: "ml-recommendation/fp-growth.html", tags: ["fp-tree","frequent","mining"], section: "ml" }
];
