/* eslint-disable */
// Deen track · 12 months × 30 days · English + Arabic parallel.
// Rotation: Quran(1) Tafsir(2) Hadith(3) Fiqh(4) Aqeedah(5) Seerah(6) → repeat
// Days 1-20: learn (cycles of 6 + extra topics)
// Days 21-30: cumulative revision

(function () {
  // Compact day-builder. ar = same shape as en.
  function D(num, phase, sub, en, ar) {
    var d = {
      num: num, phase: phase, sub: sub,
      topic: en.t, slot: en.s, objective: en.o, source: en.src,
      plan: en.p, deliverable: en.d, crossLink: en.cl, dua: en.dua
    };
    if (ar) {
      d.topicAr = ar.t; d.slotAr = ar.s; d.objectiveAr = ar.o; d.sourceAr = ar.src;
      d.planAr = ar.p; d.deliverableAr = ar.d; d.crossLinkAr = ar.cl; d.duaAr = ar.dua;
    }
    return d;
  }

  // Recurring slot strings
  var SLOTS = {
    quran:   'Quran slot · 6:30–7:00 AM + Esha review',
    quranAr: 'فَتْرَةُ القُرْآنِ · ٦:٣٠–٧:٠٠ صَبَاحًا + مُرَاجَعَةُ العِشَاء',
    morning: '4:30–5:00 AM Arabic/deep dive + Esha 8:45–9:30 PM',
    morningAr: '٤:٣٠–٥:٠٠ صَبَاحًا غَوْصٌ فِي العَرَبِيَّة + عِشَاء ٨:٤٥–٩:٣٠ مَسَاءً',
    madrasa: 'Online madrasa class 5:30–6:30 AM Sat/Sun',
    madrasaAr: 'دَرْسُ المَدْرَسَةِ ٥:٣٠–٦:٣٠ صَبَاحًا السَّبْت/الأَحَد',
    review:  'Weekly review slot 3:00–5:00 PM Sun',
    reviewAr: 'فَتْرَةُ المُرَاجَعَةِ الأُسْبُوعِيَّة ٣:٠٠–٥:٠٠ مَسَاءً الأَحَد'
  };

  var DEEN_MONTHS = [];

  // ═════════════════════════════════════════════════════════════
  // MONTH 1 — Foundations
  // ═════════════════════════════════════════════════════════════
  DEEN_MONTHS.push({
    num: '01',
    tabLabel: 'Foundations',
    tabLabelAr: 'الأُسُس',
    theme: 'Open the mushaf, the Sunnah, and the spine.',
    themeAr: 'افْتَحِ المُصْحَفَ وَالسُّنَّةَ وَالعَمُود.',
    thesis: 'Lay tracks across all six sub-disciplines so nothing surprises you in month two.',
    thesisAr: 'ضَعْ سِكَكًا فِي السِّتَّةِ كُلِّهَا حَتَّى لَا يُفَاجِئَكَ الشَّهْرُ الثَّانِي.',
    focus: {
      quran: 'Surah Al-Mulk · 30 ayaat memorised',
      quranAr: 'سُورَةُ المُلْكِ · ٣٠ آيَةً مَحْفُوظَة',
      tafsir: 'Tafsir As-Sa\'di on Al-Mulk',
      tafsirAr: 'تَفْسِيرُ السَّعْدِيِّ لِسُورَةِ المُلْك',
      hadith: 'Nawawi #1-5 (Niyyah, Pillars, Decree, Innovation, Halal)',
      hadithAr: 'النَّوَوِيَّة ١-٥ (النِّيَّة، الأَرْكَان، القَدَر، البِدْعَة، الحَلَال)',
      fiqh: 'Tahara · types of najasah, wudu conditions and fards',
      fiqhAr: 'الطَّهَارَةُ · أَنْوَاعُ النَّجَاسَةِ وَشُرُوطُ الوُضُوءِ وَفَرَائِضُهُ',
      aqeedah: 'The three categories of tawhid',
      aqeedahAr: 'أَقْسَامُ التَّوْحِيدِ الثَّلَاثَة',
      seerah: 'Pre-Islamic Arabia + birth + childhood of the Prophet ﷺ',
      seerahAr: 'جَزِيرَةُ العَرَبِ قَبْلَ الإِسْلَامِ + المَوْلِدُ + الطُّفُولَة'
    },
    days: [
      D(1, 'learn', 'quran',
        { t: 'Al-Mulk vv. 1–5 · memorise with tajweed', s: SLOTS.quran,
          o: 'Memorise the first five ayaat of Surah Al-Mulk with correct tajweed and recite them in Esha tonight.',
          src: 'Mushaf al-Madinah p. 562 · MaqraaTV qari of choice · Tajweed rules: madd, qalqalah.',
          p: ['Read verses 1–5 aloud three times from the mushaf, applying tajweed rules carefully.',
              'Listen to the same five verses twice from your chosen reciter (MaqraaTV).',
              'Recite from memory five times; mark any verse you stumble on for extra repetition.',
              'Recite verses 1–5 in Esha qiyam tonight to lock the memorisation in salah.'],
          d: 'Al-Mulk vv. 1–5 memorised and recited in Esha salah.',
          cl: 'Day 2 will tafsir these same five verses.',
          dua: 'O Allah, make the Quran the spring of my heart and the light of my chest.' },
        { t: 'المُلْك ١–٥ · حِفْظٌ بِتَجْوِيد', s: SLOTS.quranAr,
          o: 'اِحْفَظِ الآيَاتِ الخَمْسَ الأُولَى مِنْ سُورَةِ المُلْكِ بِتَجْوِيدٍ صَحِيحٍ، وَاتْلُهَا فِي صَلَاةِ العِشَاءِ اللَّيْلَة.',
          src: 'مُصْحَفُ المَدِينَةِ ص ٥٦٢ · قَارِئٌ مِنْ MaqraaTV · أَحْكَامُ المَدِّ وَالقَلْقَلَة.',
          p: ['اِقْرَأِ الآيَاتِ ١–٥ ثَلَاثَ مَرَّاتٍ بِصَوْتٍ مَسْمُوعٍ مِنَ المُصْحَفِ مَعَ تَطْبِيقِ التَّجْوِيدِ.',
              'اِسْتَمِعْ إِلَى الآيَاتِ مَرَّتَيْنِ مِنَ القَارِئِ المُخْتَار.',
              'كَرِّرِ الآيَاتِ مِنَ الحِفْظِ خَمْسَ مَرَّاتٍ، وَأَشِّرْ مَوَاطِنَ التَّعَثُّر.',
              'اِتْلُهَا فِي قِيَامِ العِشَاءِ اللَّيْلَة لِتَثْبِيتِ الحِفْظِ.'],
          d: 'حِفْظُ المُلْك ١–٥ وَتِلَاوَتُهَا فِي صَلَاةِ العِشَاء.',
          cl: 'اليَوْمُ ٢ يُفَسِّرُ هَذِهِ الآيَاتِ الخَمْس.',
          dua: 'اللَّهُمَّ اجْعَلِ القُرْآنَ رَبِيعَ قَلْبِي وَنُورَ صَدْرِي.' }),

      D(2, 'learn', 'tafsir',
        { t: 'Tafsir As-Sa\'di on Al-Mulk vv. 1–5', s: SLOTS.morning,
          o: 'Read As-Sa\'di\'s tafsir on the five verses you memorised yesterday and extract three reflections.',
          src: 'Tafsir As-Sa\'di · Surah Al-Mulk vv. 1–5 · Arabic original or trusted English (e.g. Tafsir.com).',
          p: ['Read As-Sa\'di on verses 1–5 once carefully.',
              'Underline three short phrases that reframe how you understand the verses.',
              'Write a one-paragraph reflection on what tabarak al-ladhi biyadihil mulk means for your work.',
              'Recite verses 1–5 with the meaning in mind during Esha tonight.'],
          d: 'A one-paragraph reflection in your notebook + meaning-conscious recitation in Esha.',
          cl: 'Day 1 memorised these verses; Day 8 picks up verses 6–10.' },
        { t: 'تَفْسِيرُ السَّعْدِيِّ لِلْمُلْك ١–٥', s: SLOTS.morningAr,
          o: 'اِقْرَأْ تَفْسِيرَ السَّعْدِيِّ لِلْآيَاتِ التِي حَفِظْتَهَا أَمْسِ وَاسْتَخْرِجْ ثَلَاثَ تَأَمُّلَاتٍ.',
          src: 'تَفْسِيرُ السَّعْدِيِّ · المُلْك ١–٥ · الأَصْلُ العَرَبِيُّ.',
          p: ['اِقْرَأْ تَفْسِيرَ السَّعْدِيِّ لِلْآيَاتِ ١–٥ بِتَأَنٍّ مَرَّةً.',
              'سَطِّرْ ثَلَاثَ عِبَارَاتٍ تَفْتَحُ فَهْمَكَ لِلْآيَاتِ.',
              'اِكْتُبْ فِقْرَةً قَصِيرَةً عَنْ مَعْنَى «تَبَارَكَ الَّذِي بِيَدِهِ المُلْك» فِي حَيَاتِكَ المِهْنِيَّة.',
              'تَدَبَّرِ الآيَاتِ أَثْنَاءَ صَلَاةِ العِشَاء.'],
          d: 'فِقْرَةُ تَأَمُّلٍ فِي دَفْتَرِكَ + تِلَاوَةٌ مَعَ التَّدَبُّرِ فِي العِشَاء.',
          cl: 'اليَوْمُ ١ حَفِظَ الآيَاتِ؛ اليَوْمُ ٨ يَأْخُذُ الآيَاتِ ٦–١٠.' }),

      D(3, 'learn', 'hadith',
        { t: 'Nawawi #1 · "Actions are by intentions"', s: SLOTS.morning,
          o: 'Memorise Nawawi hadith #1 with its sanad and apply it to one decision today.',
          src: '40 Hadith of Imam An-Nawawi · #1 · Bukhari 1, Muslim 1907.',
          p: ['Read the Arabic text of the hadith three times.',
              'Memorise the matn (text) so you can recite it from memory.',
              'Read a short commentary (Ibn Daqiq, or Jami\' al-\'Ulum wal-Hikam summary).',
              'Pick one task today where you will explicitly renew your niyyah before starting.'],
          d: 'Hadith #1 memorised in Arabic + one task done with explicit renewed niyyah.',
          cl: 'Day 10 picks up Nawawi #2.' },
        { t: 'النَّوَوِيَّة ١ · «إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ»', s: SLOTS.morningAr,
          o: 'اِحْفَظِ الحَدِيثَ الأَوَّلَ بِسَنَدِهِ وَطَبِّقْهُ عَلَى قَرَارٍ وَاحِدٍ اليَوْم.',
          src: 'الأَرْبَعُونَ النَّوَوِيَّةُ · حَدِيث ١ · البُخَارِيُّ ١، مُسْلِمٌ ١٩٠٧.',
          p: ['اِقْرَأْ نَصَّ الحَدِيثِ ثَلَاثَ مَرَّاتٍ.',
              'اِحْفَظِ المَتْنَ حَتَّى تَتْلُوَهُ مِنَ الحِفْظِ.',
              'اِقْرَأْ شَرْحًا مُوجَزًا (ابْنُ دَقِيقٍ أَوْ جَامِعُ العُلُومِ).',
              'اِخْتَرْ مُهِمَّةً اليَوْمَ وَجَدِّدْ نِيَّتَكَ قَبْلَ البَدْءِ صَرَاحَةً.'],
          d: 'حِفْظُ الحَدِيثِ بِالعَرَبِيَّةِ + مُهِمَّةٌ تَامَّةٌ بِنِيَّةٍ مُجَدَّدَةٍ صَرَاحَةً.',
          cl: 'اليَوْمُ ١٠ يَأْخُذُ النَّوَوِيَّةَ ٢.' }),

      D(4, 'learn', 'fiqh',
        { t: 'Tahara · definition + types of najasah', s: SLOTS.morning,
          o: 'Understand the legal definition of tahara and the three categories of najasah (light, medium, heavy).',
          src: 'Umdat al-Salik · Book of Tahara · or Bulugh al-Maram Chapter 1.',
          p: ['Read the chapter\'s opening pages on the definition of tahara.',
              'Note the three categories of najasah with one example each.',
              'List five common modern items and classify them by category.',
              'Test yourself by quizzing a family member or writing flashcards.'],
          d: 'A flashcard set covering definitions + 5 modern examples classified.',
          cl: 'Day 11 covers wudu conditions; Day 18 covers wudu fards.' },
        { t: 'الطَّهَارَةُ · تَعْرِيفٌ وَأَنْوَاعُ النَّجَاسَة', s: SLOTS.morningAr,
          o: 'افْهَمْ تَعْرِيفَ الطَّهَارَةِ الشَّرْعِيَّ وَأَقْسَامَ النَّجَاسَةِ الثَّلَاثَة.',
          src: 'عُمْدَةُ السَّالِكِ كِتَابُ الطَّهَارَةِ · أَوْ بُلُوغُ المَرَامِ بَابُ الطَّهَارَة.',
          p: ['اِقْرَأِ الصَّفَحَاتِ الأُولَى مِنَ البَابِ.',
              'دَوِّنْ أَقْسَامَ النَّجَاسَةِ الثَّلَاثَةَ مَعَ مِثَالٍ لِكُلٍّ.',
              'اِذْكُرْ خَمْسَةَ أَشْيَاءَ مُعَاصِرَةٍ وَصَنِّفْهَا.',
              'اِخْتَبِرْ نَفْسَكَ بِبِطَاقَاتٍ أَوْ بِسُؤَالِ أَهْلِك.'],
          d: 'مَجْمُوعَةُ بِطَاقَاتٍ تَشْمَلُ التَّعَارِيفَ وَخَمْسَةَ أَمْثِلَةٍ مُصَنَّفَة.',
          cl: 'اليَوْمُ ١١ شُرُوطُ الوُضُوءِ، اليَوْمُ ١٨ فَرَائِضُ الوُضُوء.' }),

      D(5, 'learn', 'aqeedah',
        { t: 'Tawhid ar-Rububiyyah · Allah as sole Lord', s: SLOTS.morning,
          o: 'Understand the first category of tawhid — that Allah alone is Creator, Sustainer, and Sovereign.',
          src: 'Three Fundamentals of Sh. Muhammad ibn \'Abd al-Wahhab · Section on tawhid.',
          p: ['Read the section on tawhid ar-rububiyyah carefully.',
              'Note three verses cited as evidence.',
              'Identify one example of where modern people fall into rububiyyah doubts (e.g. attributing pure causation to created things).',
              'Write a two-sentence summary of this category in your own words.'],
          d: 'A two-sentence written definition + three Quranic evidences referenced.',
          cl: 'Day 12 covers tawhid al-uluhiyyah; Day 19 covers asma was-sifat.' },
        { t: 'تَوْحِيدُ الرُّبُوبِيَّة · اللَّهُ وَحْدَهُ الرَّبّ', s: SLOTS.morningAr,
          o: 'افْهَمْ أَوَّلَ أَقْسَامِ التَّوْحِيدِ — أَنَّ اللَّهَ وَحْدَهُ خَالِقٌ مُدَبِّرٌ مَالِك.',
          src: 'الأُصُولُ الثَّلَاثَةُ لِلشَّيْخِ مُحَمَّدِ بْنِ عَبْدِ الوَهَّابِ.',
          p: ['اِقْرَأْ بَابَ تَوْحِيدِ الرُّبُوبِيَّةِ بِتَأَنٍّ.',
              'دَوِّنْ ثَلَاثَ آيَاتٍ شَاهِدَة.',
              'اُذْكُرْ مَثَلًا مُعَاصِرًا يَقَعُ فِيهِ النَّاسُ مِنْ خَلَلٍ فِي الرُّبُوبِيَّة.',
              'اِكْتُبْ تَعْرِيفًا فِي سَطْرَيْنِ بِأُسْلُوبِكَ.'],
          d: 'تَعْرِيفٌ فِي سَطْرَيْنِ + ثَلَاثُ آيَاتٍ شَاهِدَة.',
          cl: 'اليَوْمُ ١٢ الأُلُوهِيَّة، اليَوْمُ ١٩ الأَسْمَاءُ وَالصِّفَات.' }),

      D(6, 'learn', 'seerah',
        { t: 'Arabia before Islam · the social fabric', s: SLOTS.morning,
          o: 'Map the tribal, religious, and economic landscape of Arabia immediately before the Prophet\'s birth ﷺ.',
          src: 'Ar-Raheeq al-Makhtum (The Sealed Nectar) · Chapter 1.',
          p: ['Read Chapter 1 of Ar-Raheeq al-Makhtum.',
              'Note three tribes, three forms of shirk, and three economic facts.',
              'Sketch a one-page mind-map of the pre-Islamic Arabia world.',
              'Notice one parallel between pre-Islamic disorder and modern moral disorder.'],
          d: 'One-page mind-map of pre-Islamic Arabia in your notebook.',
          cl: 'Day 13 covers the birth of the Prophet ﷺ.' },
        { t: 'جَزِيرَةُ العَرَبِ قَبْلَ الإِسْلَامِ', s: SLOTS.morningAr,
          o: 'اِرْسُمْ خَرِيطَةَ القَبَائِلِ وَالدِّيَانَاتِ وَالاقْتِصَادِ فِي الجَزِيرَةِ قَبْلَ المَوْلِدِ النَّبَوِيّ ﷺ.',
          src: 'الرَّحِيقُ المَخْتُومُ · الفَصْلُ الأَوَّل.',
          p: ['اِقْرَأِ الفَصْلَ الأَوَّلَ مِنَ الرَّحِيقِ المَخْتُومِ.',
              'دَوِّنْ ثَلَاثَ قَبَائِلَ وَثَلَاثَةَ أَنْوَاعِ شِرْكٍ وَثَلَاثَ حَقَائِقَ اقْتِصَادِيَّة.',
              'اِرْسُمْ خَرِيطَةً ذِهْنِيَّةً عَلَى صَفْحَةٍ وَاحِدَة.',
              'لَاحِظْ مُوَازَنَةً بَيْنَ الفَوْضَى الجَاهِلِيَّةِ وَالمُعَاصِرَة.'],
          d: 'خَرِيطَةٌ ذِهْنِيَّةٌ مِنْ صَفْحَةٍ فِي دَفْتَرِك.',
          cl: 'اليَوْمُ ١٣ المَوْلِدُ النَّبَوِيّ ﷺ.' }),

      D(7, 'revise', 'revise',
        { t: 'Week 1 cumulative revision', s: SLOTS.review,
          o: 'Re-touch every day from days 1–6 to lock the week before adding more.',
          src: 'Your notebook + the original sources.',
          p: ['Recite Al-Mulk 1–5 from memory once.',
              'Re-read the As-Sa\'di tafsir paragraph and your reflection.',
              'Recite Nawawi #1 from memory.',
              'Quiz yourself on the three najasah categories and Tawhid ar-Rububiyyah definition.',
              'Re-skim your Seerah mind-map and add one bullet you forgot.'],
          d: 'Five-line journal entry on what stuck and what slipped this week.',
          cl: 'Cycle 2 begins on Day 8 with Al-Mulk 6–10.' },
        { t: 'مُرَاجَعَةُ الأُسْبُوعِ الأَوَّلِ', s: SLOTS.reviewAr,
          o: 'لَامِسْ كُلَّ يَوْمٍ مِنَ ١ إِلَى ٦ لِتَثْبِيتِ الأُسْبُوعِ قَبْلَ الزِّيَادَة.',
          src: 'دَفْتَرُكَ + المَصَادِرُ الأَصْلِيَّة.',
          p: ['تَلَاوَةُ المُلْك ١–٥ مِنَ الحِفْظِ مَرَّةً.',
              'مُرَاجَعَةُ التَّفْسِيرِ وَالتَّأَمُّل.',
              'تَلَاوَةُ النَّوَوِيَّةِ ١ مِنَ الحِفْظ.',
              'اِخْتَبِرْ نَفْسَكَ فِي أَقْسَامِ النَّجَاسَةِ وَتَوْحِيدِ الرُّبُوبِيَّة.',
              'أَعِدِ النَّظَرَ فِي خَرِيطَةِ السِّيرَةِ وَزِدْ نُقْطَةً نَاقِصَة.'],
          d: 'مُذَكَّرَةُ خَمْسَةِ سُطُورٍ عَمَّا ثَبَتَ وَمَا تَسَرَّبَ.',
          cl: 'الدَّوْرَةُ الثَّانِيَةُ تَبْدَأُ مِنَ اليَوْمِ ٨ بِالمُلْك ٦–١٠.' }),

      // ── Cycle 2 (Days 8-14) ──
      D(8, 'learn', 'quran',
        { t: 'Al-Mulk vv. 6–10 · memorise', s: SLOTS.quran,
          o: 'Memorise verses 6–10 of Surah Al-Mulk with tajweed; cumulative this week: 10.',
          src: 'Mushaf al-Madinah p. 562–563 · same reciter as Day 1.',
          p: ['Read verses 6–10 aloud three times from the mushaf.',
              'Listen twice from the reciter, attending to where you stop and start.',
              'Recite from memory five times.',
              'Recite verses 1–10 in Esha qiyam tonight.'],
          d: 'Cumulative Al-Mulk 1–10 recited in Esha.',
          cl: 'Day 9 will tafsir these.' },
        { t: 'المُلْك ٦–١٠ · حِفْظ', s: SLOTS.quranAr,
          o: 'اِحْفَظِ الآيَاتِ ٦–١٠ بِالتَّجْوِيدِ؛ التَّرَاكُمُ هَذَا الأُسْبُوع: ١٠.',
          src: 'مُصْحَفُ المَدِينَةِ ص ٥٦٢–٥٦٣ · القَارِئُ السَّابِق.',
          p: ['ثَلَاثُ قِرَاءَاتٍ بِالتَّجْوِيدِ مِنَ المُصْحَف.',
              'اِسْتِمَاعَانِ مِنَ القَارِئ.',
              'خَمْسُ مَرَّاتٍ مِنَ الحِفْظ.',
              'تَلَاوَةُ ١–١٠ فِي قِيَامِ العِشَاء.'],
          d: 'تَلَاوَةُ المُلْك ١–١٠ تَرَاكُمِيًّا فِي العِشَاء.',
          cl: 'اليَوْمُ ٩ يُفَسِّرُهَا.' }),

      D(9, 'learn', 'tafsir',
        { t: 'Tafsir As-Sa\'di on Al-Mulk vv. 6–10', s: SLOTS.morning,
          o: 'Read As-Sa\'di on verses 6–10 and extract three reflections on the nature of jahannam.',
          src: 'Tafsir As-Sa\'di · Al-Mulk 6–10.',
          p: ['Read As-Sa\'di on these verses once carefully.',
              'Underline three phrases about the hereafter.',
              'Write a short reflection on what it means that hellfire "almost bursts with rage".',
              'Recite verses 6–10 with the meaning in mind tonight.'],
          d: 'Notebook reflection on the imagery of jahannam.',
          cl: 'Day 8 memorised; Day 16 picks up 11–20.' },
        { t: 'تَفْسِيرُ السَّعْدِيِّ لِلْمُلْك ٦–١٠', s: SLOTS.morningAr,
          o: 'تَأَمَّلْ تَفْسِيرَ السَّعْدِيِّ لِلْآيَاتِ ٦–١٠ وَاسْتَخْرِجْ ثَلَاثَ تَأَمُّلَاتٍ عَنْ جَهَنَّم.',
          src: 'تَفْسِيرُ السَّعْدِيِّ · المُلْك ٦–١٠.',
          p: ['اِقْرَأْ التَّفْسِيرَ بِتَأَنٍّ مَرَّة.',
              'سَطِّرْ ثَلَاثَ عِبَارَاتٍ عَنِ الآخِرَة.',
              'اِكْتُبْ تَأَمُّلًا فِي قَوْلِهِ تَعَالَى «تَكَادُ تَمَيَّزُ مِنَ الغَيْظ».',
              'تَدَبَّرِ الآيَاتِ فِي صَلَاتِك.'],
          d: 'تَأَمُّلٌ فِي دَفْتَرِكَ عَنْ صُوَرِ جَهَنَّم.',
          cl: 'اليَوْمُ ٨ حَفِظَهَا، اليَوْمُ ١٦ يَأْخُذُ ١١–٢٠.' }),

      D(10, 'learn', 'hadith',
        { t: 'Nawawi #2 · Islam, Iman, Ihsan (Jibreel hadith)', s: SLOTS.morning,
          o: 'Memorise Nawawi #2 and outline the three levels of religion (Islam, Iman, Ihsan).',
          src: '40 Hadith of An-Nawawi · #2 · Muslim 8.',
          p: ['Read the long Arabic text three times.',
              'Memorise at least the framing question and Jibreel\'s questions.',
              'Outline the three levels with what each contains (5 pillars, 6 beliefs, ihsan definition).',
              'Identify which of the three you most need to strengthen this month.'],
          d: 'A clean outline of Islam/Iman/Ihsan + a personal action item on the weakest level.',
          cl: 'Day 17 covers Nawawi #3 (pillars expanded).' },
        { t: 'النَّوَوِيَّة ٢ · الإِسْلَام، الإِيمَان، الإِحْسَان', s: SLOTS.morningAr,
          o: 'اِحْفَظِ الحَدِيثَ الثَّانِيَ وَلَخِّصْ مَرَاتِبَ الدِّينِ الثَّلَاث.',
          src: 'النَّوَوِيَّة ٢ · مُسْلِمٌ ٨.',
          p: ['ثَلَاثُ قِرَاءَاتٍ لِلْمَتْنِ العَرَبِيِّ.',
              'حِفْظُ سُؤَالِ جِبْرِيلَ وَجَوَابِهِ.',
              'تَلْخِيصُ المَرَاتِبِ الثَّلَاثِ (الأَرْكَانُ، الإِيمَانُ، الإِحْسَان).',
              'تَحْدِيدُ المَرْتَبَةِ الأَضْعَفِ عِنْدَكَ هَذَا الشَّهْر.'],
          d: 'تَلْخِيصٌ مُنَظَّمٌ + بَنْدٌ شَخْصِيٌّ لِلْأَضْعَف.',
          cl: 'اليَوْمُ ١٧ النَّوَوِيَّةُ ٣.' }),

      D(11, 'learn', 'fiqh',
        { t: 'Wudu · conditions (shurut) and intention', s: SLOTS.morning,
          o: 'Know the conditions for valid wudu and the role of niyyah.',
          src: 'Umdat al-Salik · Chapter on Wudu · or Fiqh As-Sunnah Vol. 1.',
          p: ['Read the section on shurut al-wudu.',
              'List the conditions on one page (Muslim, intention, water type, etc.).',
              'Compare two madhab opinions on tartib (sequence) — Shafi\'i vs Hanafi.',
              'Make today\'s wudu with deliberate niyyah, slowly and consciously.'],
          d: 'One-page list of wudu conditions + a deliberate wudu performed.',
          cl: 'Day 18 covers the fards of wudu.' },
        { t: 'الوُضُوءُ · الشُّرُوطُ وَالنِّيَّة', s: SLOTS.morningAr,
          o: 'اِعْرِفْ شُرُوطَ صِحَّةِ الوُضُوءِ وَدَوْرَ النِّيَّةِ.',
          src: 'عُمْدَةُ السَّالِكِ بَابُ الوُضُوءِ · أَوْ فِقْهُ السُّنَّة.',
          p: ['اِقْرَأْ بَابَ شُرُوطِ الوُضُوء.',
              'لَخِّصِ الشُّرُوطَ فِي وَرَقَةٍ وَاحِدَة.',
              'قَارِنْ رَأْيَيْنِ فِي التَّرْتِيب (شَافِعِيّ وَحَنَفِيّ).',
              'تَوَضَّأْ اليَوْمَ بِنِيَّةٍ صَرِيحَةٍ مُتَأَنِّيَة.'],
          d: 'وَرَقَةُ شُرُوطٍ + وُضُوءٌ مُتَأَنٍّ.',
          cl: 'اليَوْمُ ١٨ فَرَائِضُ الوُضُوء.' }),

      D(12, 'learn', 'aqeedah',
        { t: 'Tawhid al-Uluhiyyah · worship for Allah alone', s: SLOTS.morning,
          o: 'Understand the second category of tawhid — that worship is due to Allah alone.',
          src: 'Three Fundamentals · Section on uluhiyyah · or Kitab at-Tawhid Ch 1.',
          p: ['Read the section on tawhid al-uluhiyyah.',
              'Note three verses showing exclusivity of worship.',
              'List five acts of worship (dua, sajdah, nadhr, dhabh, tawakkul) that must not be given to other than Allah.',
              'Audit one personal habit: is anything in your life functioning as a rival deity (career, comfort, image)?'],
          d: 'A one-paragraph audit of a personal "rival deity" risk.',
          cl: 'Day 19 covers asma was-sifat.' },
        { t: 'تَوْحِيدُ الأُلُوهِيَّة · العِبَادَةُ لِلَّهِ وَحْدَه', s: SLOTS.morningAr,
          o: 'افْهَمْ ثَانِيَ أَقْسَامِ التَّوْحِيدِ — أَنَّ العِبَادَةَ لِلَّهِ وَحْدَه.',
          src: 'الأُصُولُ الثَّلَاثَةُ · بَابُ الأُلُوهِيَّةِ.',
          p: ['اِقْرَأْ بَابَ الأُلُوهِيَّة.',
              'دَوِّنْ ثَلَاثَ آيَاتٍ شَاهِدَة.',
              'عَدِّدْ خَمْسَ عِبَادَاتٍ لَا تُصْرَفُ لِغَيْرِ اللَّه (دُعَاء، سُجُود، نَذْر، ذَبْح، تَوَكُّل).',
              'حَاسِبْ عَادَةً فِي حَيَاتِكَ: هَلْ شَيْءٌ يَتَّخِذُ مَكَانَ المَعْبُود؟'],
          d: 'مُحَاسَبَةٌ شَخْصِيَّةٌ فِي فِقْرَة.',
          cl: 'اليَوْمُ ١٩ الأَسْمَاءُ وَالصِّفَات.' }),

      D(13, 'learn', 'seerah',
        { t: 'Birth of the Prophet ﷺ · early signs', s: SLOTS.morning,
          o: 'Learn the events surrounding the birth of the Prophet ﷺ and the unique signs at his coming.',
          src: 'Ar-Raheeq al-Makhtum · Chapter on birth and lineage.',
          p: ['Read the chapter on the birth and lineage.',
              'Note three signs/events that marked his birth (Aamul-Fil, the lights, etc.).',
              'Trace his lineage two generations back from Abdullah.',
              'Reflect on what it means that the Prophet ﷺ was orphaned early.'],
          d: 'A brief lineage chart and a paragraph reflection on orphanhood as preparation.',
          cl: 'Day 20 covers his childhood.' },
        { t: 'المَوْلِدُ النَّبَوِيُّ ﷺ · العَلَامَاتُ المُبَكِّرَة', s: SLOTS.morningAr,
          o: 'تَعَلَّمْ أَحْدَاثَ المَوْلِدِ وَالعَلَامَاتِ المُمَيَّزَةَ لِبَعْثَتِهِ ﷺ.',
          src: 'الرَّحِيقُ المَخْتُومُ بَابُ المَوْلِدِ وَالنَّسَب.',
          p: ['اِقْرَأْ بَابَ المَوْلِدِ وَالنَّسَب.',
              'دَوِّنْ ثَلَاثَ عَلَامَاتٍ (عَامُ الفِيلِ، الأَنْوَار، إِلَخ).',
              'تَتَبَّعْ نَسَبَهُ ﷺ جِيلَيْنِ.',
              'تَأَمَّلْ يُتْمَهُ ﷺ المُبَكِّرَ.'],
          d: 'شَجَرَةُ نَسَبٍ مُوجَزَةٌ + تَأَمُّلٌ فِي اليُتْم.',
          cl: 'اليَوْمُ ٢٠ طُفُولَتُهُ ﷺ.' }),

      D(14, 'revise', 'revise',
        { t: 'Week 2 cumulative revision', s: SLOTS.review,
          o: 'Lock days 8–13 before adding more in cycle 3.',
          src: 'Your notebook + original sources.',
          p: ['Recite Al-Mulk 1–10 from memory.',
              'Re-read the As-Sa\'di tafsir on 6–10 + jahannam reflection.',
              'Recite Nawawi #1 and #2 from memory.',
              'Quiz yourself on wudu conditions + tawhid al-uluhiyyah.',
              'Re-read the birth chapter notes.'],
          d: 'Journal entry on what is becoming automatic and what still requires concentration.',
          cl: 'Cycle 3 begins on Day 15 with Al-Mulk 11–20.' },
        { t: 'مُرَاجَعَةُ الأُسْبُوعِ الثَّانِي', s: SLOTS.reviewAr,
          o: 'ثَبِّتْ أَيَّامَ ٨–١٣ قَبْلَ الدَّوْرَةِ الثَّالِثَة.',
          src: 'الدَّفْتَرُ + المَصَادِر.',
          p: ['تَلَاوَةُ المُلْك ١–١٠ مِنَ الحِفْظ.',
              'إِعَادَةُ تَفْسِيرِ ٦–١٠ وَتَأَمُّلِ جَهَنَّم.',
              'تَلَاوَةُ النَّوَوِيَّتَيْنِ ١ وَ٢.',
              'اِخْتَبِرْ نَفْسَكَ فِي شُرُوطِ الوُضُوءِ وَالأُلُوهِيَّة.',
              'مُرَاجَعَةُ مُلَخَّصِ المَوْلِد.'],
          d: 'مُذَكَّرَةٌ عَمَّا أَصْبَحَ تِلْقَائِيًّا وَمَا يَحْتَاجُ تَرْكِيزًا.',
          cl: 'الدَّوْرَةُ الثَّالِثَةُ مِنَ اليَوْمِ ١٥.' }),

      // ── Cycle 3 (Days 15-20) ──
      D(15, 'learn', 'quran',
        { t: 'Al-Mulk vv. 11–20 · memorise (double load)', s: SLOTS.quran,
          o: 'Memorise ten ayaat in one day (the biggest single push this month) — verses 11–20.',
          src: 'Mushaf al-Madinah p. 563.',
          p: ['Read verses 11–20 five times from the mushaf with tajweed.',
              'Listen three times from your reciter.',
              'Recite from memory eight times in three sittings.',
              'Recite 1–20 in Esha tonight and again at Tahajjud.'],
          d: 'Cumulative Al-Mulk 1–20 recited in two prayers.',
          cl: 'Day 16 will tafsir these.' },
        { t: 'المُلْك ١١–٢٠ · حِفْظٌ مُضَاعَف', s: SLOTS.quranAr,
          o: 'اِحْفَظْ عَشْرَ آيَاتٍ فِي يَوْمٍ وَاحِدٍ — الآيَاتُ ١١–٢٠.',
          src: 'مُصْحَفُ المَدِينَةِ ص ٥٦٣.',
          p: ['خَمْسُ قِرَاءَاتٍ بِالتَّجْوِيدِ.',
              'ثَلَاثُ اسْتِمَاعَاتٍ.',
              'ثَمَانِي مَرَّاتٍ مِنَ الحِفْظِ فِي ثَلَاثِ جَلَسَاتٍ.',
              'تَلَاوَةُ ١–٢٠ فِي العِشَاءِ وَالتَّهَجُّد.'],
          d: 'تَلَاوَةُ ١–٢٠ فِي صَلَاتَيْنِ.',
          cl: 'اليَوْمُ ١٦ يُفَسِّرُهَا.' }),

      D(16, 'learn', 'tafsir',
        { t: 'Tafsir As-Sa\'di on Al-Mulk vv. 11–20', s: SLOTS.morning,
          o: 'Read As-Sa\'di on the ten verses and pick three themes (knowledge of Allah, sustenance, recompense).',
          src: 'Tafsir As-Sa\'di · Al-Mulk 11–20.',
          p: ['Read As-Sa\'di on verses 11–20 twice.',
              'Identify three repeating themes.',
              'Note one verse that re-reads differently after the tafsir.',
              'Recite 11–20 with the meaning in mind tonight.'],
          d: 'A note of three themes + one verse re-read.',
          cl: 'Day 22 starts month-end revision.' },
        { t: 'تَفْسِيرُ السَّعْدِيِّ لِلْمُلْك ١١–٢٠', s: SLOTS.morningAr,
          o: 'اِقْرَأْ تَفْسِيرَ السَّعْدِيِّ لِلْآيَاتِ ١١–٢٠ وَاسْتَخْرِجْ ثَلَاثَةَ مَوَاضِيع.',
          src: 'تَفْسِيرُ السَّعْدِيِّ · المُلْك ١١–٢٠.',
          p: ['اِقْرَأْ التَّفْسِيرَ مَرَّتَيْن.',
              'حَدِّدْ ثَلَاثَةَ مَوَاضِيعَ مُكَرَّرَة.',
              'دَوِّنْ آيَةً أَعَدْتَ قِرَاءَتَهَا بَعْدَ التَّفْسِير.',
              'تَدَبَّرِ ١١–٢٠ فِي صَلَاتِك.'],
          d: 'مُلَاحَظَةُ ثَلَاثَةِ مَوَاضِيعَ + آيَةٌ أُعِيدَ فَهْمُهَا.',
          cl: 'اليَوْمُ ٢٢ يَبْدَأُ مُرَاجَعَةَ الشَّهْر.' }),

      D(17, 'learn', 'hadith',
        { t: 'Nawawi #3 · The five pillars expanded', s: SLOTS.morning,
          o: 'Memorise Nawawi #3 and reconcile its five pillars with the Jibreel hadith framework.',
          src: '40 Hadith of An-Nawawi · #3 · Bukhari 8, Muslim 16.',
          p: ['Read and memorise the Arabic text.',
              'Map each pillar to a row of your daily plan (e.g. shahadah → niyyah, salah → 5 daily prayers).',
              'Identify which pillar is weakest in your current practice.',
              'Set one concrete action this week to strengthen it.'],
          d: 'A five-row table mapping pillars to daily acts + one action set.',
          cl: 'Day 24 reviews Nawawi 1–3.' },
        { t: 'النَّوَوِيَّة ٣ · الأَرْكَانُ الخَمْسَة', s: SLOTS.morningAr,
          o: 'اِحْفَظِ الحَدِيثَ الثَّالِثَ وَوَفِّقْ بَيْنَ أَرْكَانِهِ وَحَدِيثِ جِبْرِيل.',
          src: 'النَّوَوِيَّة ٣ · البُخَارِيُّ ٨، مُسْلِمٌ ١٦.',
          p: ['اِقْرَأْ وَاحْفَظِ المَتْنَ العَرَبِيَّ.',
              'اِرْبِطْ كُلَّ رُكْنٍ بِخَانَةٍ مِنْ يَوْمِك.',
              'حَدِّدْ أَضْعَفَ رُكْنٍ فِي وَاقِعِك.',
              'ضَعْ خُطْوَةً وَاحِدَةً لِتَقْوِيَتِهِ هَذَا الأُسْبُوع.'],
          d: 'جَدْوَلٌ مِنْ خَمْسَةِ صُفُوفٍ + خُطْوَةٌ مُحَدَّدَة.',
          cl: 'اليَوْمُ ٢٤ مُرَاجَعَةُ النَّوَوِيَّاتِ ١–٣.' }),

      D(18, 'learn', 'fiqh',
        { t: 'Wudu · the fards (obligatory acts)', s: SLOTS.morning,
          o: 'Master the six fards of wudu so that every wudu you make is valid by default.',
          src: 'Umdat al-Salik · Wudu chapter, section on fards.',
          p: ['List the six fards in order: niyyah, washing face, washing hands+arms, masah of head, washing feet, tartib.',
              'Read each with its evidence from Quran 5:6 and the Sunnah.',
              'Practice a slow, complete wudu naming each fard out loud.',
              'Note one common mistake people make (rushing the masah, missing the heels).'],
          d: 'A slow wudu performed with each fard named + one common mistake logged.',
          cl: 'Day 25 will quiz wudu mastery.' },
        { t: 'فَرَائِضُ الوُضُوءِ', s: SLOTS.morningAr,
          o: 'أَتْقِنْ فَرَائِضَ الوُضُوءِ السِّتَّ حَتَّى يَكُونَ وُضُوؤُكَ صَحِيحًا تِلْقَائِيًّا.',
          src: 'عُمْدَةُ السَّالِكِ بَابُ الوُضُوءِ.',
          p: ['عَدِّدِ السِّتَّةَ بِالتَّرْتِيب: النِّيَّة، الوَجْه، اليَدَيْن، المَسْح، الرِّجْلَيْن، التَّرْتِيب.',
              'اِقْرَأْ دَلِيلَ كُلٍّ مِنَ المَائِدَةِ ٦ وَالسُّنَّة.',
              'مَارِسْ وُضُوءًا بَطِيئًا تُسَمِّي فِيهِ كُلَّ فَرْض.',
              'سَجِّلْ خَطَأً شَائِعًا (تَرْكُ العَقِبَيْنِ مَثَلًا).'],
          d: 'وُضُوءٌ مُتَأَنٍّ مَعَ تَسْمِيَةِ الفَرَائِضِ + خَطَأٌ مَوْثُوق.',
          cl: 'اليَوْمُ ٢٥ اِخْتِبَارُ الوُضُوء.' }),

      D(19, 'learn', 'aqeedah',
        { t: 'Tawhid al-Asma was-Sifaat · names and attributes', s: SLOTS.morning,
          o: 'Understand the third category — affirm what Allah affirmed of His names and attributes, without distortion, denial, or anthropomorphism.',
          src: 'Three Fundamentals · or al-Wasitiyyah of Ibn Taymiyyah.',
          p: ['Read the section on names and attributes.',
              'Memorise the principle: "we affirm what He affirmed, without takyif, tamthil, ta\'til, tahrif".',
              'List five names of Allah and one attribute each implies for our conduct.',
              'Reflect on Allah\'s Latif and Khabir on your current decisions.'],
          d: 'A list of five names + reflection on Latif/Khabir.',
          cl: 'Day 26 quizzes the three categories.' },
        { t: 'تَوْحِيدُ الأَسْمَاءِ وَالصِّفَات', s: SLOTS.morningAr,
          o: 'تَلَقَّ صِفَاتِ اللَّهِ كَمَا أَثْبَتَهَا، بِلَا تَحْرِيفٍ وَلَا تَعْطِيلٍ وَلَا تَكْيِيفٍ وَلَا تَمْثِيل.',
          src: 'الأُصُولُ الثَّلَاثَةُ · أَوِ الوَاسِطِيَّة.',
          p: ['اِقْرَأْ بَابَ الأَسْمَاءِ وَالصِّفَات.',
              'اِحْفَظِ القَاعِدَةَ: «نُثْبِتُ مَا أَثْبَتَ بِلَا تَكْيِيفٍ وَلَا تَمْثِيلٍ».',
              'اُذْكُرْ خَمْسَةً مِنْ أَسْمَاءِ اللَّهِ مَعَ أَثَرٍ سُلُوكِيٍّ لِكُلٍّ.',
              'تَأَمَّلِ «اللَّطِيفُ الخَبِيرُ» فِي قَرَارَاتِكَ الحَالِيَّة.'],
          d: 'قَائِمَةُ خَمْسَةِ أَسْمَاءٍ + تَأَمُّل.',
          cl: 'اليَوْمُ ٢٦ اِخْتِبَارُ الأَقْسَامِ الثَّلَاثَة.' }),

      D(20, 'learn', 'seerah',
        { t: 'Childhood of the Prophet ﷺ · Halima\'s care + foster years', s: SLOTS.morning,
          o: 'Understand his foster upbringing in the desert and the early forming of his character.',
          src: 'Ar-Raheeq al-Makhtum · Chapter on childhood and youth.',
          p: ['Read the foster years section.',
              'Note three character traits formed in this period.',
              'Note the splitting-of-the-chest incident and what it foreshadowed.',
              'Reflect on parenting in your own family in light of this period.'],
          d: 'Three character traits + a parenting reflection.',
          cl: 'Day 27 covers his youth and pre-prophethood years.' },
        { t: 'طُفُولَةُ النَّبِيِّ ﷺ · حَلِيمَةُ السَّعْدِيَّة', s: SLOTS.morningAr,
          o: 'افْهَمْ نَشْأَتَهُ ﷺ فِي البَادِيَةِ وَتَكْوِينَ شَخْصِيَّتِهِ المُبَكِّرَة.',
          src: 'الرَّحِيقُ المَخْتُومُ · بَابُ الطُّفُولَةِ وَالشَّبَاب.',
          p: ['اِقْرَأْ بَابَ الرَّضَاعَةِ فِي البَادِيَة.',
              'دَوِّنْ ثَلَاثَ سِمَاتٍ شَخْصِيَّةٍ تَكَوَّنَتْ.',
              'لَاحِظْ حَادِثَةَ شَقِّ الصَّدْرِ وَدَلَالَاتِهَا.',
              'تَأَمَّلْ تَرْبِيَتَكَ لِأَوْلَادِكَ فِي ضَوْءِ هَذَا.'],
          d: 'ثَلَاثُ سِمَاتٍ + تَأَمُّلٌ تَرْبَوِيّ.',
          cl: 'اليَوْمُ ٢٧ مَرْحَلَةُ الشَّبَاب.' }),

      // ── Days 21-30: Month-end revision ──
      D(21, 'revise', 'quran',
        { t: 'Quran revision · Al-Mulk 1–20 from memory', s: SLOTS.quran,
          o: 'Recite all twenty memorised ayaat from memory three times across the day to lock them.',
          src: 'Memory only · check the mushaf only for stumbles.',
          p: ['Recite 1–20 once after Fajr.',
              'Recite again at Dhuhr.',
              'Recite a third time in Esha qiyam.',
              'Mark any verse that needed a peek and re-recite it 10 times.'],
          d: 'All 20 ayaat recited three times from memory; weak verses re-drilled.',
          cl: 'Day 28 will recite the full surah.' },
        { t: 'مُرَاجَعَةُ المُلْك ١–٢٠ مِنَ الحِفْظ', s: SLOTS.quranAr,
          o: 'اُتْلِ العِشْرِينَ آيَةً ثَلَاثَ مَرَّاتٍ فِي اليَوْمِ لِتَثْبِيتِهَا.',
          src: 'مِنَ الحِفْظِ فَقَط · العَوْدَةُ إِلَى المُصْحَفِ عِنْدَ التَّعَثُّر.',
          p: ['تَلَاوَةٌ بَعْدَ الفَجْر.',
              'تَلَاوَةٌ عِنْدَ الظُّهْر.',
              'تَلَاوَةٌ فِي قِيَامِ العِشَاء.',
              'كَرِّرِ الآيَاتِ المُتَعَثِّرَةَ عَشْرَ مَرَّاتٍ.'],
          d: 'تَلَاوَةُ ٢٠ آيَةً ثَلَاثَ مَرَّاتٍ.',
          cl: 'اليَوْمُ ٢٨ تَلَاوَةُ السُّورَةِ كَامِلَة.' }),

      D(22, 'revise', 'tafsir',
        { t: 'Tafsir consolidation · the three themes of Al-Mulk', s: SLOTS.morning,
          o: 'Re-read As-Sa\'di on all twenty verses and consolidate the three running themes.',
          src: 'Tafsir As-Sa\'di · Al-Mulk 1–20.',
          p: ['Re-read As-Sa\'di on 1–20 in one sitting.',
              'List the three themes that run through the surah (sovereignty, gratitude, accountability).',
              'Pick one verse that has become a personal anchor and write a short reflection.',
              'Recite the surah at Esha with each theme alive.'],
          d: 'Three-theme summary + one anchor-verse reflection.',
          cl: 'Day 28 closes Quran with a full recitation.' },
        { t: 'تَوْطِيدُ التَّفْسِيرِ · ثَلَاثَةُ مَوَاضِيع', s: SLOTS.morningAr,
          o: 'أَعِدْ قِرَاءَةَ تَفْسِيرِ السَّعْدِيِّ لِلْعِشْرِينَ كُلِّهَا وَوَطِّدِ المَوَاضِيعَ الثَّلَاثَة.',
          src: 'تَفْسِيرُ السَّعْدِيِّ · المُلْك ١–٢٠.',
          p: ['إِعَادَةُ القِرَاءَةِ فِي جَلْسَةٍ.',
              'تَلْخِيصُ المَوَاضِيعِ الثَّلَاثَة.',
              'اِخْتَرْ آيَةً مِرْسَاةً وَاكْتُبْ تَأَمُّلًا.',
              'تَلَاوَةُ السُّورَةِ فِي العِشَاءِ مَعَ التَّدَبُّر.'],
          d: 'تَلْخِيصُ ثَلَاثَةِ مَوَاضِيعَ + تَأَمُّل.',
          cl: 'اليَوْمُ ٢٨ تَلَاوَةٌ كَامِلَة.' }),

      D(23, 'revise', 'hadith',
        { t: 'Hadith consolidation · Nawawi 1–3 review', s: SLOTS.morning,
          o: 'Recite all three memorised hadith from memory and reflect on how each is showing up in your practice.',
          src: 'Your hadith notebook.',
          p: ['Recite Nawawi #1, #2, #3 from memory.',
              'For each, write one line of "this is how it showed up this month".',
              'Identify a single hadith to push deeper into next month.',
              'Make dua that Allah accepts the niyyah of the memorisation.'],
          d: 'Three short application notes + one push for month 2.',
          cl: 'Month 2 begins with Nawawi #4–7.' },
        { t: 'مُرَاجَعَةُ النَّوَوِيَّاتِ ١–٣', s: SLOTS.morningAr,
          o: 'تَلَاوَةُ الأَحَادِيثِ الثَّلَاثَةِ مِنَ الحِفْظِ وَتَأَمُّلٌ فِي تَطْبِيقِ كُلٍّ مِنْهَا.',
          src: 'دَفْتَرُ الحَدِيثِ.',
          p: ['تَلَاوَةُ الأَحَادِيثِ مِنَ الحِفْظ.',
              'سَطْرٌ لِكُلِّ حَدِيثٍ: «كَيْفَ ظَهَرَ هَذَا الشَّهْر».',
              'اِخْتَرْ حَدِيثًا تُعَمِّقُهُ الشَّهْرَ القَادِم.',
              'اِدْعُ بِقَبُولِ النِّيَّةِ.'],
          d: 'ثَلَاثُ تَطْبِيقَاتٍ + بَنْدٌ لِلشَّهْرِ القَادِم.',
          cl: 'الشَّهْرُ ٢ يَبْدَأُ بِالنَّوَوِيَّاتِ ٤–٧.' }),

      D(24, 'revise', 'fiqh',
        { t: 'Fiqh review · wudu mastery test', s: SLOTS.morning,
          o: 'Perform a slow, narrated wudu in front of a mirror and self-grade against the fards + sunnan.',
          src: 'Your wudu notebook page.',
          p: ['Make a slow, deliberate wudu narrating each step.',
              'Self-grade: every fard counted? every sunnah included (siwak, three washes)?',
              'Note any gap and correct it on the spot.',
              'Make a brief dua of acceptance after wudu.'],
          d: 'Self-grade card on wudu + corrections noted.',
          cl: 'Month 2 expands to salah pillars.' },
        { t: 'اِخْتِبَارُ الوُضُوءِ', s: SLOTS.morningAr,
          o: 'تَوَضَّأْ مُتَأَنِّيًا أَمَامَ مِرْآةٍ وَقَيِّمْ نَفْسَكَ.',
          src: 'صَفْحَةُ دَفْتَرِ الوُضُوء.',
          p: ['وُضُوءٌ مُتَأَنٍّ بِسَرْدِ كُلِّ خُطْوَة.',
              'تَقْيِيمٌ ذَاتِيٌّ لِلْفَرَائِضِ وَالسُّنَن.',
              'تَصْحِيحٌ فَوْرِيّ.',
              'دُعَاءُ القَبُولِ بَعْدَ الوُضُوء.'],
          d: 'بِطَاقَةُ تَقْيِيمٍ + تَصْحِيحَات.',
          cl: 'الشَّهْرُ ٢ يَتَوَسَّعُ إِلَى الصَّلَاة.' }),

      D(25, 'revise', 'aqeedah',
        { t: 'Aqeedah quiz · the three categories of tawhid', s: SLOTS.morning,
          o: 'Quiz yourself out loud on the three categories and one practical implication of each.',
          src: 'Your aqeedah notebook.',
          p: ['Define each of the three categories from memory.',
              'Give one Quranic evidence for each.',
              'Give one practical implication for each in your daily life.',
              'Note any category that felt fuzzy and re-read tomorrow.'],
          d: 'A clean three-category card recited from memory + one fuzzy area marked.',
          cl: 'Month 2 covers the names and attributes deeper.' },
        { t: 'اِخْتِبَارُ التَّوْحِيدِ', s: SLOTS.morningAr,
          o: 'اِخْتَبِرْ نَفْسَكَ بِصَوْتٍ مَسْمُوعٍ فِي الأَقْسَامِ الثَّلَاثَةِ وَأَثَرِ كُلٍّ.',
          src: 'دَفْتَرُ العَقِيدَة.',
          p: ['تَعْرِيفُ كُلِّ قِسْمٍ مِنَ الحِفْظ.',
              'دَلِيلٌ قُرْآنِيٌّ لِكُلٍّ.',
              'أَثَرٌ تَطْبِيقِيٌّ يَوْمِيٌّ.',
              'دَوِّنْ مَا التَبَسَ.'],
          d: 'بِطَاقَةُ أَقْسَامٍ مِنَ الحِفْظِ + نُقَاطُ غُمُوضٍ.',
          cl: 'الشَّهْرُ ٢ يَتَعَمَّقُ فِي الأَسْمَاءِ وَالصِّفَات.' }),

      D(26, 'revise', 'seerah',
        { t: 'Seerah timeline · pre-Islam to childhood', s: SLOTS.morning,
          o: 'Draw a clean timeline from Aamul-Fil through the Prophet\'s twentieth year of life.',
          src: 'Your seerah notes from days 6, 13, 20.',
          p: ['Draw a horizontal timeline with five anchor events.',
              'Mark his age at each.',
              'Add one trait formed at each stage.',
              'Reflect on which trait you most want to imitate this month.'],
          d: 'A one-page seerah timeline in your notebook.',
          cl: 'Month 2 covers Quraysh and early prophethood.' },
        { t: 'الخَطُّ الزَّمَنِيُّ لِلسِّيرَةِ · الجَاهِلِيَّةُ إِلَى الطُّفُولَة', s: SLOTS.morningAr,
          o: 'اِرْسُمْ خَطًّا زَمَنِيًّا مِنْ عَامِ الفِيلِ إِلَى الثَّانِيَةِ وَالعِشْرِينَ مِنْ عُمْرِهِ ﷺ.',
          src: 'مُلَاحَظَاتُكَ مِنْ ٦، ١٣، ٢٠.',
          p: ['خَطٌّ أُفُقِيٌّ بِخَمْسَةِ أَحْدَاثٍ.',
              'سِنُّهُ ﷺ عِنْدَ كُلِّ حَدَث.',
              'سِمَةٌ تَكَوَّنَتْ فِي كُلِّ مَرْحَلَة.',
              'سِمَةٌ تُرِيدُ مُحَاكَاتَهَا هَذَا الشَّهْر.'],
          d: 'خَطٌّ زَمَنِيٌّ مِنْ صَفْحَةٍ.',
          cl: 'الشَّهْرُ ٢ قُرَيْشٌ وَبَدْءُ النُّبُوَّة.' }),

      D(27, 'revise', 'quran',
        { t: 'Full surah recitation · Al-Mulk 1–20 in salah', s: SLOTS.quran,
          o: 'Recite the entire memorised portion in tonight\'s Esha or Tahajjud without prompts.',
          src: 'Memory only.',
          p: ['Make a fresh wudu before Esha.',
              'In the first rak\'ah of Esha, recite Al-Mulk 1–10.',
              'In the second, recite 11–20.',
              'Make dua afterwards thanking Allah for the memorisation.'],
          d: 'Full memorised portion recited in salah without a single mistake.',
          cl: 'Day 28 is the cumulative quiz across all 6 sub-disciplines.' },
        { t: 'تَلَاوَةُ المُلْك ١–٢٠ فِي الصَّلَاة', s: SLOTS.quranAr,
          o: 'اُتْلِ المَحْفُوظَ كُلَّهُ فِي العِشَاءِ أَوِ التَّهَجُّدِ بِلَا تَلْقِين.',
          src: 'مِنَ الحِفْظِ فَقَط.',
          p: ['وُضُوءٌ طَرِيّ.',
              'الرَّكْعَةُ الأُولَى: ١–١٠.',
              'الرَّكْعَةُ الثَّانِيَة: ١١–٢٠.',
              'دُعَاءُ الشُّكْرِ بَعْدَ السَّلَام.'],
          d: 'تَلَاوَةٌ كَامِلَةٌ فِي الصَّلَاةِ بِلَا خَطَإ.',
          cl: 'اليَوْمُ ٢٨ اِمْتِحَانٌ تَرَاكُمِيّ.' }),

      D(28, 'revise', 'revise',
        { t: 'Cumulative quiz · all six sub-disciplines', s: SLOTS.review,
          o: 'In one sitting, prove to yourself you can still produce content from each of the six sub-disciplines.',
          src: 'Your six notebook sections.',
          p: ['Recite Al-Mulk 1–20.',
              'Summarise the three themes of As-Sa\'di on Al-Mulk.',
              'Recite Nawawi 1, 2, 3.',
              'List the six wudu fards + define tahara.',
              'Define the three tawhid categories with one evidence each.',
              'Walk the seerah timeline orally.'],
          d: 'A six-line scorecard self-graded "kept / slipped / lost" per sub-discipline.',
          cl: 'Day 29 is reflection; day 30 sets intention for month 2.' },
        { t: 'اِمْتِحَانٌ تَرَاكُمِيٌّ · السِّتَّةُ كُلُّهَا', s: SLOTS.reviewAr,
          o: 'فِي جَلْسَةٍ وَاحِدَةٍ، أَثْبِتْ لِنَفْسِكَ أَنَّكَ تُنْتِجُ مِنْ كُلِّ بَابٍ.',
          src: 'دَفَاتِرُكَ السِّتَّة.',
          p: ['تَلَاوَةُ المُلْك ١–٢٠.',
              'تَلْخِيصُ ثَلَاثَةِ مَوَاضِيعَ مِنَ التَّفْسِير.',
              'تَلَاوَةُ النَّوَوِيَّاتِ ١، ٢، ٣.',
              'فَرَائِضُ الوُضُوءِ وَتَعْرِيفُ الطَّهَارَة.',
              'أَقْسَامُ التَّوْحِيدِ بِأَدِلَّتِهَا.',
              'الخَطُّ الزَّمَنِيُّ شَفَوِيًّا.'],
          d: 'بِطَاقَةُ تَقْيِيمٍ مِنْ سِتَّةِ سُطُورٍ.',
          cl: 'اليَوْمُ ٢٩ تَأَمُّلٌ، اليَوْمُ ٣٠ نِيَّةٌ لِلشَّهْرِ ٢.' }),

      D(29, 'revise', 'revise',
        { t: 'Personal reflection · what changed in you this month', s: SLOTS.review,
          o: 'Write a two-page reflection on the inner shifts this month — what habits emerged, what struggles repeated.',
          src: 'Pen + notebook only · no devices.',
          p: ['Sit alone for 30 minutes with no phone.',
              'Write what you notice about your taqwa, your salah, your patience this month.',
              'Note one prayer du\'a Allah answered.',
              'Note one du\'a still outstanding that you renew tonight.'],
          d: 'Two pages of personal reflection in your notebook.',
          cl: 'Day 30 sets the niyyah for month 2.' },
        { t: 'تَأَمُّلٌ شَخْصِيٌّ · مَا الَّذِي تَغَيَّرَ', s: SLOTS.reviewAr,
          o: 'اِكْتُبْ صَفْحَتَيْنِ عَنْ تَحَوُّلَاتِكَ الدَّاخِلِيَّةَ هَذَا الشَّهْر.',
          src: 'قَلَمٌ وَدَفْتَرٌ فَقَط.',
          p: ['اِجْلِسْ وَحْدَكَ ثَلَاثِينَ دَقِيقَةً بِلَا جِهَاز.',
              'اُكْتُبْ مَا لَاحَظْتَ فِي تَقْوَاكَ وَصَلَاتِكَ وَصَبْرِك.',
              'اُذْكُرْ دُعَاءً اسْتَجَابَهُ اللَّهُ هَذَا الشَّهْر.',
              'اُذْكُرْ دُعَاءً تُجَدِّدُهُ اللَّيْلَة.'],
          d: 'صَفْحَتَانِ مِنَ التَّأَمُّلِ فِي دَفْتَرِك.',
          cl: 'اليَوْمُ ٣٠ نِيَّةُ الشَّهْرِ ٢.' }),

      D(30, 'revise', 'revise',
        { t: 'Intention reset · ready the heart for month 2', s: SLOTS.review,
          o: 'Make a fresh, written niyyah for month 2 and set one concrete deliverable for each sub-discipline.',
          src: 'Pen + notebook + your month 2 focus list.',
          p: ['Write a fresh niyyah for the next 30 days, dated.',
              'Set one concrete deliverable per sub-discipline (Quran ayaat, hadith count, fiqh chapter, etc.).',
              'Pray two rak\'ah of salat al-hajah asking Allah for tawfiq.',
              'Sleep early — month 2 starts at Fajr.'],
          d: 'A dated niyyah + six deliverables ready for tomorrow morning.',
          cl: 'Month 2 begins with Al-Qalam and Nawawi #4.',
          dua: 'O Allah, accept the past and bless the next.' },
        { t: 'تَجْدِيدُ النِّيَّةِ لِلشَّهْرِ ٢', s: SLOTS.reviewAr,
          o: 'اِكْتُبْ نِيَّةً جَدِيدَةً لِلشَّهْرِ ٢ مَعَ بَنْدٍ مُحَدَّدٍ لِكُلِّ بَابٍ.',
          src: 'قَلَمٌ + دَفْتَرٌ + قَائِمَةُ الشَّهْرِ ٢.',
          p: ['اُكْتُبْ نِيَّةً مَكْتُوبَةً مُؤَرَّخَةً.',
              'بَنْدٌ مُحَدَّدٌ لِكُلِّ بَابٍ مِنَ السِّتَّة.',
              'صَلِّ رَكْعَتَيِ الحَاجَةِ سَائِلًا التَّوْفِيق.',
              'نَمْ مُبَكِّرًا — الشَّهْرُ ٢ يَبْدَأُ فِي الفَجْر.'],
          d: 'نِيَّةٌ مُؤَرَّخَةٌ + سِتَّةُ بُنُودٍ جَاهِزَةٌ لِلصَّبَاح.',
          cl: 'الشَّهْرُ ٢ يَبْدَأُ بِالقَلَمِ وَالنَّوَوِيَّةِ ٤.',
          dua: 'اللَّهُمَّ تَقَبَّلْ مَا مَضَى وَبَارِكْ فِيمَا يَأْتِي.' })
    ]
  });

  // Attach to global SYLLABUS_DATA
  if (window.SYLLABUS_DATA && typeof window.SYLLABUS_DATA.attachMonths === 'function') {
    window.SYLLABUS_DATA.attachMonths('deen', DEEN_MONTHS);
  }
  // Expose for the next files to extend
  window.__SYLLABUS_DEEN_MONTHS = DEEN_MONTHS;
})();
