/* eslint-disable */
// Software Engineering track · 12 months × 30 days · EN + AR
// Rotation: Backend(1) AI(2) DevOps(3) SecOps(4) Frontend(5) Build(6) Ship(7) → repeat
// Days 1-20: learn (cycles of 7 + extra learn days)
// Days 21-30: cumulative revision + build/ship

(function () {
  function D(num, phase, sub, en, ar) {
    var d = {
      num: num, phase: phase, sub: sub,
      topic: en.t, slot: en.s, objective: en.o, source: en.src,
      plan: en.p, deliverable: en.d, crossLink: en.cl, dua: en.dua
    };
    if (ar) {
      d.topicAr = ar.t; d.slotAr = ar.s; d.objectiveAr = ar.o; d.sourceAr = ar.src;
      d.planAr = ar.p; d.deliverableAr = ar.d; d.crossLinkAr = ar.cl; d.duaAr = ar.dua;
    }
    return d;
  }

  var SLOTS = {
    weekday:    'Mon-Fri 10:00–11:00 AM (office self-learn slot)',
    weekdayAr:  'الِاثْنَيْن–الجُمُعَة ١٠:٠٠–١١:٠٠ صَبَاحًا (تَعَلُّمٌ ذَاتِيٌّ بِالمَكْتَبِ)',
    satBuild:   'Sat 9:00 AM–12:00 PM (heavy build block)',
    satBuildAr: 'السَّبْت ٩:٠٠–١٢:٠٠ صَبَاحًا (كُتْلَةُ البِنَاءِ الكَبِيرَةِ)',
    satDeep:    'Sat 2:30–5:00 PM (self-learn deep block)',
    satDeepAr:  'السَّبْت ٢:٣٠–٥:٠٠ مَسَاءً (كُتْلَةُ التَّعَلُّمِ العَمِيقَةِ)',
    sun:        'Sun 9:00 AM–1:00 PM (ship block) + 3:00–5:00 PM weekly review',
    sunAr:      'الأَحَد ٩:٠٠–١:٠٠ مَسَاءً (نَشْرٌ) + ٣:٠٠–٥:٠٠ مُرَاجَعَةٌ أُسْبُوعِيَّةٌ'
  };

  var SE_MONTHS = [];

  // ═════════════════════════════════════════════════════════════
  // MONTH 1 — Foundations
  // ═════════════════════════════════════════════════════════════
  SE_MONTHS.push({
    num: '01',
    tabLabel: 'Foundations',
    tabLabelAr: 'الأُسُس',
    theme: 'Open the books, install the tools, plant the flag.',
    themeAr: 'افْتَحِ الكُتُبَ، نَصِّبِ الأَدَوَاتِ، اِغْرِزِ الرَّايَةَ.',
    thesis: 'Every discipline gets its first chapter. By Day 21 you have touched all five plus a Build day and a Ship day.',
    thesisAr: 'كُلُّ تَخَصُّصٍ يَأْخُذُ فَصْلَهُ الأَوَّلَ. بِحُلُولِ اليَوْمِ ٢١ سَتَكُونُ قَدْ لَامَسْتَ الخَمْسَةَ كُلَّهَا.',
    focus: {
      backend:  'DDIA Ch 1 · Reliable, Scalable, Maintainable',
      backendAr: 'DDIA الفَصْل ١ · المَوْثُوقِيَّةُ وَالقَابِلِيَّةُ لِلتَّوَسُّعِ وَالصِّيَانَةُ',
      ai:       'Anthropic API basics · first request to claude-opus-4-7',
      aiAr:     'أَسَاسِيَّاتُ Anthropic API · أَوَّلُ طَلَبٍ',
      devops:   'Docker · containers, Dockerfile, docker-compose',
      devopsAr: 'دُوكَر · الحَاوِيَات، Dockerfile، docker-compose',
      secops:   'OWASP Top 10 · the contemporary list',
      secopsAr: 'قَائِمَةُ OWASP العَشْرُ',
      frontend: 'Modern CSS · Grid, Flexbox, container queries, :has()',
      frontendAr: 'CSS الحَدِيثَةُ · Grid وَFlexbox',
      build:    'prophetic-stack-saas repo init · README v0.1 · Hello World deployed',
      buildAr:  'تَهْيِئَةُ المُسْتَوْدَعِ + README + Hello World',
      ship:     '"Kicking off 12 months in public" blog post + LinkedIn pin',
      shipAr:   'مَنْشُورٌ افْتِتَاحِيٌّ + تَثْبِيتٌ عَلَى LinkedIn'
    },
    days: [
      D(1, 'learn', 'backend',
        { t: 'DDIA Ch 1 · Reliable, Scalable, Maintainable Applications', s: SLOTS.weekday,
          o: 'Read DDIA Chapter 1 and note three real-world systems exhibiting each of the three properties.',
          src: 'Designing Data-Intensive Applications (Kleppmann) · Ch 1 · pp. 1-22.',
          p: ['Read Ch 1 in one sitting (approx. 50 min).',
              'Identify three systems you have used or built that exemplify reliability, scalability, maintainability.',
              'Write a one-paragraph distillation of each property.',
              'Note one open question to revisit in Ch 2.'],
          d: 'A one-page notebook entry with the three properties and your three example systems.',
          cl: 'Day 8 will read DDIA Ch 2 (Data Models).' },
        { t: 'DDIA الفَصْل ١ · تَطْبِيقَاتٌ مَوْثُوقَةٌ قَابِلَةٌ لِلتَّوَسُّعِ', s: SLOTS.weekdayAr,
          o: 'اِقْرَأِ الفَصْلَ الأَوَّلَ وَدَوِّنْ ثَلَاثَةَ أَنْظِمَةٍ تُمَثِّلُ كُلَّ خَاصِّيَّةٍ.',
          src: 'تَصْمِيمُ تَطْبِيقَاتِ البَيَانَاتِ المُكَثَّفَةِ · الفَصْل ١.',
          p: ['اِقْرَأِ الفَصْلَ فِي جَلْسَةٍ.',
              'ثَلَاثَةُ أَنْظِمَةٍ لِكُلِّ خَاصِّيَّةٍ.',
              'فِقْرَةٌ مُكَثَّفَةٌ لِكُلٍّ.',
              'سُؤَالٌ مَفْتُوحٌ لِلْفَصْلِ ٢.'],
          d: 'صَفْحَةُ مُلَاحَظَاتٍ.',
          cl: 'اليَوْمُ ٨ الفَصْل ٢.' }),

      D(2, 'learn', 'ai',
        { t: 'Anthropic API basics · first request to claude-opus-4-7', s: SLOTS.weekday,
          o: 'Set up an Anthropic API key and send your first messages request, returning a response.',
          src: 'Anthropic API docs · Getting Started · docs.anthropic.com.',
          p: ['Create an Anthropic account and API key.',
              'Install the official SDK (Python or TypeScript).',
              'Write a 20-line script that sends a messages request to claude-opus-4-7.',
              'Commit the script to a new repo prophetic-stack-ai-lab.'],
          d: 'A committed script + console output of the first response.',
          cl: 'Day 9 covers tool use; Day 16 covers RAG.' },
        { t: 'أَسَاسِيَّاتُ Anthropic API · أَوَّلُ طَلَبٍ', s: SLOTS.weekdayAr,
          o: 'هَيِّئِ المِفْتَاحَ وَأَرْسِلْ أَوَّلَ طَلَبٍ.',
          src: 'وَثَائِقُ Anthropic.',
          p: ['أَنْشِئْ مِفْتَاحًا.',
              'نَصِّبِ SDK.',
              'سِكْرِبْتُ ٢٠ سَطْرًا.',
              'اِحْفَظْهُ فِي مُسْتَوْدَعٍ جَدِيدٍ.'],
          d: 'سِكْرِبْتٌ + خَرْجٌ.',
          cl: 'اليَوْمُ ٩ اِسْتِخْدَامُ الأَدَوَات.' }),

      D(3, 'learn', 'devops',
        { t: 'Docker · containers, Dockerfile, docker-compose', s: SLOTS.weekday,
          o: 'Install Docker, write a Dockerfile for a small Laravel app, and bring up the stack with docker-compose.',
          src: 'Docker docs · "Get Started" + Maximilian Schwarzmüller Docker course Ch 1.',
          p: ['Install Docker Desktop.',
              'Write a Dockerfile for a minimal Laravel + PHP-FPM image.',
              'Write a docker-compose.yml with Laravel + Postgres + Redis services.',
              'Run "docker-compose up" and verify all three start cleanly.'],
          d: 'A working docker-compose.yml committed to the repo.',
          cl: 'Day 10 covers AWS SAA Compute + Storage.' },
        { t: 'دُوكَر · حَاوِيَاتٌ وَcompose', s: SLOTS.weekdayAr,
          o: 'نَصِّبْ Docker وَأَطْلِقْ Laravel + Postgres + Redis.',
          src: 'وَثَائِقُ Docker.',
          p: ['تَثْبِيتُ Docker Desktop.',
              'Dockerfile لِـLaravel.',
              'docker-compose.yml.',
              'تَشْغِيلٌ نَظِيفٌ.'],
          d: 'docker-compose.yml.',
          cl: 'اليَوْمُ ١٠ AWS Compute.' }),

      D(4, 'learn', 'secops',
        { t: 'OWASP Top 10 (2021) · the contemporary list', s: SLOTS.weekday,
          o: 'Read the OWASP Top 10 (2021) and identify which two apply most directly to your current SaaS.',
          src: 'owasp.org/Top10 · A01 through A10.',
          p: ['Read the summary of each of A01–A10.',
              'For each, note one concrete attack scenario.',
              'Identify the two most relevant to your stack (likely A01 Broken Access Control and A03 Injection).',
              'Note one mitigation per identified risk.'],
          d: 'A two-page summary with the ten + two flagged risks + mitigations.',
          cl: 'Day 11 covers AuthN/AuthZ deep.' },
        { t: 'قَائِمَةُ OWASP العَشْرُ', s: SLOTS.weekdayAr,
          o: 'اِقْرَأِ القَائِمَةَ وَحَدِّدِ الِاثْنَتَيْنِ الأَهَمَّ لِنِظَامِكَ.',
          src: 'owasp.org/Top10.',
          p: ['اِقْرَأْ كُلَّ بَنْدٍ.',
              'سِينَارِيُو هُجُومٍ لِكُلٍّ.',
              'حَدِّدِ الِاثْنَتَيْنِ.',
              'مُعَالَجَةٌ لِكُلٍّ.'],
          d: 'مُلَخَّصٌ.',
          cl: 'اليَوْمُ ١١ المُصَادَقَةُ.' }),

      D(5, 'learn', 'frontend',
        { t: 'Modern CSS · Grid, Flexbox, container queries, :has()', s: SLOTS.weekday,
          o: 'Refresh modern CSS layout primitives and rebuild your portfolio hero with Grid only.',
          src: 'Kevin Powell · CSS Grid playlist · or web.dev/learn/css.',
          p: ['Watch Kevin Powell\'s Grid intro (40 min).',
              'Read the MDN page on Container Queries.',
              'Read the MDN page on :has().',
              'Rebuild your portfolio hero using Grid + Flexbox combined.'],
          d: 'A committed Grid-only hero rebuild.',
          cl: 'Day 12 covers TypeScript.' },
        { t: 'CSS الحَدِيثَةُ', s: SLOTS.weekdayAr,
          o: 'أَعِدْ بِنَاءَ الهِيرُو بِـGrid.', src: 'Kevin Powell + MDN.',
          p: ['Grid.', 'Container Queries.', ':has().', 'إِعَادَةُ بِنَاءٍ.'],
          d: 'هِيرُو جَدِيدٌ.', cl: 'اليَوْمُ ١٢ TypeScript.' }),

      D(6, 'build', 'build',
        { t: 'Build day · prophetic-stack-saas repo + initial scaffold', s: SLOTS.satBuild,
          o: 'Create the GitHub repository, write README v0.1, and stand up a "Hello World" Laravel app with Docker.',
          src: 'Your GitHub + your terminal.',
          p: ['Create public GitHub repo: prophetic-stack-saas.',
              'Write README v0.1 with mission, stack, and 6-month direction.',
              'Drop in the Dockerfile + docker-compose.yml from Day 3.',
              'Push a tag v0.0.1 marking the start.'],
          d: 'A public repo with a tagged v0.0.1.', cl: 'Day 7 ships the announcement post.' },
        { t: 'يَوْمُ البِنَاءِ · المُسْتَوْدَعُ', s: SLOTS.satBuildAr,
          o: 'أَنْشِئْ مُسْتَوْدَعَ GitHub وَ"Hello World".', src: 'GitHub.',
          p: ['مُسْتَوْدَعٌ عَامٌّ.', 'README ٠٫١.', 'Dockerfile + compose.', 'وَسْمُ v0.0.1.'],
          d: 'مُسْتَوْدَعٌ مَوْسُومٌ.', cl: 'اليَوْمُ ٧ النَّشْرُ.' }),

      D(7, 'ship', 'ship',
        { t: 'Ship day · "Kicking off 12 months in public"', s: SLOTS.sun,
          o: 'Publish the kicking-off blog post and pin it to your LinkedIn featured section.',
          src: 'Your blog + LinkedIn.',
          p: ['Draft a 600-word post: why, what, the public artifact.',
              'Edit for one pass.',
              'Publish to your blog.',
              'Pin to LinkedIn featured + share with a 200-character summary.'],
          d: 'A published post + pinned LinkedIn entry.', cl: 'Cycle 2 begins Day 8.' },
        { t: 'يَوْمُ النَّشْرِ · افْتِتَاحِيَّةُ السَّنَةِ', s: SLOTS.sunAr,
          o: 'اِنْشُرِ المَقَالَ الأَوَّلَ وَثَبِّتْهُ.', src: 'المُدَوَّنَةُ.',
          p: ['مُسَوَّدَةُ ٦٠٠ كَلِمَةٍ.', 'تَحْرِيرٌ.', 'نَشْرٌ.', 'تَثْبِيتٌ.'],
          d: 'مَنْشُورٌ مُثَبَّتٌ.', cl: 'الدَّوْرَةُ ٢.' }),

      // Cycle 2 (Days 8-14)
      D(8, 'learn', 'backend',
        { t: 'DDIA Ch 2 · Data Models and Query Languages', s: SLOTS.weekday,
          o: 'Read DDIA Ch 2 and compare relational vs document vs graph for one workload you actually have.',
          src: 'DDIA Ch 2 · pp. 23-65.',
          p: ['Read Ch 2 in one sitting.',
              'Pick one current workload (e.g., users + their hifz progress).',
              'Sketch it in each model: relational, document, graph.',
              'Pick the best fit with three sentences of justification.'],
          d: 'A three-model sketch + a chosen winner.', cl: 'Day 15 covers DDIA Ch 3.' },
        { t: 'DDIA الفَصْل ٢ · نَمَاذِجُ البَيَانَاتِ', s: SLOTS.weekdayAr,
          o: 'قَارِنْ بَيْنَ النَّمَاذِجِ لِحِمْلٍ حَقِيقِيٍّ.', src: 'DDIA الفَصْل ٢.',
          p: ['اِقْرَأِ الفَصْلَ.', 'حِمْلٌ حَقِيقِيٌّ.', 'ثَلَاثَةُ رَسْمَاتٍ.', 'مُبَرَّرٌ.'],
          d: 'رَسْمَاتٌ.', cl: 'اليَوْمُ ١٥ الفَصْل ٣.' }),

      D(9, 'learn', 'ai',
        { t: 'Anthropic tool use · function calling basics', s: SLOTS.weekday,
          o: 'Make Claude call a tool: define a tool schema and have Claude invoke it with the right arguments.',
          src: 'Anthropic Tool use docs · docs.anthropic.com/en/docs/build-with-claude/tool-use.',
          p: ['Read the tool-use docs.',
              'Define one tool: get_weather(location).',
              'Send a messages request with the tool definition.',
              'Verify Claude returns a tool_use block; mock execute it and feed back the result.'],
          d: 'A working tool-use loop committed.', cl: 'Day 16 covers RAG.' },
        { t: 'اِسْتِخْدَامُ الأَدَوَاتِ · function calling', s: SLOTS.weekdayAr,
          o: 'دَعِ Claude يَسْتَدْعِيَ أَدَاةً.',
          src: 'وَثَائِقُ Anthropic.',
          p: ['اِقْرَأْ.',
              'عَرِّفْ أَدَاةً.',
              'أَرْسِلْ طَلَبًا.',
              'نَفِّذْ مُحَاكَاةً وَأَعِدْ.'],
          d: 'دَوْرَةٌ تَعْمَلُ.', cl: 'اليَوْمُ ١٦ RAG.' }),

      D(10, 'learn', 'devops',
        { t: 'AWS SAA · Compute (EC2) + Storage (EBS, EFS, S3)', s: SLOTS.weekday,
          o: 'Watch one module on EC2 fundamentals and one on storage; take 10 flashcards.',
          src: 'Stephane Maarek AWS SAA course · Compute + Storage modules.',
          p: ['Watch the EC2 module (60 min).',
              'Watch the EBS/EFS/S3 module (60 min).',
              'Make 10 flashcards across both.',
              'Take 5 sample questions from Tutorials Dojo for free.'],
          d: '10 flashcards + 5 sample-question results logged.', cl: 'Day 17 covers VPC.' },
        { t: 'AWS SAA · Compute + Storage', s: SLOTS.weekdayAr,
          o: 'وَحْدَتَانِ + ١٠ بِطَاقَاتٍ.',
          src: 'دَوْرَةُ Maarek.',
          p: ['EC2.', 'EBS/EFS/S3.', '١٠ بِطَاقَاتٍ.', '٥ أَسْئِلَةٍ.'],
          d: 'بِطَاقَاتٌ.', cl: 'اليَوْمُ ١٧ VPC.' }),

      D(11, 'learn', 'secops',
        { t: 'AuthN/AuthZ deep · JWT, OAuth 2.0, OIDC', s: SLOTS.weekday,
          o: 'Distinguish authentication from authorization and understand the JWT/OAuth/OIDC trio.',
          src: 'auth0.com/intro-to-iam + RFC 6749 (skim) + Okta OIDC primer.',
          p: ['Read the IAM primer.',
              'Note JWT structure (header.payload.signature) and signing.',
              'Note OAuth 2.0 flows (auth code, client credentials, device).',
              'Note OIDC as identity layer on top of OAuth.'],
          d: 'A diagram of the JWT/OAuth/OIDC relationship.', cl: 'Day 18 covers container security.' },
        { t: 'المُصَادَقَةُ وَالتَّفْوِيضُ', s: SLOTS.weekdayAr,
          o: 'JWT + OAuth + OIDC.',
          src: 'auth0 + RFC 6749.',
          p: ['التَّمْيِيزُ.', 'بِنْيَةُ JWT.', 'تَدَفُّقَاتُ OAuth.', 'OIDC.'],
          d: 'مُخَطَّطٌ.', cl: 'اليَوْمُ ١٨ أَمْنُ الحَاوِيَاتِ.' }),

      D(12, 'learn', 'frontend',
        { t: 'TypeScript fundamentals · types, generics, utility types', s: SLOTS.weekday,
          o: 'Cover TypeScript fundamentals fast and convert one small JS file to TS.',
          src: 'TypeScript Handbook · "Everyday Types" + "Generics".',
          p: ['Read Everyday Types.',
              'Read Generics.',
              'Pick one .js file in your portfolio repo.',
              'Convert it to .ts with proper types.'],
          d: 'One file converted to TS and committed.', cl: 'Day 19 covers React fundamentals.' },
        { t: 'أَسَاسِيَّاتُ TypeScript', s: SLOTS.weekdayAr,
          o: 'حَوِّلْ مَلَفًّا إِلَى TS.', src: 'TypeScript Handbook.',
          p: ['Everyday Types.', 'Generics.', 'مَلَفٌّ.', 'تَحْوِيلٌ.'],
          d: 'مَلَفٌّ مُحَوَّلٌ.', cl: 'اليَوْمُ ١٩ React.' }),

      D(13, 'build', 'build',
        { t: 'Build day · scaffold the multi-tenant base', s: SLOTS.satBuild,
          o: 'Install Laravel, scaffold a basic multi-tenant pattern using row-level scoping.',
          src: 'Laravel docs + stancl/tenancy or your own scaffolding.',
          p: ['composer create-project laravel/laravel saas.',
              'Add a tenant_id column to the users table.',
              'Write a global scope that filters by tenant_id.',
              'Commit and push.'],
          d: 'A tenant-scoped Laravel scaffold committed.', cl: 'Day 14 ships about it.' },
        { t: 'سِقَالَةُ التَّعَدُّدِيَّةِ', s: SLOTS.satBuildAr,
          o: 'سِقَالَةٌ بِنِطَاقٍ عَلَى مُسْتَوَى الصَّفِّ.', src: 'Laravel.',
          p: ['create-project.', 'tenant_id.', 'GlobalScope.', 'Push.'],
          d: 'سِقَالَةٌ.', cl: 'اليَوْمُ ١٤ نَشْرٌ.' }),

      D(14, 'ship', 'ship',
        { t: 'Ship day · "How I scaffolded multi-tenancy on day 14"', s: SLOTS.sun,
          o: 'Publish a 600-word post on the tenant-scoping approach with code snippets.',
          src: 'Your blog.',
          p: ['Draft 600 words.', 'Add two code snippets.', 'Publish.', 'Share on LinkedIn.'],
          d: 'A second public post.', cl: 'Cycle 3 begins Day 15.' },
        { t: 'مَنْشُورٌ ثَانٍ', s: SLOTS.sunAr,
          o: 'تَوْثِيقُ السِّقَالَةِ.', src: 'المُدَوَّنَةُ.',
          p: ['٦٠٠ كَلِمَةٍ.', 'مَقْطَعَا كُودٍ.', 'نَشْرٌ.', 'LinkedIn.'],
          d: 'مَنْشُورٌ.', cl: 'الدَّوْرَةُ ٣.' }),

      // Cycle 3 (Days 15-21)
      D(15, 'learn', 'backend',
        { t: 'DDIA Ch 3 · Storage and Retrieval (B-trees vs LSM)', s: SLOTS.weekday,
          o: 'Understand the two main storage engine families and their trade-offs.',
          src: 'DDIA Ch 3 · pp. 69-103.',
          p: ['Read Ch 3.',
              'Note B-tree characteristics (Postgres, MySQL).',
              'Note LSM-tree characteristics (Cassandra, RocksDB).',
              'Pick the right engine family for two workloads (transactional vs time-series).'],
          d: 'A trade-off table B-tree vs LSM.', cl: 'Day 22 reviews backend.' },
        { t: 'DDIA الفَصْل ٣ · التَّخْزِينُ وَالاسْتِرْجَاعُ', s: SLOTS.weekdayAr,
          o: 'B-tree مُقَابِلَ LSM.', src: 'DDIA الفَصْل ٣.',
          p: ['اِقْرَأْ.', 'B-tree.', 'LSM.', 'حِمْلَانِ.'],
          d: 'جَدْوَلُ مُقَايَضَاتٍ.', cl: 'اليَوْمُ ٢٢.' }),

      D(16, 'learn', 'ai',
        { t: 'RAG · retrieval-augmented generation basics', s: SLOTS.weekday,
          o: 'Build a tiny RAG: embed three documents, store, retrieve, and feed Claude for grounded answers.',
          src: 'Anthropic RAG cookbook + a simple embeddings library.',
          p: ['Pick three of your blog posts as documents.',
              'Chunk + embed each (use sentence-transformers locally or OpenAI/Voyage embeddings).',
              'Store embeddings in a JSON or sqlite vector table.',
              'On a user query, retrieve top-2 chunks and inject into the Claude prompt.'],
          d: 'A working tiny-RAG script.', cl: 'Day 23 reviews AI.' },
        { t: 'RAG · أَسَاسِيَّاتُ التَّوْلِيدِ بِالاسْتِرْجَاعِ', s: SLOTS.weekdayAr,
          o: 'RAG مُصَغَّرٌ.', src: 'Anthropic cookbook.',
          p: ['ثَلَاثُ وَثَائِقَ.', 'تَجْزِئَةٌ + تَضْمِينٌ.', 'تَخْزِينٌ.', 'اِسْتِرْجَاعٌ + حَقْنٌ.'],
          d: 'سِكْرِبْتٌ.', cl: 'اليَوْمُ ٢٣.' }),

      D(17, 'learn', 'devops',
        { t: 'AWS SAA · Networking (VPC, subnets, SG, NAT)', s: SLOTS.weekday,
          o: 'Understand VPC architecture: subnets (public/private), security groups, NACLs, NAT gateways.',
          src: 'Maarek AWS SAA · Networking module.',
          p: ['Watch the VPC module (90 min).',
              'Draw your own three-tier VPC design (web/app/db).',
              'Note SG vs NACL key differences.',
              'Take 10 sample questions on networking.'],
          d: 'A hand-drawn three-tier VPC + 10 question results.', cl: 'Day 24 reviews DevOps.' },
        { t: 'AWS · الشَّبَكَاتُ', s: SLOTS.weekdayAr,
          o: 'VPC ثُلَاثِيَّةُ الطَّبَقَات.', src: 'Maarek.',
          p: ['VPC.', 'رَسْمٌ.', 'SG vs NACL.', '١٠ أَسْئِلَةٍ.'],
          d: 'رَسْمٌ.', cl: 'اليَوْمُ ٢٤.' }),

      D(18, 'learn', 'secops',
        { t: 'Container security · image scanning + runtime', s: SLOTS.weekday,
          o: 'Scan your Docker image for vulnerabilities and learn one runtime hardening technique.',
          src: 'Trivy docs + Docker security docs.',
          p: ['Install Trivy.',
              'Scan your Laravel Dockerfile image.',
              'Note the top three findings.',
              'Apply one hardening (non-root user, drop capabilities).'],
          d: 'A scan report + one hardening applied.', cl: 'Day 25 reviews SecOps.' },
        { t: 'أَمْنُ الحَاوِيَاتِ', s: SLOTS.weekdayAr,
          o: 'فَحْصٌ + تَقْسِيَةٌ.', src: 'Trivy.',
          p: ['تَثْبِيتُ Trivy.', 'فَحْصٌ.', 'الأَوَّلُ ٣.', 'تَقْسِيَةٌ.'],
          d: 'فَحْصٌ + تَقْسِيَةٌ.', cl: 'اليَوْمُ ٢٥.' }),

      D(19, 'learn', 'frontend',
        { t: 'React fundamentals · components, hooks, state', s: SLOTS.weekday,
          o: 'Build a small React component that uses useState + useEffect to fetch from your API.',
          src: 'React docs · "Learn React" Ch 1-4.',
          p: ['Read Ch 1-4 of the React docs.',
              'Create a Vite + React + TS project.',
              'Build a component that calls your /api/users endpoint.',
              'Render a list and a loading state.'],
          d: 'A working React component committed.', cl: 'Day 26 reviews frontend.' },
        { t: 'أَسَاسِيَّاتُ React', s: SLOTS.weekdayAr,
          o: 'مُكَوِّنٌ يَجْلِبُ.', src: 'وَثَائِقُ React.',
          p: ['الفُصُول ١-٤.', 'مَشْرُوعُ Vite.', 'مُكَوِّنٌ يَجْلِبُ.', 'قَائِمَةٌ + تَحْمِيلٌ.'],
          d: 'مُكَوِّنٌ.', cl: 'اليَوْمُ ٢٦.' }),

      D(20, 'build', 'build',
        { t: 'Build day · auth on the SaaS', s: SLOTS.satBuild,
          o: 'Add a basic JWT-based authentication to your Laravel SaaS.',
          src: 'tymon/jwt-auth or Laravel Sanctum.',
          p: ['Install Sanctum.',
              'Add /api/register and /api/login routes.',
              'Issue a token on login.',
              'Test with curl or HTTPie.'],
          d: 'Working register + login + token issuance.', cl: 'Day 21 ships about it.' },
        { t: 'مُصَادَقَةٌ JWT', s: SLOTS.satBuildAr,
          o: 'تَسْجِيلٌ وَدُخُولٌ + رَمْزٌ.', src: 'Sanctum.',
          p: ['تَثْبِيتٌ.', 'مَسَارَانِ.', 'إِصْدَارُ رَمْزٍ.', 'اِخْتِبَارٌ.'],
          d: 'مُصَادَقَةٌ.', cl: 'اليَوْمُ ٢١ نَشْرٌ.' }),

      // Days 21-30: Revision + Ship
      D(21, 'revise', 'ship',
        { t: 'Ship day · "Three weeks in: tenancy + auth"', s: SLOTS.sun,
          o: 'Publish a third post summarising the first three weeks of the syllabus.',
          src: 'Your blog.',
          p: ['Draft 700 words.', 'Add screenshots of the working app.', 'Publish.', 'Share on LinkedIn.'],
          d: 'A third post out.', cl: 'Day 22 begins revision.' },
        { t: 'مَنْشُورُ ثَلَاثَةِ أَسَابِيع', s: SLOTS.sunAr,
          o: '٧٠٠ كَلِمَةٍ.', src: 'المُدَوَّنَةُ.',
          p: ['٧٠٠.', 'صُوَرٌ.', 'نَشْرٌ.', 'LinkedIn.'],
          d: 'مَنْشُورٌ.', cl: 'اليَوْمُ ٢٢ مُرَاجَعَةٌ.' }),

      D(22, 'revise', 'backend',
        { t: 'Backend revision · DDIA Ch 1-3 consolidation', s: SLOTS.weekday,
          o: 'Re-read your DDIA notes from Days 1, 8, 15 and write one summary doc.',
          src: 'Your DDIA notebook pages.',
          p: ['Re-read all three chapter notes.',
              'Write a 500-word summary that ties them together.',
              'Identify which chapter you struggled with most.',
              'Schedule a re-read.'],
          d: 'A 500-word backend summary.', cl: 'Month 2 begins Ch 4-5.' },
        { t: 'مُرَاجَعَةُ DDIA ١-٣', s: SLOTS.weekdayAr,
          o: 'مُلَخَّصٌ مُجَمَّعٌ.', src: 'دَفْتَرُ الخَلْفِيَّةِ.',
          p: ['مُرَاجَعَةٌ.', '٥٠٠ كَلِمَةٍ.', 'الأَصْعَبُ.', 'إِعَادَةُ قِرَاءَةٍ.'],
          d: 'مُلَخَّصٌ.', cl: 'الشَّهْرُ ٢.' }),

      D(23, 'revise', 'ai',
        { t: 'AI revision · API + tool use + RAG together', s: SLOTS.weekday,
          o: 'Build one script that combines all three: a Claude agent with one tool and a tiny RAG.',
          src: 'Your previous scripts.',
          p: ['Combine the scripts from Days 2, 9, 16.',
              'Make a single agent that retrieves and tools.',
              'Test on one realistic question.',
              'Commit as ai-lab/agent-v1.'],
          d: 'A combined agent-v1.', cl: 'Month 2 covers agents deeper.' },
        { t: 'مُرَاجَعَةُ AI', s: SLOTS.weekdayAr,
          o: 'دَمْجُ الثَّلَاثَةِ.', src: 'سَابِقُكَ.',
          p: ['دَمْجٌ.', 'وَكِيلٌ.', 'اِخْتِبَارٌ.', 'commit.'],
          d: 'وَكِيلٌ.', cl: 'الشَّهْرُ ٢.' }),

      D(24, 'revise', 'devops',
        { t: 'DevOps revision · Docker + AWS basics integrated', s: SLOTS.weekday,
          o: 'Tie together Docker (Day 3) and AWS basics (Days 10, 17) by sketching a deployment diagram.',
          src: 'Your DevOps notes.',
          p: ['Sketch your eventual cloud topology.',
              'Mark where Docker images live (ECR).',
              'Mark where containers run (EC2 → eventually K8s).',
              'Note one gap to fill in Month 2.'],
          d: 'A deployment topology sketch.', cl: 'Month 2 covers AWS Networking + DB.' },
        { t: 'مُرَاجَعَةُ DevOps', s: SLOTS.weekdayAr,
          o: 'طُوبُولُوجِيَا نَشْرٍ.', src: 'دَفْتَرُك.',
          p: ['طُوبُولُوجِيَا.', 'ECR.', 'EC2.', 'فَجْوَةٌ.'],
          d: 'رَسْمٌ.', cl: 'الشَّهْرُ ٢.' }),

      D(25, 'revise', 'secops',
        { t: 'SecOps revision · the three threats most likely on your stack', s: SLOTS.weekday,
          o: 'Pick three OWASP categories most likely to hit your SaaS and write mitigation playbooks.',
          src: 'Your OWASP notes.',
          p: ['Re-read OWASP Top 10.',
              'Pick three (A01, A03, A07 likely).',
              'Write a 2-paragraph playbook per category.',
              'File under security/playbooks in the repo.'],
          d: 'Three playbooks committed.', cl: 'Month 2 covers AuthN/AuthZ in depth.' },
        { t: 'مُرَاجَعَةُ SecOps', s: SLOTS.weekdayAr,
          o: 'ثَلَاثُ خُطَطٍ.', src: 'OWASP.',
          p: ['مُرَاجَعَةٌ.', 'ثَلَاثٌ.', 'كِتَابٌ لِكُلٍّ.', 'commit.'],
          d: 'كُتُبٌ.', cl: 'الشَّهْرُ ٢.' }),

      D(26, 'revise', 'frontend',
        { t: 'Frontend revision · the integrated stack', s: SLOTS.weekday,
          o: 'Connect Day 5\'s CSS, Day 12\'s TS, Day 19\'s React into one component.',
          src: 'Your frontend repo.',
          p: ['Take the hero from Day 5.',
              'Rewrite in TS.',
              'Wrap in a React component.',
              'Verify it still works in the portfolio.'],
          d: 'A TS+React hero deployed.', cl: 'Month 2 covers React patterns.' },
        { t: 'مُرَاجَعَةُ الوَاجِهَةِ', s: SLOTS.weekdayAr,
          o: 'دَمْجُ الثَّلَاثَةِ.', src: 'مُسْتَوْدَعُ الوَاجِهَةِ.',
          p: ['الهِيرُو.', 'TS.', 'React.', 'تَأَكُّدٌ.'],
          d: 'مُكَوِّنٌ.', cl: 'الشَّهْرُ ٢.' }),

      D(27, 'build', 'build',
        { t: 'Build day · cross-cutting integration day', s: SLOTS.satBuild,
          o: 'Wire the React frontend (Day 26) to the Laravel auth (Day 20) — one full end-to-end login flow.',
          src: 'Your repo.',
          p: ['Add /api/login support for CORS.',
              'On the React side, build a login form.',
              'Store the JWT in httpOnly cookie.',
              'Test the round-trip.'],
          d: 'A working end-to-end login.', cl: 'Day 28 cumulative test.' },
        { t: 'دَمْجٌ شَامِلٌ', s: SLOTS.satBuildAr,
          o: 'تَسْجِيلُ دُخُولٍ شَامِلٌ.', src: 'المُسْتَوْدَعُ.',
          p: ['CORS.', 'نَمُوذَجٌ.', 'كُوكِيٌّ.', 'اِخْتِبَارٌ.'],
          d: 'دُخُولٌ يَعْمَلُ.', cl: 'اليَوْمُ ٢٨.' }),

      D(28, 'revise', 'revise',
        { t: 'Cumulative quiz · 30-day Month 1 mastery test', s: SLOTS.satDeep,
          o: 'Self-quiz across all five disciplines.',
          src: 'All Month 1 notebooks.',
          p: ['Backend: explain reliable/scalable/maintainable.',
              'AI: list the steps of a tool-use loop.',
              'DevOps: draw the three-tier VPC.',
              'SecOps: list the top 3 OWASP categories you focused on.',
              'Frontend: explain the difference between :has() and parent-selectors.'],
          d: 'A five-line scorecard.', cl: 'Day 29 reflects.' },
        { t: 'اِمْتِحَانُ الشَّهْرِ ١', s: SLOTS.satDeepAr,
          o: 'الخَمْسَةُ كُلُّهَا.', src: 'الدَّفَاتِرُ.',
          p: ['الخَلْفِيَّةُ.', 'AI.', 'DevOps.', 'SecOps.', 'الوَاجِهَةُ.'],
          d: 'بِطَاقَةٌ.', cl: 'اليَوْمُ ٢٩.' }),

      D(29, 'revise', 'revise',
        { t: 'Reflection · what shipped vs what slipped', s: SLOTS.sun,
          o: 'Write a one-page reflection on the month: what shipped, what slipped, what is the bottleneck.',
          src: 'Pen + notebook.',
          p: ['Thirty minutes alone.',
              'List what shipped (artifacts).',
              'List what slipped (overruns, skipped days).',
              'Identify the bottleneck for Month 2.'],
          d: 'A one-page reflection.', cl: 'Day 30 plans Month 2.' },
        { t: 'تَأَمُّلٌ', s: SLOTS.sunAr,
          o: 'مَا نُشِرَ وَمَا تَأَخَّرَ.', src: 'قَلَمٌ.',
          p: ['ثَلَاثُونَ دَقِيقَةً.', 'المَنْشُورُ.', 'المُتَأَخِّرُ.', 'العَائِقُ.'],
          d: 'تَأَمُّلٌ.', cl: 'اليَوْمُ ٣٠.' }),

      D(30, 'revise', 'ship',
        { t: 'Ship day · Month 1 retrospective post + Month 2 niyyah', s: SLOTS.sun,
          o: 'Publish a retrospective post + write a dated commitment for Month 2.',
          src: 'Your blog + notebook.',
          p: ['Draft a 700-word "Month 1 in public" post.',
              'Publish.',
              'Write a dated commitment for Month 2 (DDIA Ch 4-5, AWS SAA Networking + DB, etc.).',
              'Sleep early.'],
          d: 'A retrospective post + Month 2 commitment.', cl: 'Month 2 begins tomorrow.',
          dua: 'O Allah, the first month was a gift; make the second deeper.' },
        { t: 'يَوْمُ النَّشْرِ + نِيَّةُ الشَّهْرِ ٢', s: SLOTS.sunAr,
          o: 'مَنْشُورٌ + نِيَّةٌ.', src: 'المُدَوَّنَةُ.',
          p: ['٧٠٠ كَلِمَةٍ.', 'نَشْرٌ.', 'نِيَّةٌ.', 'نَوْمٌ.'],
          d: 'مَنْشُورٌ + نِيَّةٌ.', cl: 'الشَّهْرُ ٢.',
          dua: 'اللَّهُمَّ اِجْعَلِ الشَّهْرَ الثَّانِيَ أَعْمَقَ.' })
    ]
  });

  // ═════════════════════════════════════════════════════════════
  // MONTH 2 — Cloud, Encoding, Patterns
  // ═════════════════════════════════════════════════════════════
  SE_MONTHS.push({
    num: '02',
    tabLabel: 'Cloud',
    tabLabelAr: 'السَّحَابَةُ',
    theme: 'DDIA Ch 4-5 · AWS networking + databases · OAuth + secrets · React patterns + agents.',
    themeAr: 'DDIA ٤-٥ · شَبَكَاتُ AWS + قَوَاعِدُ بَيَانَاتٍ · OAuth + أَسْرَارٌ · أَنْمَاطُ React.',
    thesis: 'Build the cloud fluency and start patterns deeper than basics.',
    thesisAr: 'بِنَاءُ الطَّلَاقَةِ السَّحَابِيَّةِ وَالأَنْمَاطِ.',
    focus: {
      backend: 'DDIA Ch 4 (Encoding) + Ch 5 (Replication)',
      backendAr: 'DDIA ٤ + ٥',
      ai: 'Agents · multi-step orchestration',
      aiAr: 'الوُكَلَاءُ · التَّنْسِيقُ المُتَعَدِّدُ الخُطُوَاتِ',
      devops: 'AWS SAA · Networking + Databases (RDS, Aurora, DynamoDB)',
      devopsAr: 'AWS · شَبَكَاتٌ وَقَوَاعِدُ بَيَانَاتٍ',
      secops: 'OAuth 2.0 deep + Secrets management',
      secopsAr: 'OAuth + الأَسْرَارُ',
      frontend: 'React patterns · state management + forms',
      frontendAr: 'أَنْمَاطُ React · إِدَارَةُ الحَالَةِ وَالنَّمَاذِجُ',
      build: 'OAuth provider integration + Postgres replication setup',
      buildAr: 'OAuth + نَسْخُ Postgres',
      ship: 'Two posts: "OAuth without tears" + "Reading DDIA Ch 5"',
      shipAr: 'مَنْشُورَانِ'
    },
    days: [
      D(1, 'learn', 'backend',
        { t: 'DDIA Ch 4 · Encoding and Schema Evolution', s: SLOTS.weekday,
          o: 'Understand JSON/Avro/Protobuf trade-offs and how schemas evolve safely over time.',
          src: 'DDIA Ch 4 · pp. 111-150.',
          p: ['Read Ch 4.',
              'Note the three encoding categories.',
              'Note the rules for forward and backward compatibility.',
              'Audit one API of yours for schema-evolution safety.'],
          d: 'A schema-evolution audit of one API.', cl: 'Day 8 covers Ch 5.' },
        { t: 'DDIA ٤ · التَّرْمِيزُ', s: SLOTS.weekdayAr,
          o: 'JSON/Avro/Protobuf.', src: 'DDIA ٤.',
          p: ['اِقْرَأْ.', 'الفِئَاتُ.', 'التَّوَافُقُ.', 'مُحَاسَبَةُ API.'],
          d: 'مُحَاسَبَةٌ.', cl: 'اليَوْمُ ٨.' }),

      D(2, 'learn', 'ai',
        { t: 'Agents · multi-step orchestration', s: SLOTS.weekday,
          o: 'Build a 3-step agent: search → summarise → save.',
          src: 'Anthropic Agents cookbook.',
          p: ['Read the agent patterns docs.',
              'Define three tools.',
              'Let Claude orchestrate them sequentially.',
              'Print the trace.'],
          d: 'A 3-step agent committed.', cl: 'Day 9 covers embeddings.' },
        { t: 'وُكَلَاءُ مُتَعَدِّدُ الخُطُوَاتِ', s: SLOTS.weekdayAr,
          o: 'بَحْثٌ ← تَلْخِيصٌ ← حِفْظٌ.', src: 'Anthropic Agents.',
          p: ['اِقْرَأْ.', 'ثَلَاثُ أَدَوَاتٍ.', 'تَنْسِيقٌ.', 'أَثَرٌ.'],
          d: 'وَكِيلٌ.', cl: 'اليَوْمُ ٩.' }),

      D(3, 'learn', 'devops',
        { t: 'AWS SAA · Databases (RDS, Aurora, DynamoDB)', s: SLOTS.weekday,
          o: 'Watch the database module and understand when to pick which.',
          src: 'Maarek AWS SAA · Databases module.',
          p: ['Watch the module (90 min).',
              'Compare RDS vs Aurora vs DynamoDB on three axes.',
              'Pick the right DB for your SaaS.',
              'Take 10 sample questions.'],
          d: 'A choice + rationale.', cl: 'Day 10 covers networking.' },
        { t: 'قَوَاعِدُ بَيَانَاتِ AWS', s: SLOTS.weekdayAr,
          o: 'RDS vs Aurora vs DynamoDB.', src: 'Maarek.',
          p: ['الوَحْدَةُ.', 'مُقَارَنَةٌ.', 'اِخْتِيَارٌ.', '١٠ أَسْئِلَةٍ.'],
          d: 'اِخْتِيَارٌ.', cl: 'اليَوْمُ ١٠.' }),

      D(4, 'learn', 'secops',
        { t: 'OAuth 2.0 flows · which to use when', s: SLOTS.weekday,
          o: 'Walk through the four main OAuth flows and pick the right one for three scenarios.',
          src: 'auth0 OAuth flow chooser.',
          p: ['Read the flow chooser.',
              'Match three scenarios to flows (SPA, mobile, server-to-server).',
              'Note which is most fragile (implicit, deprecated).',
              'Implement one (auth code with PKCE) in your SaaS plan.'],
          d: 'Three scenarios mapped to flows.', cl: 'Day 11 covers secrets.' },
        { t: 'تَدَفُّقَاتُ OAuth', s: SLOTS.weekdayAr,
          o: 'الأَرْبَعَةُ + ثَلَاثَةُ سِينَارِيُوهَاتٍ.', src: 'auth0.',
          p: ['اِقْرَأْ.', 'الرَّبْطُ.', 'الأَفْشَلُ.', 'تَطْبِيقُ PKCE.'],
          d: 'رَبْطٌ.', cl: 'اليَوْمُ ١١.' }),

      D(5, 'learn', 'frontend',
        { t: 'React patterns · state management with Zustand', s: SLOTS.weekday,
          o: 'Replace useState chains with a small Zustand store for shared state.',
          src: 'Zustand docs + your React app.',
          p: ['Install Zustand.',
              'Define one store (auth + user).',
              'Use it in two components.',
              'Note the developer-experience improvement.'],
          d: 'A Zustand store integrated.', cl: 'Day 12 covers forms.' },
        { t: 'أَنْمَاطُ React · Zustand', s: SLOTS.weekdayAr,
          o: 'مَتْجَرٌ مُشْتَرَكٌ.', src: 'Zustand.',
          p: ['تَثْبِيتٌ.', 'مَتْجَرٌ.', 'اِسْتِخْدَامٌ.', 'مُلَاحَظَةٌ.'],
          d: 'مَتْجَرٌ.', cl: 'اليَوْمُ ١٢.' }),

      D(6, 'build', 'build',
        { t: 'Build · OAuth provider integration', s: SLOTS.satBuild,
          o: 'Integrate Google OAuth into your SaaS using Laravel Socialite.',
          src: 'Laravel Socialite docs.',
          p: ['Install Socialite.', 'Register Google credentials.', 'Add /auth/google routes.', 'Test the round-trip.'],
          d: 'Working Google OAuth.', cl: 'Day 7 ships.' },
        { t: 'بِنَاءُ OAuth', s: SLOTS.satBuildAr,
          o: 'Google OAuth.', src: 'Socialite.',
          p: ['تَثْبِيتٌ.', 'بَيَانَاتٌ.', 'مَسَارَانِ.', 'اِخْتِبَارٌ.'],
          d: 'OAuth يَعْمَلُ.', cl: 'اليَوْمُ ٧.' }),

      D(7, 'ship', 'ship',
        { t: 'Ship · "OAuth without tears" post', s: SLOTS.sun,
          o: 'Publish a tutorial post on Laravel Socialite with Google.',
          src: 'Your blog.',
          p: ['Draft 800 words.', 'Add screenshots.', 'Publish.', 'Share.'],
          d: 'A tutorial post live.', cl: 'Cycle 2 begins Day 8.' },
        { t: 'نَشْرُ "OAuth بِلَا دُمُوعٍ"', s: SLOTS.sunAr,
          o: '٨٠٠ كَلِمَةٍ.', src: 'المُدَوَّنَةُ.',
          p: ['مُسَوَّدَةٌ.', 'صُوَرٌ.', 'نَشْرٌ.', 'مُشَارَكَةٌ.'],
          d: 'مَنْشُورٌ.', cl: 'الدَّوْرَةُ ٢.' }),

      D(8, 'learn', 'backend',
        { t: 'DDIA Ch 5 · Replication (single-leader, multi-leader, leaderless)', s: SLOTS.weekday,
          o: 'Distinguish the three replication models and their consistency trade-offs.',
          src: 'DDIA Ch 5 · pp. 151-200.',
          p: ['Read Ch 5.', 'Note single-leader (Postgres).', 'Note multi-leader (multi-region).', 'Note leaderless (Cassandra).'],
          d: 'A trade-off table.', cl: 'Day 15 covers partitioning.' },
        { t: 'DDIA ٥ · النَّسْخُ', s: SLOTS.weekdayAr,
          o: 'النَّمَاذِجُ الثَّلَاثَةُ.', src: 'DDIA ٥.',
          p: ['اِقْرَأْ.', 'وَاحِدٌ.', 'مُتَعَدِّدٌ.', 'بِلَا قَائِدٍ.'],
          d: 'جَدْوَلٌ.', cl: 'اليَوْمُ ١٥.' }),

      D(9, 'learn', 'ai',
        { t: 'Embeddings · choosing a model + storage', s: SLOTS.weekday,
          o: 'Compare three embedding options and pick one for your stack.',
          src: 'Voyage AI + OpenAI ada + sentence-transformers benchmarks.',
          p: ['Read each option\'s sheet.',
              'Pick one for cost vs quality.',
              'Decide on storage (pgvector vs Pinecone).',
              'Commit a decision note.'],
          d: 'A decision note.', cl: 'Day 16 covers evals.' },
        { t: 'التَّضْمِينَاتُ', s: SLOTS.weekdayAr,
          o: 'اِخْتِيَارٌ + تَخْزِينٌ.', src: 'بَيَانَاتُ المُقَدِّمِينَ.',
          p: ['اِقْرَأْ.', 'اِخْتَرْ.', 'التَّخْزِينُ.', 'مُلَاحَظَةٌ.'],
          d: 'قَرَارٌ.', cl: 'اليَوْمُ ١٦.' }),

      D(10, 'learn', 'devops',
        { t: 'AWS SAA · Networking advanced (Route 53, Direct Connect, Transit Gateway)', s: SLOTS.weekday,
          o: 'Cover the advanced networking pieces likely on the exam.',
          src: 'Maarek AWS SAA · Advanced Networking module.',
          p: ['Watch the module (90 min).', 'Note when to use each.', 'Flashcards × 10.', '10 sample Qs.'],
          d: 'Flashcards.', cl: 'Day 17 covers Helm.' },
        { t: 'الشَّبَكَاتُ المُتَقَدِّمَةُ', s: SLOTS.weekdayAr,
          o: 'Route 53 وَTransit Gateway.', src: 'Maarek.',
          p: ['الوَحْدَةُ.', 'الِاسْتِخْدَامُ.', 'بِطَاقَاتٌ.', 'أَسْئِلَةٌ.'],
          d: 'بِطَاقَاتٌ.', cl: 'اليَوْمُ ١٧.' }),

      D(11, 'learn', 'secops',
        { t: 'Secrets management · environment vars + Vault', s: SLOTS.weekday,
          o: 'Stop hardcoding secrets and adopt a secrets-manager pattern.',
          src: 'HashiCorp Vault tutorials + AWS Secrets Manager docs.',
          p: ['Audit your repo for hardcoded secrets.',
              'Move all to env vars + .env.example.',
              'Read about Vault\'s static secrets mode.',
              'Decide whether to use Vault or AWS Secrets Manager.'],
          d: 'A secrets-cleaned repo + a chosen manager.', cl: 'Day 18 covers IAM.' },
        { t: 'إِدَارَةُ الأَسْرَارِ', s: SLOTS.weekdayAr,
          o: 'Vault أَوْ AWS.', src: 'الوَثَائِقُ.',
          p: ['مُحَاسَبَةٌ.', 'env.', 'Vault.', 'اِخْتِيَارٌ.'],
          d: 'مُسْتَوْدَعٌ نَظِيفٌ.', cl: 'اليَوْمُ ١٨.' }),

      D(12, 'learn', 'frontend',
        { t: 'React forms · React Hook Form + Zod validation', s: SLOTS.weekday,
          o: 'Build a typed, validated form using React Hook Form + Zod.',
          src: 'React Hook Form + Zod docs.',
          p: ['Install both.', 'Define a Zod schema for register form.', 'Wire it to RHF.', 'Test validation.'],
          d: 'A validated register form.', cl: 'Day 19 covers Next.js.' },
        { t: 'النَّمَاذِجُ مَعَ Zod', s: SLOTS.weekdayAr,
          o: 'تَحَقُّقٌ مُنَوَّعٌ.', src: 'RHF + Zod.',
          p: ['تَثْبِيتٌ.', 'مُخَطَّطٌ.', 'رَبْطٌ.', 'اِخْتِبَارٌ.'],
          d: 'نَمُوذَجٌ.', cl: 'اليَوْمُ ١٩.' }),

      D(13, 'build', 'build',
        { t: 'Build · Postgres replication setup (read replica)', s: SLOTS.satBuild,
          o: 'Add a read replica to your Postgres in docker-compose and route reads to it.',
          src: 'Postgres docs on streaming replication.',
          p: ['Add a postgres-replica service to compose.',
              'Configure streaming replication.',
              'Set up Laravel read/write split.',
              'Test that writes go to primary, reads from replica.'],
          d: 'Working primary + replica.', cl: 'Day 14 ships about it.' },
        { t: 'نَسْخُ Postgres', s: SLOTS.satBuildAr,
          o: 'إِضَافَةُ نُسْخَةِ قِرَاءَةٍ.', src: 'وَثَائِقُ Postgres.',
          p: ['خِدْمَةٌ.', 'تَدَفُّقٌ.', 'تَقْسِيمٌ.', 'اِخْتِبَارٌ.'],
          d: 'نُسْخَتَانِ.', cl: 'اليَوْمُ ١٤.' }),

      D(14, 'ship', 'ship',
        { t: 'Ship · "Reading DDIA Ch 5 with my own replicas"', s: SLOTS.sun,
          o: 'Publish a post connecting DDIA Ch 5 theory to your hands-on replica setup.',
          src: 'Your blog.',
          p: ['700 words.', 'Add the docker-compose snippet.', 'Publish.', 'Share.'],
          d: 'A post out.', cl: 'Cycle 3 begins Day 15.' },
        { t: 'نَشْرُ مَقَالِ النَّسْخِ', s: SLOTS.sunAr,
          o: '٧٠٠ كَلِمَةٍ.', src: 'المُدَوَّنَةُ.',
          p: ['٧٠٠.', 'compose.', 'نَشْرٌ.', 'مُشَارَكَةٌ.'],
          d: 'مَنْشُورٌ.', cl: 'الدَّوْرَةُ ٣.' }),

      D(15, 'learn', 'backend',
        { t: 'DDIA Ch 6 · Partitioning (sharding strategies)', s: SLOTS.weekday,
          o: 'Understand range vs hash partitioning and rebalancing approaches.',
          src: 'DDIA Ch 6 · pp. 201-230.',
          p: ['Read Ch 6.', 'Note range vs hash trade-offs.', 'Note hot-spot problems.', 'Choose a partitioning strategy for users in your SaaS.'],
          d: 'A strategy + rationale.', cl: 'Day 22 reviews.' },
        { t: 'DDIA ٦ · التَّقْسِيمُ', s: SLOTS.weekdayAr,
          o: 'النِّطَاقُ مُقَابِلَ التَّجْزِئَةِ.', src: 'DDIA ٦.',
          p: ['اِقْرَأْ.', 'المُقَايَضَاتُ.', 'النُّقَطُ الحَارَّةُ.', 'اِسْتِرَاتِيجِيَّةٌ.'],
          d: 'اِسْتِرَاتِيجِيَّةٌ.', cl: 'اليَوْمُ ٢٢.' }),

      D(16, 'learn', 'ai',
        { t: 'Evaluation · building a tiny eval harness', s: SLOTS.weekday,
          o: 'Build a 10-case eval set for one of your AI features.',
          src: 'Anthropic evals docs + your own scripts.',
          p: ['Pick one feature (e.g., summarisation).', 'Write 10 input → expected output pairs.', 'Write a scorer (exact match or LLM-as-judge).', 'Run baseline.'],
          d: 'A 10-case eval harness.', cl: 'Day 23 reviews.' },
        { t: 'تَقْيِيمُ AI', s: SLOTS.weekdayAr,
          o: '١٠ حَالَاتٍ.', src: 'وَثَائِقُ Anthropic.',
          p: ['اِخْتِيَارٌ.', '١٠ أَزْوَاجٍ.', 'مُقَيِّمٌ.', 'خَطٌّ أَسَاسٌ.'],
          d: 'حُزْمَةُ تَقْيِيمٍ.', cl: 'اليَوْمُ ٢٣.' }),

      D(17, 'learn', 'devops',
        { t: 'Helm charts intro', s: SLOTS.weekday,
          o: 'Understand Helm and write a tiny chart for your Laravel app.',
          src: 'Helm docs · Getting Started.',
          p: ['Install Helm.', 'Run helm create laravel.', 'Customise values.yaml.', 'helm install --dry-run.'],
          d: 'A working dry-run.', cl: 'Day 24 reviews.' },
        { t: 'Helm', s: SLOTS.weekdayAr,
          o: 'مُخَطَّطٌ صَغِيرٌ.', src: 'وَثَائِقُ Helm.',
          p: ['تَثْبِيتٌ.', 'إِنْشَاءٌ.', 'تَخْصِيصٌ.', 'تَجْرِيبٌ.'],
          d: 'مُخَطَّطٌ.', cl: 'اليَوْمُ ٢٤.' }),

      D(18, 'learn', 'secops',
        { t: 'AWS IAM deep · least privilege', s: SLOTS.weekday,
          o: 'Build a least-privilege IAM policy for one role you actually need.',
          src: 'AWS IAM docs + policy simulator.',
          p: ['Identify the role.', 'Draft a tight policy.', 'Test in the simulator.', 'Tighten until it just works.'],
          d: 'A least-priv policy + simulator results.', cl: 'Day 25 reviews.' },
        { t: 'IAM مُتَعَمِّقٌ', s: SLOTS.weekdayAr,
          o: 'أَقَلُّ امْتِيَازٍ.', src: 'IAM Simulator.',
          p: ['دَوْرٌ.', 'سِيَاسَةٌ.', 'اِخْتِبَارٌ.', 'تَضْيِيقٌ.'],
          d: 'سِيَاسَةٌ.', cl: 'اليَوْمُ ٢٥.' }),

      D(19, 'learn', 'frontend',
        { t: 'Next.js intro · SSR vs SSG vs ISR', s: SLOTS.weekday,
          o: 'Understand the three rendering modes and when to use each.',
          src: 'Next.js docs · Rendering.',
          p: ['Read the rendering section.', 'Pick one for your portfolio (SSG).', 'Pick one for your SaaS dashboard (SSR).', 'Note ISR for blog.'],
          d: 'A three-mode choice note.', cl: 'Day 26 reviews.' },
        { t: 'Next.js', s: SLOTS.weekdayAr,
          o: 'SSR/SSG/ISR.', src: 'وَثَائِقُ Next.',
          p: ['اِقْرَأْ.', 'بُورْتْفُولِيُو.', 'لَوْحَةٌ.', 'مُدَوَّنَةٌ.'],
          d: 'مُلَاحَظَةٌ.', cl: 'اليَوْمُ ٢٦.' }),

      D(20, 'build', 'build',
        { t: 'Build · move portfolio to Next.js (SSG)', s: SLOTS.satBuild,
          o: 'Migrate your portfolio from plain HTML/CSS to Next.js with SSG.',
          src: 'Next.js + your portfolio.',
          p: ['create-next-app.', 'Port the hero.', 'Configure SSG build.', 'Deploy to Vercel.'],
          d: 'A live Next.js portfolio.', cl: 'Day 21 ships about it.' },
        { t: 'تَرْحِيلُ البُورْتْفُولِيُو', s: SLOTS.satBuildAr,
          o: 'Next.js + SSG + Vercel.', src: 'Next.',
          p: ['إِنْشَاءٌ.', 'نَقْلٌ.', 'بِنَاءٌ.', 'نَشْرٌ.'],
          d: 'بُورْتْفُولِيُو حَيٌّ.', cl: 'اليَوْمُ ٢١.' }),

      D(21, 'revise', 'ship',
        { t: 'Ship · "Two months in: what shipped"', s: SLOTS.sun,
          o: 'Publish a two-month summary post.',
          src: 'Your blog.',
          p: ['Draft 700 words.', 'Link to all four prior posts.', 'Publish.', 'Share.'],
          d: 'A two-month summary post.', cl: 'Day 22 begins revision.' },
        { t: 'مُلَخَّصُ شَهْرَيْنِ', s: SLOTS.sunAr,
          o: '٧٠٠ كَلِمَةٍ.', src: 'المُدَوَّنَةُ.',
          p: ['٧٠٠.', 'رَوَابِطُ.', 'نَشْرٌ.', 'مُشَارَكَةٌ.'],
          d: 'مَنْشُورٌ.', cl: 'اليَوْمُ ٢٢.' }),

      D(22, 'revise', 'backend',
        { t: 'Backend revision · Ch 4-6 integration', s: SLOTS.weekday,
          o: 'Tie encoding, replication, and partitioning into one mental model.',
          src: 'Your DDIA notes.',
          p: ['Re-read your three chapter notes.', 'Draw one diagram showing them together.', 'Note one open question.', 'Plan Ch 7 for Month 3.'],
          d: 'An integrated diagram.', cl: 'Month 3 covers Transactions.' },
        { t: 'مُرَاجَعَةُ الخَلْفِيَّةِ ٤-٦', s: SLOTS.weekdayAr,
          o: 'دَمْجٌ.', src: 'الدَّفْتَرُ.',
          p: ['قِرَاءَةٌ.', 'رَسْمٌ.', 'سُؤَالٌ.', 'تَخْطِيطٌ.'],
          d: 'رَسْمٌ.', cl: 'الشَّهْرُ ٣.' }),

      D(23, 'revise', 'ai',
        { t: 'AI revision · agent + RAG + eval together', s: SLOTS.weekday,
          o: 'Combine the agent (Day 2), RAG (Month 1 Day 16), and eval (Day 16) into one tested feature.',
          src: 'Your AI lab.',
          p: ['Combine.', 'Run the eval against the combined system.', 'Note the pass rate.', 'Fix one failure.'],
          d: 'A combined, eval-gated AI feature.', cl: 'Month 3 covers prompt caching.' },
        { t: 'مُرَاجَعَةُ AI', s: SLOTS.weekdayAr,
          o: 'دَمْجٌ ثُلَاثِيٌّ.', src: 'مُخْتَبَرُكَ.',
          p: ['دَمْجٌ.', 'تَقْيِيمٌ.', 'النَّجَاحُ.', 'إِصْلَاحٌ.'],
          d: 'مِيزَةٌ.', cl: 'الشَّهْرُ ٣.' }),

      D(24, 'revise', 'devops',
        { t: 'DevOps revision · AWS basics + Helm sketch', s: SLOTS.weekday,
          o: 'Sketch your future cloud deployment using AWS + K8s + Helm.',
          src: 'Your DevOps notes.',
          p: ['Take the M1 topology.', 'Refine with the M2 networking + DB.', 'Add Helm chart layer.', 'Identify the next gap.'],
          d: 'A refined topology.', cl: 'Month 3 covers Terraform.' },
        { t: 'مُرَاجَعَةُ DevOps', s: SLOTS.weekdayAr,
          o: 'طُوبُولُوجِيَا مُحَدَّثَةٌ.', src: 'الدَّفْتَرُ.',
          p: ['M1.', 'تَحْدِيثٌ.', 'Helm.', 'فَجْوَةٌ.'],
          d: 'طُوبُولُوجِيَا.', cl: 'الشَّهْرُ ٣.' }),

      D(25, 'revise', 'secops',
        { t: 'SecOps revision · OAuth + secrets + IAM tied', s: SLOTS.weekday,
          o: 'Build one diagram showing how OAuth, secrets, and IAM relate in your stack.',
          src: 'Your SecOps notes.',
          p: ['Draw the user journey through OAuth.', 'Mark where secrets live.', 'Mark where IAM enforces.', 'Identify one weakness.'],
          d: 'An integrated security diagram.', cl: 'Month 3 covers network security.' },
        { t: 'مُرَاجَعَةُ SecOps', s: SLOTS.weekdayAr,
          o: 'دَمْجٌ.', src: 'الدَّفْتَرُ.',
          p: ['تَدَفُّقٌ.', 'أَسْرَارٌ.', 'IAM.', 'ضَعْفٌ.'],
          d: 'رَسْمٌ.', cl: 'الشَّهْرُ ٣.' }),

      D(26, 'revise', 'frontend',
        { t: 'Frontend revision · React patterns inventory', s: SLOTS.weekday,
          o: 'List patterns you have now: useState, useEffect, Zustand, RHF, Zod, Next.js SSG/SSR. Identify the gap.',
          src: 'Your frontend repo.',
          p: ['List the patterns.', 'Find one gap (e.g., loading skeletons).', 'Add it.', 'Commit.'],
          d: 'A frontend patterns inventory + one new pattern added.', cl: 'Month 3 covers design systems.' },
        { t: 'جَرْدُ الأَنْمَاطِ', s: SLOTS.weekdayAr,
          o: 'فَجْوَةٌ تُسَدُّ.', src: 'المُسْتَوْدَعُ.',
          p: ['جَرْدٌ.', 'فَجْوَةٌ.', 'إِضَافَةٌ.', 'commit.'],
          d: 'جَرْدٌ.', cl: 'الشَّهْرُ ٣.' }),

      D(27, 'build', 'build',
        { t: 'Build · cross-stack feature complete', s: SLOTS.satBuild,
          o: 'Ship a feature that touches every layer: tenant signup with OAuth, tenant dashboard React+Next, replica reads.',
          src: 'Your repo.',
          p: ['Tenant signup.', 'Dashboard component.', 'Replica routing.', 'End-to-end test.'],
          d: 'One full-stack feature.', cl: 'Day 28 quizzes.' },
        { t: 'مِيزَةٌ مُتَكَامِلَةٌ', s: SLOTS.satBuildAr,
          o: 'كُلُّ الطَّبَقَاتِ.', src: 'المُسْتَوْدَعُ.',
          p: ['التَّسْجِيلُ.', 'اللَّوْحَةُ.', 'النُّسْخَةُ.', 'الِاخْتِبَارُ.'],
          d: 'مِيزَةٌ.', cl: 'اليَوْمُ ٢٨.' }),

      D(28, 'revise', 'revise',
        { t: 'Month 2 cumulative quiz', s: SLOTS.satDeep,
          o: 'Self-quiz on all five disciplines + the integrated feature.',
          src: 'Notebooks.',
          p: ['Encoding + replication + partitioning.',
              'Agent + embeddings + eval.',
              'AWS Networking + DB + Helm.',
              'OAuth flows + secrets + IAM.',
              'Zustand + RHF + Next.js.'],
          d: 'A scorecard.', cl: '٢٩.' },
        { t: 'اِمْتِحَانُ الشَّهْرِ ٢', s: SLOTS.satDeepAr,
          o: 'الخَمْسَةُ.', src: 'الدَّفَاتِرُ.',
          p: ['الخَلْفِيَّةُ.', 'AI.', 'DevOps.', 'SecOps.', 'الوَاجِهَةُ.'],
          d: 'بِطَاقَةٌ.', cl: '٢٩.' }),

      D(29, 'revise', 'revise',
        { t: 'Reflection · the pace check', s: SLOTS.sun,
          o: 'Are you behind schedule? At pace? Ahead? Adjust Month 3 accordingly.',
          src: 'Pen + notebook.',
          p: ['Compare planned vs done.', 'Note slipped days.', 'Decide what to cut for Month 3.', 'Set Month 3 niyyah.'],
          d: 'A pace assessment + Month 3 niyyah.', cl: '٣٠.' },
        { t: 'فَحْصُ الإِيقَاعِ', s: SLOTS.sunAr,
          o: 'مُتَأَخِّرٌ أَوْ فِي الإِيقَاعِ.', src: 'قَلَمٌ.',
          p: ['مُقَارَنَةٌ.', 'تَأَخُّرٌ.', 'حَذْفٌ.', 'نِيَّةٌ.'],
          d: 'تَقْيِيمٌ + نِيَّةٌ.', cl: '٣٠.' }),

      D(30, 'revise', 'ship',
        { t: 'Ship · Month 2 retro + Month 3 niyyah', s: SLOTS.sun,
          o: 'Publish the M2 retro + commit publicly to Month 3 goals.',
          src: 'Your blog.',
          p: ['Draft 700 words.', 'Add the integrated feature screenshot.', 'Publish.', 'Sleep early.'],
          d: 'A retro post.', cl: 'Month 3 begins tomorrow.',
          dua: 'O Allah, deepen what You have started.' },
        { t: 'نَشْرُ مُرَاجَعَةِ الشَّهْرِ ٢', s: SLOTS.sunAr,
          o: '٧٠٠ كَلِمَةٍ.', src: 'المُدَوَّنَةُ.',
          p: ['٧٠٠.', 'صُورَةٌ.', 'نَشْرٌ.', 'نَوْمٌ.'],
          d: 'مَنْشُورٌ.', cl: 'الشَّهْرُ ٣.',
          dua: 'اللَّهُمَّ عَمِّقْ مَا بَدَأْتَ.' })
    ]
  });

  // Attach to global SYLLABUS_DATA
  if (window.SYLLABUS_DATA && typeof window.SYLLABUS_DATA.attachMonths === 'function') {
    window.SYLLABUS_DATA.attachMonths('se', SE_MONTHS);
  }
  window.__SYLLABUS_SE_MONTHS = SE_MONTHS;
})();
