/* ==============================================
   BOOKS CATALOG — Master index of all books
   Add new books here. One entry per book.
   The `id` must match the folder name in books/
   ============================================== */

var BOOK_CATEGORIES = [
    { id: "islamic-studies", label: "Islamic Studies", icon: "fas fa-quran", color: "#22c55e" },
    { id: "islamic-lifestyle", label: "Islamic Lifestyle", icon: "fas fa-mosque", color: "#10b981" },
    { id: "islamic-history", label: "Islamic History", icon: "fas fa-landmark", color: "#059669" },
    { id: "productivity", label: "Productivity", icon: "fas fa-rocket", color: "#3b82f6" },
    { id: "personal-development", label: "Personal Development", icon: "fas fa-seedling", color: "#8b5cf6" },
    { id: "software-engineering", label: "Software Engineering", icon: "fas fa-code", color: "#f59e0b" },
    { id: "engineering-management", label: "Engineering Management", icon: "fas fa-users-cog", color: "#ef4444" },
    { id: "leadership", label: "Leadership", icon: "fas fa-chess-king", color: "#ec4899" },
    { id: "non-fiction", label: "Non-Fiction", icon: "fas fa-book", color: "#6366f1" },
    { id: "finance-business", label: "Finance & Business", icon: "fas fa-chart-line", color: "#14b8a6" },
    { id: "psychology", label: "Psychology", icon: "fas fa-brain", color: "#f43f5e" },
    { id: "biography", label: "Biography", icon: "fas fa-user-tie", color: "#a855f7" },
    { id: "parenting-family", label: "Parenting & Family", icon: "fas fa-home", color: "#f97316" },
    { id: "health-wellness", label: "Health & Wellness", icon: "fas fa-heartbeat", color: "#06b6d4" },
    { id: "spirituality", label: "Spirituality", icon: "fas fa-star-and-crescent", color: "#84cc16" }
];

var BOOKS_CATALOG = [
    // ═══════════════════════════════════════
    // EXISTING BOOKS
    // ═══════════════════════════════════════
    {
        id: "the-productive-muslim",
        title: "The Productive Muslim",
        author: "Mohammed Faris",
        subtitle: "Where Faith Meets Productivity",
        description: "A comprehensive guide that combines Islamic principles with modern productivity science. Learn the Focus \u00d7 Energy \u00d7 Time formula, build spiritual habits, and unlock your full potential as a Muslim professional.",
        categories: ["islamic-lifestyle", "productivity", "personal-development"],
        tags: ["habits", "time-management", "spirituality", "focus", "energy", "ramadan", "salah"],
        icon: "fas fa-book-open",
        color: "#22c55e",
        chaptersCount: 9,
        status: "complete",
        dateAdded: "2024-01-15",
        language: "English",
        factCheckNote: "This summary is based on personal reading and interpretation. Always refer to the original book for exact quotes and context. Verify Islamic references (Quran, Hadith) with qualified scholars."
    },
    {
        id: "the-barakah-effect",
        title: "The Barakah Effect",
        author: "Mohammed Faris",
        subtitle: "More With Less \u2014 Achieving Barakah in Every Area of Life",
        description: "Discover the 10 principles of Barakah and learn how to achieve more with less through divine blessings. A paradigm shift from hustle culture to a purpose-driven, blessed life rooted in Islamic values.",
        categories: ["islamic-lifestyle", "spirituality", "personal-development"],
        tags: ["barakah", "blessings", "gratitude", "ihsan", "excellence", "salawat", "tawakkul", "death-awareness"],
        icon: "fas fa-star",
        color: "#3b82f6",
        chaptersCount: 16,
        status: "complete",
        dateAdded: "2024-03-10",
        language: "English",
        factCheckNote: "This summary is based on personal reading and interpretation. Always refer to the original book for exact quotes and context. Verify Islamic references (Quran, Hadith) with qualified scholars."
    },

    // ═══════════════════════════════════════
    // ISLAMIC STUDIES & SPIRITUALITY
    // ═══════════════════════════════════════
    {
        id: "purification-of-the-heart",
        title: "Purification of the Heart",
        author: "Hamza Yusuf",
        subtitle: "Signs, Symptoms, and Cures of the Spiritual Diseases of the Heart",
        description: "A translation and commentary on Imam al-Mawlud\u2019s poem on the diseases of the heart. Explores envy, hatred, love of the world, arrogance, and other spiritual ailments with their Islamic cures.",
        categories: ["islamic-studies", "spirituality"],
        tags: ["heart", "diseases", "tazkiyah", "purification", "envy", "arrogance", "spiritual-growth"],
        icon: "fas fa-heart",
        color: "#ec4899",
        chaptersCount: 12,
        status: "complete",
        dateAdded: "2024-04-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original book and Imam al-Mawlud\u2019s poem for accuracy. Verify all Islamic references with qualified scholars."
    },
    {
        id: "reclaim-your-heart",
        title: "Reclaim Your Heart",
        author: "Yasmin Mogahed",
        subtitle: "Personal Insights on Breaking Free from Life\u2019s Shackles",
        description: "A collection of essays on detaching from the dunya, healing from heartbreak, finding inner peace, and building a deeper connection with Allah through the trials of life.",
        categories: ["islamic-lifestyle", "spirituality", "personal-development"],
        tags: ["attachment", "dunya", "healing", "tawakkul", "inner-peace", "trials"],
        icon: "fas fa-dove",
        color: "#a855f7",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-04-15",
        language: "English",
        factCheckNote: "This summary is based on personal reading and interpretation. Always refer to the original book for exact quotes and context."
    },
    {
        id: "dont-be-sad",
        title: "Don\u2019t Be Sad",
        author: "Aaidh ibn Abdullah al-Qarni",
        subtitle: "Prescriptions for Happiness from the Quran and Sunnah",
        description: "One of the best-selling Arabic books of all time. A treasure of practical advice from the Quran, Sunnah, and the lives of scholars on overcoming sadness, anxiety, and depression.",
        categories: ["islamic-studies", "spirituality", "personal-development"],
        tags: ["happiness", "sadness", "anxiety", "quran", "sunnah", "optimism", "contentment"],
        icon: "fas fa-smile",
        color: "#f59e0b",
        chaptersCount: 12,
        status: "complete",
        dateAdded: "2024-05-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Verify all Quran and Hadith references with original Arabic sources and qualified scholars."
    },
    {
        id: "fortress-of-the-muslim",
        title: "Fortress of the Muslim",
        author: "Sa\u2019id bin Ali bin Wahf al-Qahtani",
        subtitle: "Invocations from the Quran and Sunnah",
        description: "The essential collection of authentic duas and adhkar for every occasion \u2014 morning, evening, travel, eating, sleeping, distress, and more. A Muslim\u2019s daily companion.",
        categories: ["islamic-studies"],
        tags: ["dua", "adhkar", "dhikr", "supplication", "daily-routine", "protection"],
        icon: "fas fa-shield-alt",
        color: "#059669",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-05-10",
        language: "English/Arabic",
        factCheckNote: "Duas are sourced from authentic hadith collections. Always verify transliterations and translations with Arabic originals."
    },
    {
        id: "revive-your-heart",
        title: "Revive Your Heart",
        author: "Nouman Ali Khan",
        subtitle: "Putting Life in Perspective",
        description: "Reflections on faith, gratitude, and purpose drawn from the Quran. Nouman Ali Khan shares powerful insights on how to reconnect with Allah and find meaning in everyday struggles.",
        categories: ["islamic-lifestyle", "spirituality"],
        tags: ["quran", "faith", "gratitude", "purpose", "reflection", "iman"],
        icon: "fas fa-heartbeat",
        color: "#ef4444",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-05-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Verify Quranic references with original Arabic text and tafsir."
    },
    {
        id: "being-muslim",
        title: "Being Muslim",
        author: "Asad Tarsin",
        subtitle: "A Practical Guide",
        description: "A clear, comprehensive guide covering the essentials of Muslim practice \u2014 prayer, fasting, zakat, hajj, daily etiquette, and spiritual development. Perfect for new Muslims and those seeking to strengthen foundations.",
        categories: ["islamic-studies", "islamic-lifestyle"],
        tags: ["prayer", "fasting", "zakat", "hajj", "basics", "practice", "new-muslim"],
        icon: "fas fa-pray",
        color: "#22c55e",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-06-01",
        language: "English",
        factCheckNote: "This summary covers Islamic practices. Always verify rulings with qualified scholars of your madhab."
    },
    {
        id: "tales-of-the-prophets",
        title: "Stories of the Prophets",
        author: "Ibn Kathir",
        subtitle: "Qisas al-Anbiya \u2014 Lessons from the Lives of the Prophets",
        description: "The classic collection of stories of the Prophets from Adam to Muhammad (peace be upon them all), drawn from the Quran and authentic narrations. Timeless lessons in faith, patience, and trust in Allah.",
        categories: ["islamic-studies", "islamic-history"],
        tags: ["prophets", "adam", "ibrahim", "musa", "isa", "stories", "quran", "patience"],
        icon: "fas fa-scroll",
        color: "#84cc16",
        chaptersCount: 12,
        status: "complete",
        dateAdded: "2024-06-10",
        language: "English",
        factCheckNote: "Based on Ibn Kathir\u2019s Qisas al-Anbiya. Verify all narrations with original Arabic sources."
    },

    // ═══════════════════════════════════════
    // ISLAMIC HISTORY
    // ═══════════════════════════════════════
    {
        id: "the-sealed-nectar",
        title: "The Sealed Nectar",
        author: "Safiur Rahman Mubarakpuri",
        subtitle: "Ar-Raheeq Al-Makhtum \u2014 Biography of the Noble Prophet",
        description: "The award-winning biography of Prophet Muhammad (peace be upon him). A detailed, authenticated account of his life from birth to death, covering key events, battles, and the establishment of Islam.",
        categories: ["islamic-history", "biography"],
        tags: ["seerah", "prophet-muhammad", "biography", "makkah", "madinah", "battles", "revelation"],
        icon: "fas fa-book-quran",
        color: "#059669",
        chaptersCount: 12,
        status: "complete",
        dateAdded: "2024-06-20",
        language: "English",
        factCheckNote: "This summary covers the Seerah. Verify all historical facts and hadith references with authenticated sources."
    },
    {
        id: "in-the-footsteps-of-the-prophet",
        title: "In the Footsteps of the Prophet",
        author: "Tariq Ramadan",
        subtitle: "Lessons from the Life of Muhammad",
        description: "A spiritual and intellectual biography of the Prophet Muhammad (peace be upon him) that draws timeless lessons for modern life \u2014 justice, compassion, humility, and social engagement.",
        categories: ["islamic-history", "islamic-lifestyle", "biography"],
        tags: ["seerah", "prophet-muhammad", "lessons", "justice", "compassion", "modern-life"],
        icon: "fas fa-shoe-prints",
        color: "#10b981",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-07-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Verify all Seerah details with authenticated sources."
    },
    {
        id: "lost-islamic-history",
        title: "Lost Islamic History",
        author: "Firas Alkhateeb",
        subtitle: "Reclaiming Muslim Civilisation from the Past",
        description: "A panoramic journey through 1,400 years of Islamic civilization \u2014 from the Prophet\u2019s era through the Umayyads, Abbasids, Ottomans, and into the modern Muslim world. Science, art, governance, and scholarship.",
        categories: ["islamic-history", "non-fiction"],
        tags: ["civilization", "history", "caliphate", "science", "golden-age", "ottoman", "umayyad", "abbasid"],
        icon: "fas fa-globe-africa",
        color: "#6366f1",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-07-10",
        language: "English",
        factCheckNote: "This summary covers historical events. Cross-reference with academic historical sources for accuracy."
    },

    // ═══════════════════════════════════════
    // PRODUCTIVITY
    // ═══════════════════════════════════════
    {
        id: "atomic-habits",
        title: "Atomic Habits",
        author: "James Clear",
        subtitle: "Tiny Changes, Remarkable Results",
        description: "The definitive guide to building good habits and breaking bad ones. Learn the Four Laws of Behavior Change, the habit loop, identity-based habits, and how 1% improvements compound into extraordinary results.",
        categories: ["productivity", "personal-development"],
        tags: ["habits", "behavior-change", "compound-effect", "identity", "systems", "cue-routine-reward"],
        icon: "fas fa-atom",
        color: "#3b82f6",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-07-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original book for research citations and specific examples."
    },
    {
        id: "deep-work",
        title: "Deep Work",
        author: "Cal Newport",
        subtitle: "Rules for Focused Success in a Distracted World",
        description: "Learn why the ability to focus without distraction is the superpower of the 21st century. Cal Newport presents strategies for cultivating deep work habits and eliminating shallow work.",
        categories: ["productivity", "personal-development"],
        tags: ["focus", "distraction", "deep-work", "shallow-work", "concentration", "flow"],
        icon: "fas fa-bullseye",
        color: "#8b5cf6",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-08-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original book for research references."
    },
    {
        id: "the-7-habits",
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen R. Covey",
        subtitle: "Powerful Lessons in Personal Change",
        description: "The classic framework for personal and professional effectiveness. From being proactive to synergizing, these seven habits form a principle-centered approach to solving personal and professional problems.",
        categories: ["productivity", "personal-development", "leadership"],
        tags: ["habits", "effectiveness", "character", "proactive", "win-win", "synergy", "principles"],
        icon: "fas fa-list-ol",
        color: "#14b8a6",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-08-10",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original book for the full framework and examples."
    },
    {
        id: "getting-things-done",
        title: "Getting Things Done",
        author: "David Allen",
        subtitle: "The Art of Stress-Free Productivity",
        description: "The GTD methodology for capturing, clarifying, organizing, reflecting, and engaging with tasks. Master your workflow, clear your mind, and achieve stress-free productivity.",
        categories: ["productivity"],
        tags: ["gtd", "workflow", "organization", "capture", "inbox-zero", "next-actions", "projects"],
        icon: "fas fa-check-double",
        color: "#22c55e",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-08-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The GTD system has specific nuances best understood from the original book."
    },
    {
        id: "essentialism",
        title: "Essentialism",
        author: "Greg McKeown",
        subtitle: "The Disciplined Pursuit of Less",
        description: "Not about getting more done in less time \u2014 it\u2019s about getting only the right things done. Learn to identify what is truly essential, eliminate everything else, and make execution effortless.",
        categories: ["productivity", "personal-development"],
        tags: ["essentialism", "minimalism", "focus", "priority", "saying-no", "trade-offs"],
        icon: "fas fa-compress-arrows-alt",
        color: "#f43f5e",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-09-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original book for detailed examples and frameworks."
    },
    {
        id: "the-one-thing",
        title: "The ONE Thing",
        author: "Gary Keller & Jay Papasan",
        subtitle: "The Surprisingly Simple Truth Behind Extraordinary Results",
        description: "What\u2019s the ONE Thing you can do such that by doing it everything else will be easier or unnecessary? A powerful framework for focusing on what matters most and achieving extraordinary results.",
        categories: ["productivity", "personal-development"],
        tags: ["focus", "priority", "domino-effect", "time-blocking", "purpose", "goal-setting"],
        icon: "fas fa-crosshairs",
        color: "#ef4444",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-09-10",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original book for the complete framework."
    },
    {
        id: "make-time",
        title: "Make Time",
        author: "Jake Knapp & John Zeratsky",
        subtitle: "How to Focus on What Matters Every Day",
        description: "A friendly, practical framework for designing your day around what matters. Four daily steps: Highlight, Laser, Energize, and Reflect. 87 tactics to reclaim time from infinity pools and busy bandwagons.",
        categories: ["productivity"],
        tags: ["time-management", "focus", "highlight", "energy", "tactics", "digital-detox"],
        icon: "fas fa-hourglass-half",
        color: "#f97316",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-09-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The book contains 87 specific tactics best explored in the original."
    },
    {
        id: "digital-minimalism",
        title: "Digital Minimalism",
        author: "Cal Newport",
        subtitle: "Choosing a Focused Life in a Noisy World",
        description: "A philosophy of technology use where you focus your online time on a small number of carefully selected activities that strongly support things you value. Includes a 30-day digital declutter plan.",
        categories: ["productivity", "personal-development"],
        tags: ["technology", "social-media", "minimalism", "attention", "solitude", "digital-detox"],
        icon: "fas fa-mobile-alt",
        color: "#6366f1",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-10-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original book for research citations."
    },

    // ═══════════════════════════════════════
    // PERSONAL DEVELOPMENT & PSYCHOLOGY
    // ═══════════════════════════════════════
    {
        id: "mindset",
        title: "Mindset",
        author: "Carol S. Dweck",
        subtitle: "The New Psychology of Success",
        description: "The groundbreaking research on fixed vs. growth mindset. Discover how your beliefs about your abilities fundamentally shape your success in school, work, sports, relationships, and parenting.",
        categories: ["psychology", "personal-development"],
        tags: ["growth-mindset", "fixed-mindset", "beliefs", "learning", "resilience", "effort"],
        icon: "fas fa-brain",
        color: "#8b5cf6",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-10-10",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Some mindset research has been debated \u2014 refer to the original and recent meta-analyses."
    },
    {
        id: "the-power-of-habit",
        title: "The Power of Habit",
        author: "Charles Duhigg",
        subtitle: "Why We Do What We Do in Life and Business",
        description: "An exploration of the science behind habit formation. Learn the habit loop (cue, routine, reward), how keystone habits create chain reactions, and how organizations and societies change through habits.",
        categories: ["psychology", "personal-development", "productivity"],
        tags: ["habits", "cue-routine-reward", "keystone-habits", "willpower", "behavior-change"],
        icon: "fas fa-sync-alt",
        color: "#f59e0b",
        chaptersCount: 9,
        status: "complete",
        dateAdded: "2024-10-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original for research citations and case studies."
    },
    {
        id: "thinking-fast-and-slow",
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        subtitle: "The Two Systems That Drive the Way We Think",
        description: "Nobel laureate Daniel Kahneman\u2019s masterwork on the two systems of thought: fast, intuitive System 1 and slow, deliberate System 2. Reveals the biases and heuristics that shape our judgments and decisions.",
        categories: ["psychology", "non-fiction"],
        tags: ["cognitive-biases", "system-1", "system-2", "heuristics", "decision-making", "behavioral-economics"],
        icon: "fas fa-balance-scale",
        color: "#f43f5e",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-11-01",
        language: "English",
        factCheckNote: "Some studies cited in this book have faced replication challenges. Refer to original research and recent reviews."
    },
    {
        id: "mans-search-for-meaning",
        title: "Man\u2019s Search for Meaning",
        author: "Viktor E. Frankl",
        subtitle: "Finding Purpose in Suffering",
        description: "Viktor Frankl\u2019s account of surviving the Holocaust and the psychological insights that emerged. Introduces logotherapy \u2014 the idea that the primary human drive is not pleasure but the pursuit of meaning.",
        categories: ["psychology", "personal-development", "non-fiction"],
        tags: ["meaning", "purpose", "suffering", "logotherapy", "resilience", "holocaust", "existentialism"],
        icon: "fas fa-sun",
        color: "#f97316",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-11-10",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The book describes historical events and a therapeutic approach \u2014 refer to the original."
    },
    {
        id: "how-to-win-friends",
        title: "How to Win Friends and Influence People",
        author: "Dale Carnegie",
        subtitle: "The Classic Guide to Human Relations",
        description: "The timeless classic on building relationships, influencing people positively, and becoming a more effective communicator. Principles that have helped millions succeed in personal and professional life.",
        categories: ["personal-development", "leadership"],
        tags: ["communication", "relationships", "influence", "empathy", "listening", "persuasion"],
        icon: "fas fa-handshake",
        color: "#22c55e",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2024-11-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The original contains many historical anecdotes and detailed examples."
    },
    {
        id: "grit",
        title: "Grit",
        author: "Angela Duckworth",
        subtitle: "The Power of Passion and Perseverance",
        description: "Why talent alone doesn\u2019t guarantee success. Angela Duckworth\u2019s research shows that grit \u2014 a combination of passion and perseverance \u2014 is the key predictor of achievement in every domain.",
        categories: ["psychology", "personal-development"],
        tags: ["grit", "perseverance", "passion", "talent", "deliberate-practice", "resilience"],
        icon: "fas fa-fist-raised",
        color: "#ef4444",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-12-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original for research details."
    },
    {
        id: "the-5am-club",
        title: "The 5 AM Club",
        author: "Robin Sharma",
        subtitle: "Own Your Morning, Elevate Your Life",
        description: "A fable-based guide to the transformative power of waking at 5 AM. Introduces the 20/20/20 formula \u2014 20 minutes of exercise, 20 minutes of reflection, 20 minutes of learning \u2014 to win the morning.",
        categories: ["productivity", "personal-development"],
        tags: ["morning-routine", "5am", "exercise", "learning", "reflection", "discipline"],
        icon: "fas fa-sunrise",
        color: "#f59e0b",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-12-10",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The book uses a fictional narrative to convey its principles."
    },
    {
        id: "the-compound-effect",
        title: "The Compound Effect",
        author: "Darren Hardy",
        subtitle: "Jumpstart Your Income, Your Life, Your Success",
        description: "Small, smart choices made consistently over time create radical differences. The compound effect is the principle of reaping huge rewards from small, seemingly insignificant actions.",
        categories: ["personal-development", "productivity"],
        tags: ["compound-effect", "consistency", "choices", "momentum", "habits", "discipline"],
        icon: "fas fa-chart-line",
        color: "#14b8a6",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2024-12-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original for specific examples and calculations."
    },
    {
        id: "influence",
        title: "Influence",
        author: "Robert B. Cialdini",
        subtitle: "The Psychology of Persuasion",
        description: "The six universal principles of influence: Reciprocity, Commitment/Consistency, Social Proof, Authority, Liking, and Scarcity. Essential reading for understanding why people say yes.",
        categories: ["psychology", "non-fiction"],
        tags: ["persuasion", "reciprocity", "social-proof", "scarcity", "authority", "marketing"],
        icon: "fas fa-magnet",
        color: "#ec4899",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-01-01",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Refer to the original and updated edition for research details."
    },
    {
        id: "emotional-intelligence",
        title: "Emotional Intelligence",
        author: "Daniel Goleman",
        subtitle: "Why It Can Matter More Than IQ",
        description: "The groundbreaking book that redefined what it means to be smart. Emotional intelligence \u2014 self-awareness, self-regulation, motivation, empathy, and social skills \u2014 predicts success better than IQ.",
        categories: ["psychology", "personal-development"],
        tags: ["eq", "self-awareness", "empathy", "social-skills", "self-regulation", "motivation"],
        icon: "fas fa-theater-masks",
        color: "#a855f7",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-01-10",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Some EQ research has evolved since publication \u2014 refer to current literature."
    },

    // ═══════════════════════════════════════
    // SOFTWARE ENGINEERING
    // ═══════════════════════════════════════
    {
        id: "clean-code",
        title: "Clean Code",
        author: "Robert C. Martin",
        subtitle: "A Handbook of Agile Software Craftsmanship",
        description: "The programmer\u2019s bible for writing clean, readable, maintainable code. Covers naming, functions, comments, formatting, error handling, unit tests, and the principles of craftsmanship.",
        categories: ["software-engineering"],
        tags: ["clean-code", "refactoring", "naming", "functions", "testing", "craftsmanship", "solid"],
        icon: "fas fa-broom",
        color: "#f59e0b",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-01-20",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Some opinions in the book are debated in the community \u2014 form your own judgment."
    },
    {
        id: "the-pragmatic-programmer",
        title: "The Pragmatic Programmer",
        author: "David Thomas & Andrew Hunt",
        subtitle: "Your Journey to Mastery",
        description: "A collection of practical programming wisdom covering everything from personal responsibility and career development to architectural techniques and team dynamics. Timeless advice for every developer.",
        categories: ["software-engineering", "personal-development"],
        tags: ["pragmatic", "dry", "orthogonality", "tracer-bullets", "broken-windows", "craftsmanship"],
        icon: "fas fa-hammer",
        color: "#3b82f6",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-01-25",
        language: "English",
        factCheckNote: "This summary is based on personal reading of the 20th Anniversary Edition. Refer to the original for all tips and exercises."
    },
    {
        id: "designing-data-intensive-applications",
        title: "Designing Data-Intensive Applications",
        author: "Martin Kleppmann",
        subtitle: "The Big Ideas Behind Reliable, Scalable, and Maintainable Systems",
        description: "The essential guide to the principles and practicalities of data systems. Covers databases, distributed systems, batch/stream processing, replication, partitioning, consistency, and transactions.",
        categories: ["software-engineering"],
        tags: ["distributed-systems", "databases", "replication", "partitioning", "consistency", "streaming", "batch"],
        icon: "fas fa-database",
        color: "#ef4444",
        chaptersCount: 12,
        status: "complete",
        dateAdded: "2025-02-01",
        language: "English",
        factCheckNote: "This summary covers complex technical topics. Refer to the original book for diagrams, details, and references."
    },
    {
        id: "system-design-interview",
        title: "System Design Interview",
        author: "Alex Xu",
        subtitle: "An Insider\u2019s Guide",
        description: "A step-by-step framework for approaching system design interviews. Covers URL shorteners, news feeds, chat systems, notification systems, and more with scalable architecture patterns.",
        categories: ["software-engineering"],
        tags: ["system-design", "interview", "scalability", "architecture", "load-balancing", "caching"],
        icon: "fas fa-sitemap",
        color: "#8b5cf6",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-02-05",
        language: "English",
        factCheckNote: "This summary covers system design concepts. Real-world implementations vary \u2014 refer to the original for complete designs."
    },
    {
        id: "refactoring",
        title: "Refactoring",
        author: "Martin Fowler",
        subtitle: "Improving the Design of Existing Code",
        description: "The definitive guide to refactoring \u2014 restructuring existing code without changing its external behavior. Covers code smells, refactoring catalog, and when/how to refactor safely.",
        categories: ["software-engineering"],
        tags: ["refactoring", "code-smells", "design", "testing", "incremental-improvement"],
        icon: "fas fa-recycle",
        color: "#22c55e",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-02-10",
        language: "English",
        factCheckNote: "This summary covers the 2nd edition (JavaScript). Refer to the original for the complete refactoring catalog."
    },
    {
        id: "the-clean-coder",
        title: "The Clean Coder",
        author: "Robert C. Martin",
        subtitle: "A Code of Conduct for Professional Programmers",
        description: "What it means to be a professional software developer. Covers saying no, time management, estimation, pressure, collaboration, tools, and the discipline of professional behavior.",
        categories: ["software-engineering", "personal-development"],
        tags: ["professionalism", "estimation", "pressure", "tdd", "collaboration", "discipline"],
        icon: "fas fa-user-shield",
        color: "#6366f1",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-02-15",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Some views are the author\u2019s strong opinions \u2014 form your own judgment."
    },
    {
        id: "code-complete",
        title: "Code Complete",
        author: "Steve McConnell",
        subtitle: "A Practical Handbook of Software Construction",
        description: "The comprehensive guide to software construction. Covers design, coding, debugging, testing, and the art of writing code that works. Backed by research and industry best practices.",
        categories: ["software-engineering"],
        tags: ["construction", "design", "debugging", "testing", "variables", "complexity"],
        icon: "fas fa-laptop-code",
        color: "#14b8a6",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-02-20",
        language: "English",
        factCheckNote: "This summary covers the 2nd edition. The book is encyclopedic \u2014 refer to the original for the complete reference."
    },
    {
        id: "head-first-design-patterns",
        title: "Head First Design Patterns",
        author: "Eric Freeman & Elisabeth Robson",
        subtitle: "Building Extensible and Maintainable Object-Oriented Software",
        description: "A brain-friendly guide to design patterns. Covers Strategy, Observer, Decorator, Factory, Singleton, Command, Adapter, Facade, Template Method, Iterator, Composite, State, and Proxy patterns.",
        categories: ["software-engineering"],
        tags: ["design-patterns", "oop", "strategy", "observer", "factory", "singleton", "decorator"],
        icon: "fas fa-puzzle-piece",
        color: "#f43f5e",
        chaptersCount: 12,
        status: "complete",
        dateAdded: "2025-02-25",
        language: "English",
        factCheckNote: "This summary covers common design patterns. Refer to the original for visual explanations and code examples."
    },
    {
        id: "cracking-the-coding-interview",
        title: "Cracking the Coding Interview",
        author: "Gayle Laakmann McDowell",
        subtitle: "189 Programming Questions and Solutions",
        description: "The essential guide to technical interview preparation. Covers data structures, algorithms, system design, behavioral questions, and strategies for landing offers at top tech companies.",
        categories: ["software-engineering"],
        tags: ["interview", "algorithms", "data-structures", "big-o", "problem-solving", "leetcode"],
        icon: "fas fa-code",
        color: "#f97316",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-03-01",
        language: "English",
        factCheckNote: "This summary covers interview strategies and concepts. Practice actual problems from the book for full benefit."
    },

    // ═══════════════════════════════════════
    // ENGINEERING MANAGEMENT
    // ═══════════════════════════════════════
    {
        id: "the-managers-path",
        title: "The Manager\u2019s Path",
        author: "Camille Fournier",
        subtitle: "A Guide for Tech Leaders Navigating Growth and Change",
        description: "The essential guide for engineering leaders at every level \u2014 from tech lead to CTO. Covers mentoring, managing individuals, managing teams, managing managers, and managing multiple teams.",
        categories: ["engineering-management", "leadership"],
        tags: ["management", "tech-lead", "mentoring", "1-on-1", "feedback", "culture", "cto"],
        icon: "fas fa-route",
        color: "#ef4444",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-03-02",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The book is rich with specific scenarios best understood from the original."
    },
    {
        id: "an-elegant-puzzle",
        title: "An Elegant Puzzle",
        author: "Will Larson",
        subtitle: "Systems of Engineering Management",
        description: "A systems-thinking approach to engineering management. Covers sizing teams, managing technical debt, succession planning, organizational design, and navigating the unique challenges of growing engineering orgs.",
        categories: ["engineering-management"],
        tags: ["systems-thinking", "org-design", "technical-debt", "team-sizing", "migrations", "strategy"],
        icon: "fas fa-cubes",
        color: "#8b5cf6",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-03",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Models and frameworks are the author\u2019s perspectives from experience."
    },
    {
        id: "staff-engineer",
        title: "Staff Engineer",
        author: "Will Larson",
        subtitle: "Leadership Beyond the Management Track",
        description: "A guide for senior individual contributors. Covers the staff engineer archetypes (Tech Lead, Architect, Solver, Right Hand), getting the title, operating at staff level, and creating impact without authority.",
        categories: ["engineering-management", "software-engineering", "leadership"],
        tags: ["staff-engineer", "ic-track", "architecture", "influence", "technical-leadership", "mentoring"],
        icon: "fas fa-star",
        color: "#f59e0b",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-04",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The book includes interviews with staff+ engineers \u2014 refer to the original for their stories."
    },
    {
        id: "the-making-of-a-manager",
        title: "The Making of a Manager",
        author: "Julie Zhuo",
        subtitle: "What to Do When Everyone Looks to You",
        description: "Practical advice for new managers from Facebook\u2019s VP of Design. Covers the transition to management, running meetings, giving feedback, hiring, and building trust with your team.",
        categories: ["engineering-management", "leadership"],
        tags: ["new-manager", "feedback", "meetings", "hiring", "trust", "design-leadership"],
        icon: "fas fa-user-graduate",
        color: "#ec4899",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-03-05",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The author\u2019s experience is primarily from Meta/Facebook."
    },
    {
        id: "team-topologies",
        title: "Team Topologies",
        author: "Matthew Skelton & Manuel Pais",
        subtitle: "Organizing Business and Technology Teams for Fast Flow",
        description: "A practical model for organizing technology teams. Four team types (Stream-aligned, Enabling, Complicated-subsystem, Platform) and three interaction modes (Collaboration, X-as-a-Service, Facilitating).",
        categories: ["engineering-management", "software-engineering"],
        tags: ["team-design", "flow", "platform", "stream-aligned", "cognitive-load", "conways-law"],
        icon: "fas fa-object-group",
        color: "#3b82f6",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-06",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The model is a framework \u2014 adapt to your organizational context."
    },
    {
        id: "accelerate",
        title: "Accelerate",
        author: "Nicole Forsgren, Jez Humble & Gene Kim",
        subtitle: "The Science of Lean Software and DevOps",
        description: "Research-backed insights on what drives software delivery performance. The four key metrics (lead time, deployment frequency, MTTR, change failure rate) and the capabilities that predict success.",
        categories: ["engineering-management", "software-engineering"],
        tags: ["devops", "dora-metrics", "continuous-delivery", "lean", "culture", "automation"],
        icon: "fas fa-tachometer-alt",
        color: "#22c55e",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-07",
        language: "English",
        factCheckNote: "This summary covers the State of DevOps research. Refer to the original for methodology and full statistical analysis."
    },

    // ═══════════════════════════════════════
    // LEADERSHIP
    // ═══════════════════════════════════════
    {
        id: "start-with-why",
        title: "Start with Why",
        author: "Simon Sinek",
        subtitle: "How Great Leaders Inspire Everyone to Take Action",
        description: "The Golden Circle framework: Why \u2192 How \u2192 What. Great leaders and organizations start with purpose (Why), not product (What). Discover how to inspire action and build loyal followings.",
        categories: ["leadership", "personal-development"],
        tags: ["purpose", "golden-circle", "inspiration", "why", "vision", "motivation"],
        icon: "fas fa-bullhorn",
        color: "#f59e0b",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-08",
        language: "English",
        factCheckNote: "This summary is based on personal reading. The framework is conceptual \u2014 refer to the original for case studies."
    },
    {
        id: "leaders-eat-last",
        title: "Leaders Eat Last",
        author: "Simon Sinek",
        subtitle: "Why Some Teams Pull Together and Others Don\u2019t",
        description: "Why the best leaders create circles of safety. Explores the biology of trust (oxytocin, serotonin, cortisol), the dangers of abstraction, and how great leaders sacrifice for their teams.",
        categories: ["leadership", "psychology"],
        tags: ["trust", "safety", "oxytocin", "sacrifice", "team", "biology", "empathy"],
        icon: "fas fa-users",
        color: "#3b82f6",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-08",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Biological claims are simplified \u2014 refer to neuroscience literature for depth."
    },
    {
        id: "the-five-dysfunctions-of-a-team",
        title: "The Five Dysfunctions of a Team",
        author: "Patrick Lencioni",
        subtitle: "A Leadership Fable",
        description: "A leadership fable revealing the five dysfunctions that prevent teams from achieving results: Absence of Trust, Fear of Conflict, Lack of Commitment, Avoidance of Accountability, and Inattention to Results.",
        categories: ["leadership", "engineering-management"],
        tags: ["trust", "conflict", "commitment", "accountability", "results", "teamwork"],
        icon: "fas fa-exclamation-triangle",
        color: "#ef4444",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-08",
        language: "English",
        factCheckNote: "This summary covers the fable and model. The original includes a detailed model assessment and practical exercises."
    },
    {
        id: "dare-to-lead",
        title: "Dare to Lead",
        author: "Bren\u00e9 Brown",
        subtitle: "Brave Work. Tough Conversations. Whole Hearts.",
        description: "Leadership through vulnerability, courage, empathy, and connection. Learn to rumble with vulnerability, live into your values, BRAVING trust, and learn to rise from failures.",
        categories: ["leadership", "personal-development"],
        tags: ["vulnerability", "courage", "empathy", "trust", "values", "shame-resilience"],
        icon: "fas fa-hand-holding-heart",
        color: "#ec4899",
        chaptersCount: 8,
        status: "complete",
        dateAdded: "2025-03-08",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Bren\u00e9 Brown\u2019s research spans 20+ years \u2014 refer to the original for depth."
    },

    // ═══════════════════════════════════════
    // FINANCE & BUSINESS
    // ═══════════════════════════════════════
    {
        id: "rich-dad-poor-dad",
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        subtitle: "What the Rich Teach Their Kids About Money",
        description: "The #1 personal finance book. Contrasts the mindsets of \u2018Rich Dad\u2019 and \u2018Poor Dad\u2019 on money, assets, liabilities, financial literacy, and the importance of making money work for you.",
        categories: ["finance-business", "personal-development"],
        tags: ["money", "assets", "liabilities", "financial-literacy", "investing", "passive-income"],
        icon: "fas fa-money-bill-wave",
        color: "#14b8a6",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-03-08",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Some financial advice is debated \u2014 consult a qualified financial advisor."
    },
    {
        id: "the-lean-startup",
        title: "The Lean Startup",
        author: "Eric Ries",
        subtitle: "How Today\u2019s Entrepreneurs Use Continuous Innovation",
        description: "Build-Measure-Learn: the fundamental feedback loop of the lean startup. Covers MVP, validated learning, innovation accounting, pivoting, and how to build a sustainable business through experimentation.",
        categories: ["finance-business", "software-engineering"],
        tags: ["startup", "mvp", "pivot", "validated-learning", "build-measure-learn", "innovation"],
        icon: "fas fa-rocket",
        color: "#f97316",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-03-08",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Startup methodologies vary \u2014 adapt principles to your context."
    },
    {
        id: "zero-to-one",
        title: "Zero to One",
        author: "Peter Thiel & Blake Masters",
        subtitle: "Notes on Startups, or How to Build the Future",
        description: "Going from 0 to 1 means creating something new, not copying what exists (1 to n). Contrarian thinking, monopoly vs competition, the power law, founder archetypes, and building the future.",
        categories: ["finance-business", "non-fiction"],
        tags: ["startups", "monopoly", "contrarian", "innovation", "power-law", "technology"],
        icon: "fas fa-lightbulb",
        color: "#8b5cf6",
        chaptersCount: 10,
        status: "complete",
        dateAdded: "2025-03-08",
        language: "English",
        factCheckNote: "This summary is based on personal reading. Views are the author\u2019s perspectives \u2014 form your own judgment."
    }
];

/* To add a new book:
   1. Add an entry to BOOKS_CATALOG above
   2. Create books/{id}/data.js with the BOOK_DATA variable
   3. The library page will automatically pick it up
*/
